import {describe,it,expect,afterEach,vi} from 'vitest';
import {mkdtempSync,rmSync,writeFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {randomUUID} from 'node:crypto';
import {ConversationStore} from '../src/storage/conversations';
import {ConversationProvider} from '../src/agent/conversation-provider';
import {DropContext} from '../src/main/drop-context';
import {SettingsSchema} from '../src/shared/contracts';
import {TaskManager} from '../src/agent/tasks';
import {Artifacts} from '../src/tools/artifacts';
import {PersonalStore} from '../src/storage/personal';
const dirs:string[]=[],stores:ConversationStore[]=[];
function setup(){const dir=mkdtempSync(join(tmpdir(),'zen-chat-test-'));dirs.push(dir);const store=new ConversationStore(dir);stores.push(store);return{dir,store};}
afterEach(()=>{for(const s of stores.splice(0))try{s.close();}catch{}for(const d of dirs.splice(0))rmSync(d,{recursive:true,force:true});});
const response=(text='Respuesta',extra:any[]=[])=>({id:'resp_'+randomUUID(),model:'gpt-6.1-sol',status:'completed',output:[...extra,{id:'msg_'+randomUUID(),type:'message',role:'assistant',status:'completed',content:[{type:'output_text',text:JSON.stringify({result:text,clarifications_requested:[]}),annotations:[]}]}]});
function api(replies:any[]){const inputs:any[]=[];return{inputs,responses:{create:vi.fn(async(params:any)=>{inputs.push(structuredClone(params));const next=replies.shift();if(next instanceof Error)throw next;return(async function*(){yield{type:'response.created',response:next};yield{type:'response.output_text.delta',delta:JSON.stringify({result:'Parcial',clarifications_requested:[]})};yield{type:next.status==='incomplete'?'response.incomplete':'response.completed',response:next};})();}),compact:vi.fn(),retrieve:vi.fn(),delete:vi.fn()}};}
function provider(store:ConversationStore,client:any,overrides={}){return new ConversationProvider({store,client:()=>client,settings:()=>SettingsSchema.parse(overrides)});}
const signal=()=>new AbortController().signal;
describe('durable conversations',()=>{
 it('keeps voice fragments verbatim without inferring a completed turn or tool authority',()=>{const{store}=setup(),chat=store.create(null);store.caption(chat.id,'session:one',{id:'one',speaker:'user',phase:'start',text:'Abre'});store.caption(chat.id,'session:one',{id:'one',speaker:'user',phase:'delta',text:'Abre el documento'});expect(store.messages(chat.id)).toHaveLength(1);expect(store.messages(chat.id)[0]).toMatchObject({text:'Abre el documento',partial:true,state:'incomplete'});expect(store.context(chat.id).messages).toEqual([]);store.caption(chat.id,'other-session:one',{id:'one',speaker:'user',phase:'start',text:'Otro fragmento'});expect(store.messages(chat.id)).toHaveLength(2);});
 it('preserves generated results across restart and deletes only the owning copy',()=>{const{store}=setup(),a=store.create(null),b=store.create(null),id=randomUUID(),item={meta:{id,title:'Resultado.txt',kind:'text' as const},data:Buffer.from('Durable output'),mime:'text/plain'};store.putArtifact(a.id,item);store.putArtifact(b.id,item);const artifacts=new Artifacts(key=>store.artifact(key));expect(artifacts.get(id).data.toString()).toBe('Durable output');store.delete(a.id);expect(artifacts.get(id).data.toString()).toBe('Durable output');store.delete(b.id);expect(()=>artifacts.get(id)).toThrow();});
 it('sends only attachment metadata when a historical image is not selected',()=>{const{store}=setup(),chat=store.create(null),id=randomUUID();store.putAttachment(chat.id,{item:{id,kind:'image',name:'Image',detail:'Local',preview:'data:image/png;base64,AAAA'},image:'data:image/png;base64,AAAA',at:Date.now()});expect(store.attachmentReferences(chat.id,[])[0].item.preview).toBeUndefined();expect(store.attachmentReferences(chat.id,[id])[0].item.preview).toContain('AAAA');expect(store.attachmentReferences(chat.id,[id])[0].image).toBeUndefined();});
 it('recovers active chat, drafts and original roles on restart; marks uncertain work without replay',()=>{let{dir,store}=setup();const a=store.create(null),b=store.create(null),id=randomUUID();store.setActive(a.id);store.saveDraft(a.id,{text:'Borrador',attachmentIds:[],scrollTop:120});store.begin(a.id,id,'Dato exclusivo A');store.accept({id:'taskA',requestId:id,state:'thinking',message:'',streamText:'Parcial A'});store.close();store=new ConversationStore(dir);stores.push(store);store.recover();expect(store.active(null).id).toBe(a.id);expect(store.draft(a.id).text).toBe('Borrador');expect(store.messages(a.id).map(m=>[m.role,m.text])).toEqual([['user','Dato exclusivo A'],['assistant','Parcial A']]);expect(store.messages(a.id)[1].state).toBe('interrupted');expect(store.context(b.id).messages).toEqual([]);expect(store.begin(a.id,id,'Repeated')).toBe(false);expect(()=>store.begin(b.id,id,'Other')).toThrow();});
 it('retains streamed text across progress, failure and keeps output on originating chat',()=>{const{store}=setup(),a=store.create(null),b=store.create(null),id=randomUUID();store.begin(a.id,id,'Solicitud');store.accept({id:'t',requestId:id,state:'thinking',message:'',streamText:'Texto parcial'});store.setActive(b.id);store.accept({id:'t',state:'executing',message:'Herramienta'});store.accept({id:'t',state:'failed',message:'Conexión interrumpida'});expect(store.messages(a.id)[1].text).toContain('Texto parcial');expect(store.messages(b.id)).toEqual([]);});
 it('migration is repeatable, flags partial previews and backs up old tasks',()=>{const{dir,store}=setup();const task={id:randomUUID(),state:'completed' as const,request:'Anterior',message:'Fragmento'};store.migrate([task]);store.migrate([task]);expect(store.list(null)).toHaveLength(1);expect(store.list(null)[0].partial).toBe(true);expect(store.taskIds(store.list(null)[0].id)).toEqual([task.id]);const personal=new PersonalStore(dir);personal.task(task);const other={...task,id:randomUUID(),message:'Otra tarea'};personal.task(other);personal.removeChat(store.list(null)[0].id,store.taskIds(store.list(null)[0].id));expect(personal.tasks().map(t=>t.id)).toEqual([other.id]);expect(store.messages(store.list(null)[0].id).every(m=>m.partial)).toBe(true);});
 it('searches exact scoped originals, archive/recover, pin and page without inference',()=>{const{store}=setup();const a=store.create(null),b=store.create(randomUUID());store.begin(a.id,randomUUID(),'ID exacto 100%_AX');store.begin(b.id,randomUUID(),'Secreto B');expect(store.search(a.id,'100%_')).toHaveLength(1);expect(store.search(a.id,'Secreto B')).toEqual([]);expect(store.list(null,'recent','100%_')).toHaveLength(1);store.update(a.id,{archived:true,pinned:true,title:'Archivo'});expect(store.list(null)).toEqual([]);expect(store.list(null,'archived')[0].id).toBe(a.id);expect(()=>store.begin(a.id,randomUUID(),'mensaje')).toThrow();store.update(a.id,{archived:false});expect(store.list(null,'pinned')[0].title).toBe('Archivo');});
 it('transfers only edited snapshot and selected references, stale versions blocked and detach prevents future transfer',()=>{const{store}=setup(),a=store.create(null),b=store.create(null);store.begin(a.id,randomUUID(),'Todo el secreto A');const drop=new DropContext(v=>v);const item=drop.text('Archivo seleccionado');store.putAttachment(a.id,drop.snapshot([item.id])[0]);store.transfer(a.id,b.id,null,store.chat(a.id).version,'Solo esta frase',[item.id]);expect(store.context(b.id).messages).toEqual([]);expect(store.transfers(b.id)[0].text).toBe('Solo esta frase');expect(store.attachments(b.id)).toHaveLength(1);expect(store.attachments(b.id)[0].item.id).not.toBe(item.id);expect(()=>store.transfer(a.id,b.id,null,0,'obsolete',[])).toThrow();store.detach(b.id,store.transfers(b.id)[0].id);expect(store.transfers(b.id)[0].active).toBe(false);});
 it('deletion leaves originals and shared copies, queues remote cleanup and blocks late resurrection',()=>{const{store}=setup(),a=store.create(null),b=store.create(null),run=randomUUID();store.begin(a.id,run,'A');store.response('resp_one',a.id,run);store.transfer(a.id,b.id,null,store.chat(a.id).version,'selected',[]);store.delete(a.id);store.response('resp_late',a.id,run);expect(store.cleanup().map(r=>r.response)).toEqual(['resp_one','resp_late']);expect(()=>store.require(a.id)).toThrow();expect(()=>store.saveContext(a.id,0,[])).toThrow();expect(store.transfers(b.id)[0].text).toBe('selected');store.cleaned('resp_one','offline');expect(store.cleanup()[0].error).toBe('offline');});
 it('reports changed and missing durable file references without reading file contents',async()=>{const{dir}=setup(),path=join(dir,'sample.txt');writeFileSync(path,'abc');const d=new DropContext(v=>v),item=await d.grantFile(path,signal()),entry=d.snapshot([item.id])[0];expect((await d.availability(entry)).availability).toBe('available');writeFileSync(path,'changed content');expect((await d.availability(entry)).availability).toBe('changed');rmSync(path);expect((await d.availability(entry)).availability).toBe('missing');});
});
describe('Responses continuity',()=>{
 it('reconciliation is explicit, deduplicates stored output and never executes tool-bearing results',async()=>{const{store}=setup(),chat=store.create(null),run=randomUUID(),r=response('Recuperada');store.begin(chat.id,run,'pregunta');store.response(r.id,chat.id,run);store.saveContext(chat.id,store.runSeq(run),r.output);store.accept({id:run,requestId:run,state:'awaiting_input',message:'Desconexión'});const client=api([]);client.responses.retrieve.mockResolvedValue(r);const p=provider(store,client);expect(await p.reconcile(chat.id)).toBe(1);expect(store.context(chat.id).items).toHaveLength(1);expect(await p.reconcile(chat.id)).toBe(0);const next=randomUUID();store.begin(chat.id,next,'acción');store.response('r2',chat.id,next);store.recover();client.responses.retrieve.mockResolvedValue({...r,output:[{type:'function_call',call_id:'uncertain'}]});expect(await p.reconcile(chat.id)).toBe(0);expect(client.responses.create).not.toHaveBeenCalled();});
 it('keeps roles, routes streams to A, isolates B and excludes future queued turns',async()=>{const{store}=setup(),a=store.create(null),b=store.create(null),run=randomUUID();store.begin(a.id,run,'secreto A');store.begin(a.id,randomUUID(),'futuro A');const client=api([response('Primera'),response('B')]),p=provider(store,client);await p.run(a.id,run,'secreto A',signal(),(message,streamText)=>{store.accept({id:run,requestId:run,state:'thinking',message,streamText});store.setActive(b.id);});expect(JSON.stringify(client.inputs[0])).not.toContain('futuro A');expect(store.messages(a.id)[1].text).toBe('Parcial');const rb=randomUUID();store.begin(b.id,rb,'petición B');await p.run(b.id,rb,'petición B',signal(),()=>{});expect(JSON.stringify(client.inputs[1])).not.toContain('secreto A');expect(client.inputs[0].model).toBe('gpt-6.1-sol');expect(client.inputs[0].reasoning.effort).toBe('low');expect(client.inputs[0].conversation).toBeUndefined();expect(client.inputs[0].previous_response_id).toBeUndefined();});
 it('reuses the entire compacted window and preserves original visible messages',async()=>{const{store}=setup(),chat=store.create(null),run=randomUUID();store.begin(chat.id,run,'Largo '.repeat(2500));const client=api([response()]),window=[{type:'compaction',id:'cmp_item',encrypted_content:'opaque'},{role:'user',content:'Exact current turn'}];client.responses.compact.mockResolvedValue({id:'cmp_1',output:window});await provider(store,client,{chatContextTokens:4000}).run(chat.id,run,'Largo',signal(),()=>{});expect(client.inputs[0].input).toEqual(window);expect(store.messages(chat.id)[0].text).toContain('Largo '.repeat(2500));expect(store.context(chat.id).items[0].encrypted_content).toBe('opaque');});
 it('does not overwrite previous context if compaction fails',async()=>{const{store}=setup(),chat=store.create(null),run=randomUUID();const prior=[{role:'user',content:'X'.repeat(10000)}];store.saveContext(chat.id,0,prior);store.begin(chat.id,run,'nuevo');const client=api([]);client.responses.compact.mockRejectedValue(Error('offline'));await expect(provider(store,client,{chatContextTokens:4000}).run(chat.id,run,'nuevo',signal(),()=>{})).rejects.toThrow();expect(store.context(chat.id).items).toEqual(prior);expect(client.responses.create).not.toHaveBeenCalled();});
 it('stores structured calls/results once and never repeats an interrupted effect',async()=>{const{store}=setup(),chat=store.create(null),run=randomUUID();store.begin(chat.id,run,'hazlo');const fn={type:'function_call',id:'fc',name:'zen_desktop',call_id:'call_1',arguments:'{}'};const first={...response(),output:[fn]},client=api([first,response('Hecho')]),desktop=vi.fn(async()=>({verified:true}));await provider(store,client).run(chat.id,run,'hazlo',signal(),()=>{},undefined,undefined,desktop);expect(desktop).toHaveBeenCalledTimes(1);expect(client.inputs[1].input.some((i:any)=>i.type==='function_call_output'&&i.call_id==='call_1')).toBe(true);expect(()=>store.startTool(run,'call_1')).toThrow();const next=randomUUID();store.saveContext(chat.id,store.runSeq(run),[fn]);store.begin(chat.id,next,'continúa');client.responses.create.mockImplementationOnce(async(params:any)=>{expect(params.input.some((i:any)=>i.type==='function_call_output'&&i.output.includes('Estado por comprobar'))).toBe(true);return(async function*(){yield{type:'response.completed',response:response()};})();});await provider(store,client).run(chat.id,next,'continúa',signal(),()=>{},undefined,undefined,desktop);expect(desktop).toHaveBeenCalledTimes(1);});
 it('retains remote IDs after incomplete output and retries cleanup explicitly',async()=>{const{store}=setup(),chat=store.create(null),run=randomUUID();store.begin(chat.id,run,'test');const r={...response('partial'),status:'incomplete'},client=api([r]),p=provider(store,client);await expect(p.run(chat.id,run,'test',signal(),()=>{})).rejects.toThrow('incompleta');expect(store.run(run)?.response).toBe(r.id);store.delete(chat.id);client.responses.delete.mockRejectedValueOnce(Error('offline'));expect(await p.cleanup()).toBe(1);client.responses.delete.mockResolvedValue({});expect(await p.cleanup()).toBe(0);});
 it('serializes turns of the same chat but permits independent chats',async()=>{let unblock!:()=>void;const waiting=new Promise<void>(r=>unblock=r),entered:string[]=[];const manager=new TaskManager({client:()=>({responses:{}}) as any,settings:()=>SettingsSchema.parse({maxConcurrentTasks:3}),execute:async()=>({}) as any,emit:()=>{},log:()=>{},conversations:{run:async(chat:string,id:string)=>{entered.push(chat);if(entered.length===1)await waiting;return{message:'ok',needsInput:false};}} as any},()=>3);const a=randomUUID(),b=randomUUID();const one=manager.run('hola',randomUUID(),undefined,undefined,undefined,2,undefined,undefined,false,a);const two=manager.run('siguiente',randomUUID(),undefined,undefined,undefined,2,undefined,undefined,false,a);const three=manager.run('otro',randomUUID(),undefined,undefined,undefined,2,undefined,undefined,false,b);await new Promise(r=>setTimeout(r,30));expect(entered).toEqual([a,b]);unblock();await Promise.all([one,two,three]);expect(entered).toEqual([a,b,a]);});
});
