import { describe, it, expect, afterEach } from 'vitest';
import { mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { Spending, estimateUsd } from '../src/storage/spending';
import { SettingsSchema } from '../src/shared/contracts';
import { compactContext, economyAgent, extendedOutput, spokenSummary } from '../src/agent/economy';
import { Store } from '../src/storage/store';
const dirs: string[] = [];
const dir = () => { const path = mkdtempSync(join(tmpdir(), 'zen-spending-test-')); dirs.push(path); return path; };
afterEach(() => { dirs.forEach(path => rmSync(path, { recursive: true, force: true })); dirs.length = 0; });
describe('pay per use budget', () => {
  it('migrates older preferences and log deletion leaves budget intact', () => { const path = dir(); const store = new Store(path, { isEncryptionAvailable: () => false, encryptString: () => Buffer.from(''), decryptString: () => '' }); writeFileSync(join(path, 'settings.json'), JSON.stringify({ voiceModel: 'gpt-realtime-2.1', maxConcurrentTasks: 3, maxToolCalls: 10, listenOnInvoke: true })); expect(store.settings()).toMatchObject({ voiceModel: 'gpt-realtime-2.1-mini', maxConcurrentTasks: 1, maxToolCalls: 4, listenOnInvoke: false, monthlyBudgetEur: 100 }); const spend = new Spending(path, () => store.settings()); spend.reserve('agent', 'gpt-6.1-sol', .5); store.clearLogs(); expect(spend.summary().committedMonthEur).toBe(.5); });
  it('counts cache without duplicating reasoning or receipts', () => { const spend = new Spending(dir(), () => SettingsSchema.parse({})); const id = spend.reserve('agent', 'gpt-6.1-sol', .5); const usage = { input_tokens: 1000, input_tokens_details: { cached_tokens: 500 }, output_tokens: 100, output_tokens_details: { reasoning_tokens: 50 } }; spend.record(id, 'r1', 'gpt-6.1-sol', usage); spend.record(id, 'r1', 'gpt-6.1-sol', usage); spend.finish(id, true); expect(spend.summary()).toMatchObject({ pendingEur: 0, inputTokens: 1000, outputTokens: 100, cachedTokens: 500 }); expect(spend.summary().estimatedMonthEur).toBeCloseTo(.0023); });
  it('reserves before paid calls and blocks exceeding maximum', () => { const spend = new Spending(dir(), () => SettingsSchema.parse({ monthlyBudgetEur: 1 })); spend.reserve('agent', 'gpt-6.1-sol', .5); spend.reserve('voice', 'gpt-realtime-2.1-mini', .5); expect(() => spend.reserve('agent', 'gpt-6.1-sol', .5)).toThrow(); });
  it('restart or missing usage cannot refill budget', () => { const path = dir(); const settings = () => SettingsSchema.parse({ monthlyBudgetEur: .5 }); const spend = new Spending(path, settings); const id = spend.reserve('agent', 'gpt-6.1-sol', .5); expect(spend.record(id, 'missing', 'gpt-6.1-sol', null)).toBe(false); const recovered = new Spending(path, settings); expect(recovered.summary()).toMatchObject({ pendingEur: .5, uncertainCalls: 1 }); expect(() => recovered.reserve('agent', 'gpt-6.1-sol', .5)).toThrow(); });
  it('resets calendar month in Madrid without deleting ledger', () => { let now = new Date('2026-09-30T21:30:00Z'); const spend = new Spending(dir(), () => SettingsSchema.parse({}), () => now); spend.reserve('agent', 'gpt-6.1-sol', .5); expect(spend.summary().month).toBe('2026-09'); now = new Date('2026-09-30T22:30:00Z'); expect(spend.summary()).toMatchObject({ month: '2026-10', committedMonthEur: 0 }); });
  it('rejects corrupt ledger, unknown rates and invalid usage', () => { const path = dir(); writeFileSync(join(path, 'spending.json'), 'invalid'); expect(() => new Spending(path, () => SettingsSchema.parse({}))).toThrow(); const spend = new Spending(dir(), () => SettingsSchema.parse({})); expect(() => spend.reserve('voice', 'gpt-unknown', .5)).toThrow(); expect(estimateUsd('gpt-6.1-sol', { input_tokens: -1, output_tokens: 1 })).toBeUndefined(); });
  it('counts audio modalities and deduplicates search charges', () => { expect(estimateUsd('gpt-realtime-2.1-mini', { input_tokens: 1000, output_tokens: 100, input_token_details: { audio_tokens: 800, cached_tokens: 100, cached_tokens_details: { audio_tokens: 100 } }, output_token_details: { audio_tokens: 80 } })).toBeCloseTo(.008798); const spend = new Spending(dir(), () => SettingsSchema.parse({})); const id = spend.reserve('agent', 'gpt-6.1-sol', .5); spend.tool(id, 'web1'); spend.tool(id, 'web1'); expect(spend.summary().estimatedMonthEur).toBe(.01); });
});
describe('context and output economy', () => {
  it('selects relevant text locally and flags omissions', () => { const source = ('irrelevante '.repeat(100) + '\n').repeat(10) + 'python importante '.repeat(80); const result = compactContext(source, 'Necesito python', 2000); expect(result.length).toBeLessThanOrEqual(2000); expect(result).toContain('python'); expect(result).toContain('omitidas'); });
  it('allows extended coding output with one coordinator', () => { expect(extendedOutput('Crea código Python')).toBe(true); expect(extendedOutput('hola')).toBe(false); expect(economyAgent.multi_agent?.enabled).toBe(false); expect(spokenSummary('He abierto Bloc de notas.')).toBe('He abierto Bloc de notas.'); });
});
