import {afterEach,describe,expect,it} from 'vitest';
import {mkdtemp,mkdir,writeFile,rm,symlink} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,resolve,sep,basename} from 'node:path';
import {FolderContext} from '../src/main/folder-context';
const fixtures:string[]=[];afterEach(async()=>{for(const path of fixtures.splice(0)){const target=resolve(path);if(!target.startsWith(resolve(tmpdir())+sep)||!basename(target).startsWith('zen-folder-'))throw Error('Fixture cleanup outside temporary test directory');await rm(target,{recursive:true,force:true});}});
const signal=()=>new AbortController().signal;
async function fixture(){const root=await mkdtemp(join(tmpdir(),'zen-folder-test-'));fixtures.push(root);await mkdir(join(root,'docs'));await writeFile(join(root,'README.md'),'Proyecto de logística. Código visible: 739162.');await writeFile(join(root,'docs','architecture.md'),'La arquitectura usa React y una API independiente.');await writeFile(join(root,'.env'),'OPENAI_API_KEY=never-send-this');await mkdir(join(root,'node_modules'));await writeFile(join(root,'node_modules','large.js'),'DEPENDENCY_SHOULD_NOT_APPEAR');await writeFile(join(root,'manual.pdf'),'Synthetic binary placeholder');return root;}
describe('Carpeta adjunta para análisis',()=>{
  it('grants read context without changing library roots; reads pertinent text and describes binary limits',async()=>{const root=await fixture(),context=new FolderContext(),grant=await context.grant(root,signal());expect(grant.label).toBe(root);const value=await context.read(grant.id,'Analiza la arquitectura del proyecto',signal(),4000);expect(value.content).toContain('React');expect(value.selected[0]).toMatch(/architecture/);expect(value.content).toContain('manual.pdf');expect(value.selected).not.toContain('manual.pdf');expect(value.skipped).toBeGreaterThan(0);expect(value.content).not.toContain('.env');expect(value.content).not.toContain('never-send-this');expect(value.content).not.toContain('DEPENDENCY_SHOULD_NOT_APPEAR');expect(value.content.length).toBeLessThanOrEqual(4000);expect(value.uploadedFile).toBe(false);});
  it('resolves only the selected root for desktop handoff and rejects revoked references',async()=>{const root=await fixture(),context=new FolderContext(),grant=await context.grant(root,signal());expect(await context.resolve(grant.id,signal())).toBe(root);context.revoke(grant.id);await expect(context.resolve(grant.id,signal())).rejects.toThrow('elegir');});
  it('rejects unknown, revoked and stopped references',async()=>{const root=await fixture(),context=new FolderContext(),grant=await context.grant(root,signal());context.revoke(grant.id);await expect(context.read(grant.id,'analiza',signal(),4000)).rejects.toThrow('elegir');const next=await context.grant(root,signal());context.clear();await expect(context.read(next.id,'analiza',signal(),4000)).rejects.toThrow('elegir');const controller=new AbortController();controller.abort();await expect(context.grant(root,controller.signal)).rejects.toThrow();});
  it('does not follow a junction into another folder',async()=>{const root=await fixture(),outside=await mkdtemp(join(tmpdir(),'zen-folder-outside-'));fixtures.push(outside);await writeFile(join(outside,'private.md'),'OUTSIDE_CONTENT');await symlink(outside,join(root,'linked'),'junction');const context=new FolderContext(),grant=await context.grant(root,signal()),value=await context.read(grant.id,'private linked',signal(),4000);expect(value.content).not.toContain('OUTSIDE_CONTENT');expect(value.content).not.toContain('private.md');expect(value.skipped).toBeGreaterThan(0);});
});
