import { contextBridge, ipcRenderer, webUtils } from 'electron';
import type { ZenBridge, TaskEvent, DockEdge } from '../shared/contracts';
const bridge: ZenBridge = {
  dropFiles:async files=>{try{if(files.length>8)throw Error('Máximo 8 archivos.');const paths=files.map(file=>webUtils.getPathForFile(file));if(paths.some(path=>!path))throw Error('Ese elemento no es un archivo local. Arrastra el archivo desde el Explorador.');return await ipcRenderer.invoke('zen:drop-files',paths);}catch(error){return{ok:false,error:(error as Error).message};}},
  dropText:value=>ipcRenderer.invoke('zen:drop-text',value),dropImage:image=>ipcRenderer.invoke('zen:drop-image',image),removeContextAttachment:id=>ipcRenderer.invoke('zen:remove-context-attachment',id),activeContextAttachments:ids=>ipcRenderer.invoke('zen:active-context-attachments',ids),
  onWindowDrop:callback=>{const listener=(_e:unknown,event:Parameters<typeof callback>[0])=>callback(event);ipcRenderer.on('zen:window-drop',listener);return()=>ipcRenderer.removeListener('zen:window-drop',listener);},
  favorites:()=>ipcRenderer.invoke('zen:favorites'),saveFavorites:rows=>ipcRenderer.invoke('zen:save-favorites',rows),
  selection:()=>ipcRenderer.invoke('zen:selection'),clipboardContext:()=>ipcRenderer.invoke('zen:clipboard-context'),
  taskControl:action=>ipcRenderer.invoke('zen:task-control',action),saveResult:value=>ipcRenderer.invoke('zen:save-result',value),revealResult:id=>ipcRenderer.invoke('zen:reveal-result',id),
  onSelection:callback=>{const handler=(_e:unknown,data:Parameters<typeof callback>[0])=>callback(data);ipcRenderer.on('zen:selection',handler);return()=>ipcRenderer.removeListener('zen:selection',handler);},
  onWorkspace:callback=>{const handler=()=>callback();ipcRenderer.on('zen:workspace',handler);return()=>ipcRenderer.removeListener('zen:workspace',handler);},
  onReadResult:callback=>{const handler=(_e:unknown,data:string|null)=>callback(data);ipcRenderer.on('zen:read-result',handler);return()=>ipcRenderer.removeListener('zen:read-result',handler);},
  projectPreview:id=>ipcRenderer.invoke('zen:project-preview',id),
  projectDestination:value=>ipcRenderer.invoke('zen:project-destination',value),
  projectApprove:value=>ipcRenderer.invoke('zen:project-approve',value),
  projectDiscard:id=>ipcRenderer.invoke('zen:project-discard',id),
  chooseDirectory: () => ipcRenderer.invoke('zen:choose-directory'),
  chooseContextFolder:()=>ipcRenderer.invoke('zen:choose-context-folder'),
  removeContextFolder:id=>ipcRenderer.invoke('zen:remove-context-folder',id),
  prepare: value => ipcRenderer.invoke('zen:prepare', value),
  approve: value => ipcRenderer.invoke('zen:approve', value),
  reject: value => ipcRenderer.invoke('zen:reject', value),
  apps: () => ipcRenderer.invoke('zen:apps'),
  openApp: value => ipcRenderer.invoke('zen:open-app', value),
  openPage: value => ipcRenderer.invoke('zen:open-page', value),
  openFile: () => ipcRenderer.invoke('zen:open-file'),
  openArtifact: id => ipcRenderer.invoke('zen:open-artifact',id),
  libraryRoots: () => ipcRenderer.invoke('zen:library-roots'),
  saveLibraryRoots: paths => ipcRenderer.invoke('zen:save-library-roots',paths),
  mcpConnection:()=>ipcRenderer.invoke('zen:mcp-connection'),
  saveMcpConnection:value=>ipcRenderer.invoke('zen:save-mcp-connection',value),
  deleteMcpConnection:()=>ipcRenderer.invoke('zen:delete-mcp-connection'),
  windows: () => ipcRenderer.invoke('zen:windows'),
  observe: value => ipcRenderer.invoke('zen:observe', value),
  media: () => ipcRenderer.invoke('zen:media'),
  pauseMedia: value => ipcRenderer.invoke('zen:pause-media', value),
  profile: () => ipcRenderer.invoke('zen:profile'),
  saveProfile: value => ipcRenderer.invoke('zen:save-profile', value),
  mode: () => ipcRenderer.invoke('zen:mode'),
  setMode: value => ipcRenderer.invoke('zen:set-mode', value),
  tasks: () => ipcRenderer.invoke('zen:tasks'),
  onMode: callback => { const handler = (_event: unknown, mode: Parameters<typeof callback>[0]) => callback(mode); ipcRenderer.on('zen:mode', handler); return () => ipcRenderer.removeListener('zen:mode', handler); },
  settings: () => ipcRenderer.invoke('zen:settings'),
  saveSettings: value => ipcRenderer.invoke('zen:save-settings', value),
  saveKey: value => ipcRenderer.invoke('zen:save-key', value),
  deleteKey: () => ipcRenderer.invoke('zen:delete-key'),
  run: value => ipcRenderer.invoke('zen:run', value),
  stop: () => ipcRenderer.invoke('zen:stop'),
  cancelTask: value => ipcRenderer.invoke('zen:cancel-task', value),
  hide: () => ipcRenderer.invoke('zen:hide'),
  layout: value => ipcRenderer.invoke('zen:layout', value),
  drag: phase => ipcRenderer.invoke('zen:drag', phase),
  dock: () => ipcRenderer.invoke('zen:dock'),
  cursor:()=>ipcRenderer.invoke('zen:cursor'),
  onCursor:callback=>{const handler=(_event:unknown,point:Parameters<typeof callback>[0])=>callback(point);ipcRenderer.on('zen:cursor',handler);return()=>ipcRenderer.removeListener('zen:cursor',handler);},
  onDock: callback => { const handler = (_event: unknown, edge: DockEdge) => callback(edge); ipcRenderer.on('zen:dock', handler); return () => ipcRenderer.removeListener('zen:dock', handler); },
  voiceInterrupt: () => ipcRenderer.invoke('zen:voice-interrupt'),
  voiceContext: id => ipcRenderer.invoke('zen:voice-context', id),
  refreshScreen:explicit=>ipcRenderer.invoke('zen:screen-refresh',explicit),
  removeScreen:()=>ipcRenderer.invoke('zen:screen-remove'),
  previewScreen:()=>ipcRenderer.invoke('zen:screen-preview'),
  attachImage:image=>ipcRenderer.invoke('zen:attach-image',{image}),
  voiceStart: sdp => ipcRenderer.invoke('zen:voice-start', sdp),
  voiceEnd: value => ipcRenderer.invoke('zen:voice-end', value),
  liveReady: id => ipcRenderer.invoke('zen:live-ready',id),
  liveEnd: id => ipcRenderer.invoke('zen:live-end',id),
  liveSubmit: id => ipcRenderer.invoke('zen:live-submit',id),
  liveConfirm:()=>ipcRenderer.invoke('zen:live-confirm'),
  confirmations:()=>ipcRenderer.invoke('zen:confirmations'),
  onConfirmations:callback=>{const handler=(_event:unknown,rows:Parameters<typeof callback>[0])=>callback(rows);ipcRenderer.on('zen:confirmations',handler);return()=>ipcRenderer.removeListener('zen:confirmations',handler);},
  clearLogs: () => ipcRenderer.invoke('zen:clear-logs'),
  onTask: callback => { const handler = (_event: unknown, data: TaskEvent) => callback(data); ipcRenderer.on('zen:task', handler); return () => ipcRenderer.removeListener('zen:task', handler); },
  onInvoke: callback => { const handler = (_event: unknown, mode: 'configured' | 'voice' | 'focus' | 'capsule') => callback(mode); ipcRenderer.on('zen:invoke', handler); return () => ipcRenderer.removeListener('zen:invoke', handler); },
  onVisibility: callback => { const handler = (_event: unknown, visible: boolean) => callback(visible); ipcRenderer.on('zen:visibility', handler); return () => ipcRenderer.removeListener('zen:visibility', handler); }
};
contextBridge.exposeInMainWorld('zen', bridge);
