import {chromium} from 'playwright';
import {createServer} from 'node:http';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import {resolve,extname,sep} from 'node:path';
import assert from 'node:assert/strict';
const root=resolve('dist/renderer'),directory=resolve('docs/ui-preview/compact');
const server=createServer(async(req,res)=>{try{const path=resolve(root,'.'+new URL(req.url,'http://localhost').pathname);if(!path.startsWith(root+sep))throw Error();res.setHeader('Content-Type',({'.html':'text/html','.js':'application/javascript','.css':'text/css','.svg':'image/svg+xml','.gif':'image/gif'})[extname(path)]??'application/octet-stream');res.end(await readFile(path));}catch{res.writeHead(404).end();}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));await mkdir(directory,{recursive:true});
const browser=await chromium.launch({channel:'msedge',headless:true}),page=await browser.newPage({viewport:{width:960,height:640}}),errors=[];
page.setDefaultTimeout(8000);page.on('pageerror',e=>errors.push(e.message));
try{
 await page.goto('http://127.0.0.1:'+server.address().port+'/preview.html');
 await page.evaluate(()=>{document.body.classList.remove('preview');window.calls=[];window.zen.run=async request=>{window.calls.push(request);return{ok:true,value:{id:request.requestId,state:'completed',message:'Respuesta simulada',request:request.text}};};});
 await page.getByRole('button',{name:'Desplegar panel',exact:true}).click();
 const metrics=[];
 for(const [width,height] of [[960,640],[640,480],[480,360],[360,400],[320,480]]){
 await page.setViewportSize({width,height});await page.getByRole('button',{name:'Inicio',exact:true}).click();await page.screenshot({path:directory+'/home-'+width+'x'+height+'.png'});
 metrics.push(await page.evaluate(()=>{const home=document.querySelector('.home-page'),composer=document.querySelector('.text-composer'),header=document.querySelector('.overlay-header'),main=document.querySelector('main');return{width:innerWidth,height:innerHeight,homeHeight:home.clientHeight,homeScroll:home.scrollHeight,bodyWidth:document.body.scrollWidth,mainWidth:main.scrollWidth,composer:composer.getBoundingClientRect().toJSON(),header:header.getBoundingClientRect().toJSON()};}));
 }
 for(const m of metrics){assert.equal(m.homeHeight,m.homeScroll,'Home must fit');assert(m.bodyWidth<=m.width&&m.mainWidth<=m.width);assert(m.composer.bottom<=m.height&&m.composer.top>m.header.bottom);}
 await page.setViewportSize({width:640,height:480});
 const input=page.getByRole('textbox',{name:'Mensaje para ZEN'}),nav=name=>page.getByRole('navigation',{name:'Navegación principal'}).getByRole('button',{name,exact:true}),plus=()=>page.getByRole('button',{name:'Añadir contexto',exact:true}).click();
 const close=()=>page.getByRole('button',{name:'Volver a la conversación',exact:true}).click();
 await input.fill('Borrador de General\nSegunda línea');await nav('Chat').click();assert.equal(await input.inputValue(),'Borrador de General\nSegunda línea');
 await page.evaluate(()=>{for(let i=0;i<38;i++)window.dispatchEvent(new CustomEvent('zen-demo-task',{detail:{id:'fixture-'+i,state:'completed',request:'Petición de prueba '+i+' · '+('nombre-largo/').repeat(7),message:('Resultado de prueba '+i+'\n').repeat(120),updatedAt:Date.now(),projectContextId:null}}));});
 const chat=page.locator('.chat-scroll-content');await chat.evaluate(el=>el.scrollTop=320);const reading=await chat.evaluate(el=>el.scrollTop);assert(reading>0);
 await page.getByRole('button',{name:/^Actividad /}).click();assert.equal(await input.inputValue(),'Borrador de General\nSegunda línea');await page.screenshot({path:directory+'/activity-640x480.png'});await close();assert.equal(await chat.evaluate(el=>el.scrollTop),reading);
 await nav('Tareas').click();await page.getByRole('textbox',{name:'Buscar tarea'}).fill('prueba');const list=page.locator('.workspace-list');await list.evaluate(el=>el.scrollTop=440);await page.locator('.task-row button').nth(7).scrollIntoViewIfNeeded();const listTop=await list.evaluate(el=>el.scrollTop);
 await page.locator('.task-row button').nth(7).click();await page.getByRole('button',{name:'Volver a tareas'}).click();assert.equal(await page.getByRole('textbox',{name:'Buscar tarea'}).inputValue(),'prueba');assert.equal(await list.evaluate(el=>el.scrollTop),listTop);
 await page.locator('.task-row button').nth(7).click();await page.getByRole('textbox',{name:'Título de la tarea',exact:true}).fill('Título revisado localmente');await page.getByRole('button',{name:'Retomar conversación',exact:true}).click();assert.equal(await input.inputValue(),'');await input.fill('Borrador específico de esta tarea');await page.getByRole('button',{name:'Salir',exact:true}).click();assert.equal(await input.inputValue(),'Borrador de General\nSegunda línea');await nav('Tareas').click();await page.getByRole('button',{name:'Retomar conversación',exact:true}).click();assert.equal(await input.inputValue(),'Borrador específico de esta tarea');await page.getByRole('button',{name:'Salir',exact:true}).click();
 // Real controls, simulated local IPC. Fixtures never touch the user's projects or files.
 await page.locator('.project-chip').click();await page.getByRole('button',{name:'Gestionar proyectos',exact:true}).click();await page.getByRole('button',{name:'Nuevo proyecto',exact:true}).click();await page.getByRole('textbox',{name:'Nombre del proyecto',exact:true}).fill('Proyecto con nombre largo para verificar distribución');await page.getByRole('button',{name:'Guardar proyectos',exact:true}).click();await close();await page.getByRole('button',{name:'Cerrar aviso',exact:true}).click();
 await page.evaluate(()=>{window.zen.chooseContextFiles=async()=>({ok:true,value:[{id:crypto.randomUUID(),kind:'file',name:'general-documento.txt',detail:'Archivo de prueba local'}]});});await plus();await page.getByRole('menuitem',{name:'Adjuntar archivos',exact:true}).click();await page.getByRole('button',{name:'Revisar contexto adjunto'}).waitFor();
 await page.locator('.project-chip').click();await page.getByRole('button',{name:/Proyecto con nombre largo.*referencias elegidas/}).click();assert.equal(await input.inputValue(),'');assert.equal(await page.getByRole('button',{name:'Revisar contexto adjunto'}).count(),0);await input.fill('Borrador del otro proyecto');
 await page.locator('.project-chip').click();await page.getByRole('button',{name:/General Perfil general/}).click();assert.equal(await input.inputValue(),'Borrador de General\nSegunda línea');await page.getByRole('button',{name:'Revisar contexto adjunto'}).click();await page.locator('.context-tray').getByText('general-documento.txt',{exact:true}).waitFor();await close();
 await page.locator('.project-chip').click();await page.keyboard.press('Escape');assert.equal(await page.locator('.project-chip').evaluate(el=>el===document.activeElement),true);assert.equal(await page.getByRole('dialog',{name:'Seleccionar proyecto'}).count(),0);
 await plus();await page.keyboard.press('Escape');assert.equal(await page.getByRole('button',{name:'Añadir contexto',exact:true}).evaluate(el=>el===document.activeElement),true);
 assert.equal(await page.evaluate(()=>window.calls.length),0,'Navigation and context selection must never submit');
 for(const [width,height] of [[960,640],[640,480],[480,360],[360,400],[320,480]]){
  await page.setViewportSize({width,height});await nav('Chat').click();await input.fill(('Borrador multilínea con texto de prueba\n').repeat(12));await page.screenshot({path:directory+'/chat-'+width+'x'+height+'.png'});
  await nav('Tareas').click();await page.screenshot({path:directory+'/tasks-'+width+'x'+height+'.png'});
  await page.locator('.project-chip').click();await page.screenshot({path:directory+'/projects-'+width+'x'+height+'.png'});assert(await page.getByRole('button',{name:'Gestionar proyectos',exact:true}).isVisible());await page.keyboard.press('Escape');
  const box=await page.getByRole('button',{name:'Enviar mensaje',exact:true}).boundingBox();assert(box.x>=0&&box.x+box.width<=width&&box.y+box.height<=height,'Send must remain reachable');assert.equal(await page.evaluate(()=>document.body.scrollWidth<=innerWidth),true);
 }
 await nav('Chat').click();await page.getByRole('button',{name:'Enviar mensaje',exact:true}).click();assert.equal(await page.evaluate(()=>window.calls.length),1);await nav('Inicio').click();await nav('Chat').click();assert.equal(await page.evaluate(()=>window.calls.length),1,'No resend on navigation');
 await plus();await page.getByRole('menuitem',{name:'Guíame',exact:true}).click();await page.getByRole('textbox',{name:'¿Qué quieres hacer paso a paso?',exact:true}).fill('Objetivo de prueba');await page.getByRole('button',{name:'Cerrar',exact:true}).click();
 await page.getByRole('button',{name:'Opciones de voz y reunión',exact:true}).click();await page.getByRole('button',{name:'Modo reunión',exact:true}).click();await close();await page.getByText('Modo reunión · respuesta en texto',{exact:true}).waitFor();
 await nav('Tareas').click();await page.getByRole('button',{name:'Favoritos',exact:true}).click();await page.getByRole('textbox',{name:'Nombre',exact:true}).fill('Rutina de prueba');await page.getByRole('textbox',{name:'Instrucción',exact:true}).fill('Explica el contexto que yo seleccione.');await page.getByRole('button',{name:'Añadir favorito',exact:true}).click();await page.getByRole('button',{name:'Usar',exact:true}).click();assert.equal(await input.inputValue(),'Explica el contexto que yo seleccione.');assert.equal(await page.evaluate(()=>window.calls.length),1);
 await page.evaluate(()=>{window.dispatchEvent(new CustomEvent('zen-demo-task',{detail:{id:'fixture-permission',state:'executing',request:'Acción pendiente simulada',message:'Preparada',projectContextId:null}}));window.dispatchEvent(new CustomEvent('zen-demo-confirmations',{detail:[{key:'test',code:'123456',label:'Permiso de prueba para una acción concreta',expiresAt:Date.now()+60000}]}));});
 await page.setViewportSize({width:320,height:360});await input.fill(('Texto multilínea\n').repeat(20));await page.getByRole('button',{name:'Revisar permiso',exact:true}).click();await page.getByRole('complementary',{name:'Confirmaciones por voz o chat'}).waitFor();
 for(const name of ['Detener','Revisar permiso','Enviar mensaje']){const box=await page.getByRole('button',{name,exact:true}).boundingBox();assert(box.x>=0&&box.x+box.width<=320&&box.y+box.height<=360,name+' accessible in compact mode');}
 assert.equal(await page.evaluate(()=>document.body.scrollWidth<=innerWidth),true);await page.screenshot({path:directory+'/permissions-320x360.png'});await close();
 await page.getByRole('button',{name:'Detener',exact:true}).click();assert.equal(await page.evaluate(()=>window.calls.length),1);await page.getByRole('button',{name:'Ver aviso',exact:false}).click();await page.getByText('Se solicitó detener. El estado de cada tarea confirmará la cancelación.',{exact:true}).last().waitFor();await close();
 await page.evaluate(()=>window.dispatchEvent(new CustomEvent('zen-demo-confirmations',{detail:[]})));
 // Browser text enlargement checks reflow only, not Windows display scaling.
 await page.setViewportSize({width:360,height:400});await page.addStyleTag({content:'.compact-shell button,.compact-shell input,.compact-shell textarea,.compact-shell p{font-size:20px!important}'});await nav('Inicio').click();await page.screenshot({path:directory+'/enlarged-text.png'});const enlargedOverflow=await page.evaluate(()=>({width:document.body.scrollWidth,items:[...document.querySelectorAll('main *')].filter(e=>e.getBoundingClientRect().right>innerWidth+1).slice(0,12).map(e=>({tag:e.tagName,cls:e.className,width:e.getBoundingClientRect().width,text:e.textContent.slice(0,70)}))}));assert(enlargedOverflow.width<=360,JSON.stringify(enlargedOverflow));const enlarged=await page.getByRole('button',{name:'Enviar mensaje',exact:true}).boundingBox();assert(enlarged.y+enlarged.height<=400);
 assert.deepEqual(errors,[]);
 const result={at:new Date().toISOString(),passed:true,scope:'Renderer in Edge with simulated local IPC; no API or physical Windows/DPI input',sizes:metrics.map(({width,height})=>({width,height})),homeFits:true,sharedComposer:true,chatScrollRestored:true,taskFilterAndScrollRestored:true,taskDraftSeparated:true,projectDraftAndAttachmentsRestored:true,keyboardFocusRestored:true,actionsDoNotSend:true,singleExplicitRequest:true,meetingReachable:true,favoritesPrepareOnly:true,permissionsAndStopReachable:true,enlargedTextReflow:true,screenshots:directory};
 console.log(JSON.stringify(result,null,2));await writeFile('docs/evidence/compact-ui.json',JSON.stringify(result,null,2));
}finally{await browser.close();await new Promise(r=>server.close(r));}
