import { chromium } from 'playwright';
import { createServer } from 'node:http';
import { readFile, mkdir, writeFile } from 'node:fs/promises';
import { resolve, extname } from 'node:path';
import assert from 'node:assert/strict';
const directory = resolve('dist/renderer');
const server = createServer(async (request, response) => {
  try { const path = resolve(directory, '.' + decodeURIComponent(new URL(request.url, 'http://localhost').pathname)); if (!path.startsWith(directory + '\\') && !path.startsWith(directory + '/')) throw new Error('Invalid path'); const content = await readFile(path); response.setHeader('Content-Type', { '.html': 'text/html; charset=utf-8', '.js': 'application/javascript', '.css': 'text/css' }[extname(path)] ?? 'application/octet-stream'); response.end(content); } catch { response.writeHead(404); response.end(); }
});
await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
const base = `http://127.0.0.1:${server.address().port}/preview.html`;
const browser = await chromium.launch({ channel: 'msedge', headless: true });
const page = await browser.newPage({ viewport: { width: 1400, height: 740 } });
page.setDefaultTimeout(30000);
const errors = []; page.on('pageerror', error => errors.push(error.message));
const screenshots='docs/ui-preview/latest-'+Date.now();
await mkdir(screenshots,{recursive:true});
try {
  for (const state of ['idle', 'executing', 'completed', 'failed', 'awaiting_approval', 'streaming']) {
    await page.goto(`${base}?state=${state}`); await page.locator('.zen-overlay').waitFor();
    assert.equal(Math.round((await page.locator('main').boundingBox()).height),48);
    await page.getByRole('button', {name:'Desplegar panel'}).click();
    await page.getByRole('region', {name:'Último mensaje'}).waitFor();
    assert.equal(await page.locator('.prompt, #request, .chat-turn, .chat-messages').count(),0);
    assert.equal((await page.locator('main').boundingBox()).width,1120);
    await page.screenshot({path: `${screenshots}/${state}.png`, animations:'disabled'});
    if(state==='awaiting_approval') { await page.getByRole('button',{name:'Permitir simulación'}).click(); assert.match(await page.locator('.approval-card').innerText(),/Ninguna acción ejecutada/); }
  }
  await page.goto(`${base}?state=idle`);
  await page.evaluate(()=>{window.demoDragPhases=[];const old=window.zen.drag;window.zen.drag=async phase=>{window.demoDragPhases.push(phase);return old(phase);};});
  const brand=await page.getByRole('button',{name:'Ver último mensaje'}).boundingBox();
  await page.mouse.move(brand.x+brand.width/2,brand.y+brand.height/2);await page.mouse.down();await page.mouse.move(brand.x+180,brand.y+130,{steps:6});await page.mouse.up();
  await page.waitForFunction(()=>window.demoDragPhases.join(',')==='start,end');
  assert.equal(await page.getByRole('region',{name:'Último mensaje'}).count(),0);
  await page.getByRole('button',{name:'Desplegar panel'}).click();
  const emit=detail=>page.evaluate(detail=>window.dispatchEvent(new CustomEvent('zen-demo-task',{detail})),detail);
  await emit({id:'voice',state:'listening',message:'',utterance:{speaker:'user',id:'u1',text:'',phase:'start'}});
  await emit({id:'voice',state:'listening',message:'',utterance:{speaker:'user',id:'u1',text:'Busca en la web',phase:'delta'}});
  await page.getByText('Busca en la web',{exact:true}).waitFor();
  const beforeContext=await page.locator('.result-text').innerText();
  await emit({id:'voice',state:'idle',message:'',screenContext:{state:'queued',capturedAt:Date.now()}});
  await page.getByText('Contexto visual enviado a SOL',{exact:true}).waitFor();
  await page.screenshot({path:screenshots+'/screen-context.png',animations:'disabled'});
  assert.equal(await page.locator('.result-text').innerText(),beforeContext);
  await page.getByRole('button',{name:'Recoger panel'}).click();
  assert(await page.getByRole('button',{name:'Actualizar contexto visual',exact:true}).isVisible());
  await page.getByRole('button',{name:'Desplegar panel'}).click();
  await emit({id:'voice',state:'idle',message:'',screenContext:{state:'expired'}});
  await page.getByText('Contexto visual caducado · actualiza la referencia',{exact:true}).waitFor();
  await page.evaluate(()=>{window.fixtureRefreshes=0;window.zen.refreshScreen=async()=>{window.fixtureRefreshes++;return{ok:true,value:true};};});
  await emit({id:'voice',state:'idle',message:'',screenContext:{state:'queued',capturedAt:Date.now(),sourceTitle:'Gráfico de prueba · Navegador'}});
  await page.getByText('Contexto visual enviado a SOL · Gráfico de prueba · Navegador',{exact:true}).waitFor();
  await page.getByRole('button',{name:'Actualizar contexto visual',exact:true}).click();
  assert.equal(await page.evaluate(()=>window.fixtureRefreshes),1);
  assert.equal(await page.locator('.companion-eyes').first().evaluate(el=>getComputedStyle(el).animationName),'none');
  await emit({id:'voice',state:'idle',message:'',screenContext:{state:'idle'}});
  assert.equal((await page.locator('.message-speaker').innerText()).replace(/\s+/g,''),'TúEndirecto');
  await page.screenshot({path:screenshots+'/latest-user.png',animations:'disabled'});
  await emit({id:'voice',state:'listening',message:'',utterance:{speaker:'user',id:'u1',text:'Busca en la web',phase:'done'}});
  await emit({id:'new',state:'thinking',request:'Busca en la web',message:'Procesando'});
  assert.match(await page.locator('.result-text').innerText(),/Busca en la web/);
  await emit({id:'new',state:'thinking',request:'Busca en la web',message:'Actividad',streamText:'Respuesta provisional'});
  await page.getByText('Respuesta provisional',{exact:true}).waitFor();
  assert.equal(await page.getByText('Busca en la web',{exact:true}).count(),0);
  await emit({id:'new',state:'completed',request:'Busca en la web',message:'Resultado con [fuente oficial](https://example.com/).'});
  await page.evaluate(()=>{window.demoOpenedUrls=[];window.zen.openPage=async url=>{window.demoOpenedUrls.push(url);return{ok:true,value:{url,title:'Fixture',verified:true}};};});
  await page.getByRole('button',{name:'fuente oficial',exact:true}).click();
  assert.deepEqual(await page.evaluate(()=>window.demoOpenedUrls),['https://example.com/']);
  await emit({id:'voice',state:'listening',message:'',utterance:{speaker:'zen',id:'audio1',sourceItemId:'u1',text:'Este es el resultado hablado.',phase:'delta'}});
  await page.getByText('Este es el resultado hablado.',{exact:true}).waitFor();
  assert.equal(await page.locator('.live-message').count(),1);
  await page.getByRole('navigation',{name:'Fuentes consultadas'}).waitFor();
  await page.screenshot({path:screenshots+'/latest-zen.png',animations:'disabled'});
  await emit({id:'voice',state:'listening',message:'',utterance:{speaker:'user',id:'u2',text:'Nueva petición',phase:'start'}});
  await emit({id:'old',state:'completed',request:'Busca en la web',message:'Mensaje obsoleto'});
  await emit({id:'voice',state:'listening',message:'',utterance:{speaker:'zen',id:'audio1',sourceItemId:'u1',text:'Mensaje obsoleto',phase:'done'}});
  assert.equal(await page.getByText('Mensaje obsoleto',{exact:true}).count(),0);
  assert.equal(await page.locator('.live-message').count(),1);
  const liveRequestId='11111111-1111-4111-8111-111111111111';
  await emit({id:'voice',state:'listening',message:'',utterance:{speaker:'user',id:'live-user-1000',text:' Abre Bloc de notas',phase:'start',timeline:{startMs:1000,endMs:2000}},liveRequest:{id:liveRequestId,captionId:'live-user-1000',text:' Abre Bloc de notas'}});
  await emit({id:'voice',state:'listening',message:'',utterance:{speaker:'zen',id:'live-zen-2100',text:' Te escucho.',phase:'start',timeline:{startMs:2100,endMs:2500}}});
  await page.getByRole('button',{name:'Revisar petición para las herramientas de ZEN'}).click();
  await page.getByRole('dialog',{name:'Revisar petición a las herramientas'}).waitFor();
  assert.match(await page.getByRole('dialog').innerText(),/Abre Bloc de notas/);
  await emit({id:'voice',state:'idle',message:'',liveRequest:null});
  assert(await page.getByRole('button',{name:'Ejecutar esta petición',exact:true}).isDisabled());
  await page.keyboard.press('Escape');assert.equal(await page.getByRole('dialog').count(),0);
  await emit({id:'voice',state:'listening',message:'',utterance:{speaker:'user',id:'u2',text:'Nueva petición',phase:'start'}});
  await page.getByRole('button',{name:'Recoger panel'}).click();await page.getByRole('button',{name:'Desplegar panel'}).click();
  assert.match(await page.locator('.result-text').innerText(),/Nueva petición/);
  await page.getByRole('button',{name:'Adjuntar contexto',exact:true}).click();
  await page.getByRole('dialog',{name:'Adjuntar contexto'}).waitFor();
  await page.evaluate(()=>{window.zen.media=async()=>({ok:true,value:[{id:'fixture-player',title:'Canción de prueba',state:'Playing',canPause:true}]});window.demoMediaPauseIds=[];window.zen.pauseMedia=async id=>{window.demoMediaPauseIds.push(id);return{ok:true,value:{id,verified:true,alreadyPaused:false}};};});
  await page.getByRole('button',{name:'Ver reproductores',exact:true}).click();await page.getByRole('button',{name:'Pausar este reproductor',exact:true}).click();await page.getByText('Canción de prueba · Paused',{exact:true}).waitFor();
  assert.deepEqual(await page.evaluate(()=>window.demoMediaPauseIds),['fixture-player']);
  await page.keyboard.press('Escape');assert.equal(await page.getByRole('dialog').count(),0);assert.equal(await page.locator('main.hidden').count(),0);
  await page.evaluate(()=>{window.demoStopCalls=0;const old=window.zen.stop;window.zen.stop=async()=>{window.demoStopCalls++;return old();};});
  await page.keyboard.press('Escape');await page.locator('[data-demo-hidden="true"]').waitFor();assert.equal(await page.evaluate(()=>window.demoStopCalls),0);
  await page.goto(`${base}?state=idle`);await page.getByRole('button',{name:'Desplegar panel'}).click();
  const projectId='33333333-3333-4333-8333-333333333333';
  const draft={id:projectId,name:'Mi proyecto',summary:'Un punto de partida sencillo para tu idea.',paths:['README.md'],directories:['src','docs']};
  await emit({id:'voice',state:'listening',message:'',utterance:{speaker:'user',id:'project-user',text:'Crea un proyecto sencillo',phase:'done'}});
  await emit({id:'project-task',request:'Crea un proyecto sencillo',state:'thinking',message:'Codex está preparando tu proyecto…',workContext:{owner:'codex',phase:'preparing'}});
  await page.getByRole('button',{name:'Ver trabajo de Codex'}).click();
  assert.match(await page.locator('.context-flow').innerText(),/Dando forma a tu idea/);
  await page.screenshot({path:screenshots+'/codex-handoff.png',animations:'disabled'});
  await emit({id:'project-task',request:'Crea un proyecto sencillo',state:'awaiting_input',message:'Codex preparó tu proyecto.',workContext:{owner:'codex',phase:'review',draft}});
  await page.getByRole('article',{name:'Propuesta de Codex'}).waitFor();
  await page.getByRole('button',{name:'Ver archivos antes de crear'}).click();await page.locator('.project-preview summary').click();
  assert.match(await page.locator('.project-preview pre').innerText(),/Preparado por Codex/);
  await page.evaluate(()=>{window.zen.chooseDirectory=async()=>({ok:true,value:{grantId:'44444444-4444-4444-8444-444444444444',label:'C:\\Demo'}});window.projectApproveCalls=[];window.zen.projectApprove=async value=>{window.projectApproveCalls.push(value);return{ok:false,error:'Simulación: no se crean archivos.'};};});
  await page.getByRole('button',{name:'Elegir ubicación'}).click();await page.getByRole('button',{name:'Crear aquí',exact:true}).waitFor();
  assert.match(await page.locator('.project-destination').innerText(),/Demo/);
  await page.getByRole('button',{name:'Ocultar contenido'}).click();await page.locator('.workspace-body').evaluate(element=>element.scrollTop=0);
  await page.locator('main').screenshot({path:screenshots+'/codex-project-review.png',animations:'disabled'});
  await page.getByRole('button',{name:'Crear aquí',exact:true}).click();
  assert.deepEqual(await page.evaluate(()=>window.projectApproveCalls),[{id:projectId,approvalId:'22222222-2222-4222-8222-222222222222'}]);
  await emit({id:'voice',state:'listening',message:'',utterance:{speaker:'user',id:'other-context',text:'Mientras tanto, otra pregunta',phase:'start'}});
  await page.getByText('Mientras tanto, otra pregunta',{exact:true}).waitFor();assert.equal(await page.getByRole('article',{name:'Propuesta de Codex'}).count(),0);
  await page.getByRole('button',{name:'Ver proyecto',exact:true}).click();await page.getByRole('article',{name:'Propuesta de Codex'}).waitFor();
  await page.setViewportSize({width:320,height:600});assert((await page.locator('main').boundingBox()).width<=320);await page.screenshot({path:screenshots+'/codex-small-screen.png',animations:'disabled'});await page.setViewportSize({width:1400,height:740});
  await page.goto(`${base}?view=preferences`); await page.getByRole('heading', { name: 'A tu manera' }).waitFor();
  assert.equal(await page.getByLabel('Máximo mensual estimado (€)').inputValue(), '100');
  assert.equal(await page.getByLabel('Objetivo diario de ahorro (€)').inputValue(), '1');
  assert.match(await page.getByRole('status', { name: 'Consumo estimado' }).innerText(), /0.080.*estimados/);
  await page.getByLabel('Máximo mensual estimado (€)').fill('80');
  await page.getByRole('button', { name: 'Guardar preferencias', exact: true }).click();
  assert.equal(await page.evaluate(() => window.zen.settings().then(r => r.value.settings.monthlyBudgetEur)), 80);
  await page.getByLabel('Máximo mensual estimado (€)').fill('100');
  await page.getByRole('button', { name: 'Guardar preferencias', exact: true }).click();
  await page.locator('fieldset').filter({ has: page.getByText('Pago por uso', { exact: true }) }).screenshot({ path: screenshots+'/settings-economy.png', animations: 'disabled' });
  await page.getByText('Tu perfil y memoria', { exact: true }).click();
  await page.getByLabel('Resumen aportado por ti').fill('Aprender diseño');
  await page.getByRole('button', { name: 'Revisar importación' }).click();
  await page.getByRole('button', { name: 'Guardar importación' }).click();
  await page.getByRole('textbox', { name: 'Editar Objetivos' }).waitFor();
  await page.getByRole('textbox', { name: 'Editar Objetivos' }).fill('Aprender diseño y colaborar');
  await page.getByRole('button', { name: 'Guardar corrección' }).click();
  assert.equal(await page.getByRole('textbox', { name: 'Editar Objetivos' }).inputValue(), 'Aprender diseño y colaborar');
  const downloadPromise = page.waitForEvent('download'); await page.getByRole('button', { name: 'Exportar perfil' }).click();
  const download = await downloadPromise; const exported = JSON.parse(await readFile(await download.path(), 'utf8')); assert.equal(exported[0].content, 'Aprender diseño y colaborar');
  await page.getByRole('button', { name: 'Borrar perfil completo' }).click(); assert.equal(await page.getByRole('textbox', { name: 'Editar Objetivos' }).count(), 0);
  await page.emulateMedia({ reducedMotion: 'reduce' }); await page.goto(`${base}?state=idle`); assert.equal(await page.locator('main').evaluate(element => getComputedStyle(element).animationName), 'none');
  await page.setViewportSize({ width: 320, height: 600 }); await page.goto(`${base}?state=failed`); await page.getByRole('button',{name:'Desplegar panel'}).click(); const box = await page.locator('main').boundingBox(); assert(box.width <= 320); await page.screenshot({ path: screenshots+'/small-screen.png', animations: 'disabled' });
  await page.setViewportSize({width:1400,height:740});
  await page.goto(`${base}?state=long-result`); await page.getByRole('button',{name:'Desplegar panel'}).click();
  assert.match(await page.locator('.result-text').innerText(),/FINAL DEL RESULTADO/);
  assert.equal(await page.locator('.result-text').evaluate(el=>getComputedStyle(el).webkitLineClamp),'none');
  await page.goto(`${base}?state=streaming&tasks=2`);await page.getByRole('button',{name:'Desplegar panel'}).click();
  assert.equal(await page.locator('.live-message').count(),1);
  assert.equal(await page.getByText('Otra petición',{exact:true}).count(),0);
  await page.getByRole('button',{name:'Recoger panel'}).click();await page.getByRole('button',{name:'Detener todas las tareas'}).click();
  // Exercise real browser audio scheduling and its silence policy without API calls.
  await page.addInitScript(() => {
    window.zenToneCount = 0; window.zenAudioGains = [];
    const oscillator = AudioContext.prototype.createOscillator;
    AudioContext.prototype.createOscillator = function (...args) { window.zenToneCount++; return oscillator.apply(this, args); };
    const gain = AudioContext.prototype.createGain;
    AudioContext.prototype.createGain = function (...args) { const node = gain.apply(this, args); window.zenAudioGains.push(node); return node; };
  });
  await page.emulateMedia({ reducedMotion: 'no-preference' });
  await page.goto(`${base}?state=idle`);
  await page.getByRole('button', { name: 'Desplegar panel' }).click();
  await page.waitForFunction(() => window.zenToneCount > 0);
  const faceBefore = await page.locator('.brand-home .companion-face').getAttribute('transform');
  await page.mouse.move(800, 20);
  await page.waitForFunction(() => !!document.querySelector('.brand-home .companion-face')?.getAttribute('transform'));
  assert.notEqual(await page.locator('.brand-home .companion-face').getAttribute('transform'), faceBefore);
  await page.getByRole('button', { name: 'Modo reunión', exact: true }).click();
  await page.waitForFunction(() => window.zenAudioGains[0]?.gain.value === 0);
  const quietCount = await page.evaluate(() => window.zenToneCount);
  await page.getByRole('button', { name: 'Recoger panel', exact: true }).click();
  await page.getByRole('button', { name: 'Desplegar panel', exact: true }).click();
  await page.evaluate(() => window.dispatchEvent(new CustomEvent('zen-demo-task', { detail: { id: 'silent-task', state: 'completed', message: 'Resultado silencioso.' } })));
  await page.getByRole('button', { name: 'Recoger panel', exact: true }).click();
  await page.getByRole('button', { name: 'Desplegar panel', exact: true }).click();
  assert.equal(await page.evaluate(() => window.zenToneCount), quietCount, 'Meeting must silence navigation and task sounds');
  await page.getByRole('button', { name: 'En reunión', exact: true }).click();
  await page.waitForTimeout(120);
  await page.evaluate(() => window.dispatchEvent(new CustomEvent('zen-demo-task', { detail: { id: 'audible-task', state: 'completed', message: 'Resultado con aviso.' } })));
  await page.waitForFunction(previous => window.zenToneCount > previous, quietCount);
  const completedCount = await page.evaluate(() => window.zenToneCount);
  await page.waitForTimeout(120);
  await page.evaluate(() => window.dispatchEvent(new CustomEvent('zen-demo-task', { detail: { id: 'audible-task', state: 'completed', message: 'Resultado actualizado.' } })));
  assert.equal(await page.evaluate(() => window.zenToneCount), completedCount, 'Streaming updates must not replay completion');
  await page.evaluate(async () => {
    const settings = await window.zen.settings();
    const disabled = { ...settings.value, settings: { ...settings.value.settings, interfaceSounds: false, interfaceAnimations: false } };
    window.zen.settings = async () => ({ ok: true, value: disabled });
    window.dispatchEvent(new Event('focus'));
  });
  await page.locator('main.motion-off').waitFor();
  assert.equal(await page.locator('.companion-float').first().evaluate(el => getComputedStyle(el).animationName), 'none');
  await page.getByRole('button', { name: 'Recoger panel', exact: true }).click();
  await page.getByRole('button', { name: 'Desplegar panel', exact: true }).click();
  assert.equal(await page.evaluate(() => window.zenToneCount), completedCount, 'Disabled sounds must stay silent');
  await page.goto(`${base}?view=preferences`);
  const sounds = page.getByRole('checkbox', { name: /Sonidos suaves al abrir/ });
  const animations = page.getByRole('checkbox', { name: /Animaciones del compañero/ });
  assert(await sounds.isChecked()); assert(await animations.isChecked());
  await sounds.uncheck(); await animations.uncheck();
  await page.getByRole('button', { name: 'Guardar preferencias', exact: true }).click();
  const savedAppearance = await page.evaluate(async () => (await window.zen.settings()).value.settings);
  assert.equal(savedAppearance.interfaceSounds, false); assert.equal(savedAppearance.interfaceAnimations, false);
  assert.deepEqual(errors, []);
  const report = { at: new Date().toISOString(), browser: 'Edge headless', passed: true, checks: ['Codex project handoff and return to latest conversation', 'project file preview and exact destination approval', 'project review on small viewport', 'screen context status preserves latest message', 'compact visual context indicator and expiry', 'Live exact transcript review and stale request blocked', 'only latest user/zen message, no composer/history', 'partial captions and public agent stream', 'old responses suppressed after interruption', 'source links retained during spoken summary', 'media picker mock in context dialog', 'original companion follows pointer',   'header drag captures pointer and suppresses click', '640px capsule and 1120px latest message', 'real Web Audio tone scheduling', 'meeting immediately silences sounds', 'task updates do not repeat completion sound', 'appearance preferences save and disable sounds and animations', 'top edge in every view', 'collapse and expand without losing context', 'execution island excludes configuration', 'optional context attachment dialog', 'preferences in separate view',   'stop available while compact', 'full latest result scrolls without truncation', 'representative states', 'approval demo single use, no execution',  'Escape hides without Stop', 'latest message retained on hide', 'settings scroll panel', 'profile import editable preview, correction, export and deletion', 'reduced motion', 'small viewport', 'no page errors'], screenshots };
  await mkdir('test-results', { recursive: true }); await writeFile('test-results/ui.json', JSON.stringify(report, null, 2)); console.log(JSON.stringify(report, null, 2));
} finally { await browser.close(); await new Promise(resolve => server.close(resolve)); }
