import { chromium } from 'playwright';
import { createServer } from 'node:http';
import { readFile, mkdir, writeFile } from 'node:fs/promises';
import { resolve, extname } from 'node:path';
import assert from 'node:assert/strict';
const directory = resolve('dist/renderer');
const server = createServer(async (request, response) => {
  try { const path = resolve(directory, '.' + decodeURIComponent(new URL(request.url, 'http://localhost').pathname)); if (!path.startsWith(directory + '\\') && !path.startsWith(directory + '/')) throw new Error('Invalid path'); const content = await readFile(path); response.setHeader('Content-Type', { '.html': 'text/html; charset=utf-8', '.js': 'application/javascript', '.css': 'text/css', '.svg':'image/svg+xml', '.gif':'image/gif' }[extname(path)] ?? 'application/octet-stream'); response.end(content); } catch { response.writeHead(404); response.end(); }
});
await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
const base = `http://127.0.0.1:${server.address().port}/preview.html`;
const browser = await chromium.launch({ channel: 'msedge', headless: true });
const page = await browser.newPage({ viewport: { width: 1400, height: 740 } });
page.setDefaultTimeout(30000);
let nativeResizeCycle;
const errors = []; page.on('pageerror', error => errors.push(error.message));
const screenshots='docs/ui-preview/latest-'+Date.now();
await mkdir(screenshots,{recursive:true});
try {
  // Match Electron: mount the composer in a narrow capsule, then widen the window.
  const chatPage=await browser.newPage({viewport:{width:320,height:72}});
  await chatPage.addInitScript(()=>Object.defineProperty(window.screen,'availHeight',{get:()=>1040}));
  await chatPage.goto(`${base}?state=idle`);
  await chatPage.evaluate(()=>{document.body.classList.remove('preview');window.zen.layout=async value=>{window.lastChatLayout=value;return{ok:true,value:true};};window.dispatchEvent(new CustomEvent('zen-demo-task',{detail:{id:'voice',state:'idle',message:'',screenContext:{state:'idle'}}}));});
  await chatPage.getByRole('button',{name:'Desplegar panel'}).click();
  await chatPage.setViewportSize({width:640,height:600});
  await chatPage.waitForFunction(()=>document.querySelector('textarea').getBoundingClientRect().height===36&&document.querySelector('.latest-message').scrollHeight<=document.querySelector('.latest-message').clientHeight);
  await chatPage.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));
  const withoutContext=(await chatPage.locator('main').boundingBox()).height;
  await chatPage.evaluate(()=>window.dispatchEvent(new CustomEvent('zen-demo-task',{detail:{id:'voice',state:'idle',message:'',screenContext:{state:'ready',sourceTitle:'Pantalla de prueba - ChatGPT',capturedAt:Date.now()}}})));
  await chatPage.waitForFunction(()=>document.querySelector('.screen-context-note')&&document.querySelector('.latest-message').scrollHeight<=document.querySelector('.latest-message').clientHeight);
  await chatPage.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));
  await chatPage.locator('main').screenshot({path:screenshots+'/robot-layout.png'});
  const withContext=(await chatPage.locator('main').boundingBox()).height;
  assert.equal(withContext-withoutContext,34,'Context appearing after idle must reserve its full row');
  await chatPage.setViewportSize({width:640,height:withContext});
  assert.equal(await chatPage.evaluate(()=>window.lastChatLayout.height),withContext);
  assert(await chatPage.locator('.screen-context-chip small').isVisible());
  assert(await chatPage.locator('textarea').evaluate(el=>el.scrollHeight===el.clientHeight));
  await chatPage.locator('main').screenshot({path:`${screenshots}/chat-desktop.png`});
  await chatPage.setViewportSize({width:320,height:600});
  await chatPage.getByRole('textbox',{name:'Mensaje para ZEN'}).fill('Esta frase ocupa varias líneas cuando el panel es estrecho.');
  const narrowInput=(await chatPage.locator('textarea').boundingBox()).height;
  await chatPage.setViewportSize({width:640,height:600});
  await chatPage.waitForFunction(()=>document.querySelector('textarea').getBoundingClientRect().height===36);
  assert(narrowInput>36,'Typed text must reflow when the window widens');
  await chatPage.getByRole('textbox',{name:'Mensaje para ZEN'}).fill('');
  await chatPage.setViewportSize({width:390,height:600});
  await chatPage.waitForFunction(()=>document.querySelector('.latest-message').scrollHeight<=document.querySelector('.latest-message').clientHeight);
  assert(await chatPage.locator('main').evaluate(el=>el.scrollWidth<=el.clientWidth&&el.scrollHeight<=el.clientHeight));
  await chatPage.locator('main').screenshot({path:`${screenshots}/chat-small.png`});
  // Reproduce Electron feedback: every requested height becomes the viewport.
  await chatPage.setViewportSize({width:640,height:600});
  await chatPage.evaluate(()=>window.dispatchEvent(new CustomEvent('zen-demo-task',{detail:{id:'layout-loop',state:'awaiting_input',message:'Petición preparada en Codex del escritorio. Pulsa Enviar allí para iniciar el análisis con tu cuenta. ZEN no ha enviado los archivos a su API ni ha ejecutado el análisis.'}})));
  const resizeCycle=async()=>{const heights=[];for(let n=0;n<14;n++){await chatPage.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));const height=await chatPage.evaluate(()=>window.lastChatLayout.height);heights.push(height);await chatPage.setViewportSize({width:640,height:Math.min(600,height)});}return heights;};
  const oldBreakpoint=await chatPage.addStyleTag({content:'@media(max-height:560px){.activity-panel{flex-basis:120px}.activity-steps{height:74px}}'});
  const before=await resizeCycle();assert(new Set(before.slice(-6)).size>1,'Regression fixture must reproduce the old resize loop');
  await oldBreakpoint.evaluate(el=>el.remove());const after=await resizeCycle();
  assert.equal(new Set(after.slice(-6)).size,1,'Native viewport feedback must settle instead of flashing');
  assert(await chatPage.locator('main').evaluate(el=>el.scrollHeight<=el.clientHeight));
  nativeResizeCycle={before,after};await chatPage.locator('main').screenshot({path:screenshots+'/native-resize-stable.png',animations:'disabled'});
  await chatPage.close();
  for (const state of ['idle', 'executing', 'completed', 'failed', 'awaiting_approval', 'streaming']) {
    await page.goto(`${base}?state=${state}`); await page.locator('.zen-overlay').waitFor();
    assert.equal(Math.round((await page.locator('main').boundingBox()).height),72);
    assert.equal(Math.round((await page.locator('main').boundingBox()).width),320);
    assert.equal(await page.locator('.brand').isVisible(),false);
    assert(await page.locator('header').evaluate(el=>Array.from(el.querySelectorAll('button')).every(button=>{const b=button.getBoundingClientRect(),h=el.getBoundingClientRect();return b.left>=h.left&&b.right<=h.right&&b.top>=h.top&&b.bottom<=h.bottom;})));
    await page.locator('main').screenshot({path:`${screenshots}/mini-${state}.png`,animations:'disabled'});
    await page.getByRole('button', {name:'Desplegar panel'}).click();
    await page.getByRole('region', {name:'Último mensaje'}).waitFor();
    assert.equal(await page.locator('.prompt, #request, .chat-turn, .chat-messages').count(),0);
    assert(await page.getByRole('textbox',{name:'Mensaje para ZEN',exact:true}).isVisible());
    assert.equal((await page.locator('main').boundingBox()).width,640);
    await page.screenshot({path: `${screenshots}/${state}.png`, animations:'disabled'});
    if(state==='awaiting_approval') { await page.getByRole('button',{name:'Permitir simulación'}).click(); assert.match(await page.locator('.approval-card').innerText(),/Ninguna acción ejecutada/); }
  }
  for (const edge of ['left','right']) {
    await page.goto(`${base}?state=idle`);
    await page.evaluate(edge=>window.dispatchEvent(new CustomEvent('zen-demo-dock',{detail:edge})),edge);
    await page.waitForFunction(edge=>document.querySelector('main').classList.contains('dock-'+edge),edge);
    const rail=await page.locator('main').boundingBox(); assert.equal(Math.round(rail.width),72); assert.equal(Math.round(rail.height),320);
    assert(await page.locator('header').evaluate(el=>Array.from(el.querySelectorAll('button')).every(button=>{const b=button.getBoundingClientRect(),h=el.getBoundingClientRect();return b.left>=h.left&&b.right<=h.right&&b.top>=h.top&&b.bottom<=h.bottom;})));
    assert.equal(await page.locator('.header-status').evaluate(el=>getComputedStyle(el).writingMode),'vertical-rl');
    await page.locator('main').screenshot({path:`${screenshots}/dock-${edge}.png`,animations:'disabled'});
    await page.getByRole('button',{name:'Desplegar panel'}).click();
    await page.getByRole('textbox',{name:'Mensaje para ZEN',exact:true}).waitFor(); assert.equal((await page.locator('main').boundingBox()).width,640);
    await page.getByRole('button',{name:'Recoger panel'}).click(); assert.equal(Math.round((await page.locator('main').boundingBox()).width),72);
  }
  await page.goto(`${base}?state=idle`);
  await page.evaluate(()=>{window.demoDragPhases=[];const old=window.zen.drag;window.zen.drag=async phase=>{window.demoDragPhases.push(phase);return old(phase);};});
  const brand=await page.getByRole('button',{name:'Ver último mensaje'}).boundingBox();
  await page.mouse.move(brand.x+brand.width/2,brand.y+brand.height/2);await page.mouse.down();await page.mouse.move(brand.x+180,brand.y+130,{steps:6});await page.mouse.up();
  await page.waitForFunction(()=>window.demoDragPhases.join(',')==='start,end');
  assert.equal(await page.getByRole('region',{name:'Último mensaje'}).count(),0);
  await page.getByRole('button',{name:'Desplegar panel'}).click();
  const emit=detail=>page.evaluate(detail=>window.dispatchEvent(new CustomEvent('zen-demo-task',{detail})),detail);
  await emit({id:'voice',state:'idle',message:'',screenContext:{state:'ready',sourceTitle:'Pantalla de prueba - ChatGPT',capturedAt:Date.now()}});
  const contextBox=await page.locator('.screen-context-note').boundingBox(),composerBox=await page.locator('.text-composer').boundingBox(),footerBox=await page.locator('.microphone-group').boundingBox();
  assert(Math.abs(contextBox.x-composerBox.x)<=1);assert(Math.abs(footerBox.x-composerBox.x)<=1);
  const contextChip=await page.getByRole('button',{name:'Ver captura de referencia',exact:true}).boundingBox(),refreshButton=await page.getByRole('button',{name:'Actualizar captura',exact:true}).boundingBox();
  assert(refreshButton.x-contextChip.x-contextChip.width<20);
  assert(await page.locator('footer').evaluate(el=>Array.from(el.querySelectorAll('button')).every(button=>{const b=button.getBoundingClientRect(),f=el.getBoundingClientRect();return b.left>=f.left&&b.right<=f.right&&b.top>=f.top&&b.bottom<=f.bottom;})));
  await page.locator('main').screenshot({path:`${screenshots}/chat-aligned.png`,animations:'disabled'});

  await emit({id:'voice',state:'listening',message:'',utterance:{speaker:'user',id:'u1',text:'',phase:'start'}});
  await emit({id:'voice',state:'listening',message:'',utterance:{speaker:'user',id:'u1',text:'Busca en la web',phase:'delta'}});
  await page.getByText('Busca en la web',{exact:true}).waitFor();
  const beforeContext=await page.locator('.result-text').innerText();
  await emit({id:'voice',state:'idle',message:'',screenContext:{state:'queued',capturedAt:Date.now()}});
  await page.getByText('Preparada',{exact:false}).waitFor();
  await page.screenshot({path:screenshots+'/screen-context.png',animations:'disabled'});
  assert.equal(await page.locator('.result-text').innerText(),beforeContext);
  await page.getByRole('button',{name:'Recoger panel'}).click();
  assert.equal(await page.getByRole('button',{name:'Actualizar contexto visual',exact:true}).count(),0);
  await page.getByRole('button',{name:'Desplegar panel'}).click();
  await emit({id:'voice',state:'idle',message:'',screenContext:{state:'expired'}});
  await page.getByText('Actualiza la referencia',{exact:false}).waitFor();
  await page.evaluate(()=>{window.fixtureRefreshes=0;window.zen.refreshScreen=async()=>{window.fixtureRefreshes++;return{ok:true,value:true};};});
  await emit({id:'voice',state:'idle',message:'',screenContext:{state:'queued',capturedAt:Date.now(),sourceTitle:'Gráfico de prueba · Navegador'}});
  assert.match(await page.locator('.screen-context-note').innerText(),/Pantalla[\s\S]*Preparada/);
  await page.getByRole('button',{name:'Actualizar contexto visual',exact:true}).click();
  assert.equal(await page.evaluate(()=>window.fixtureRefreshes),1);
  assert.equal(await page.locator('.companion-eyes').first().evaluate(el=>getComputedStyle(el).animationName),'none');
  await emit({id:'voice',state:'idle',message:'',screenContext:{state:'idle'}});
  assert.match((await page.locator('.message-speaker').innerText()).replace(/\s+/g,''),/^Tú/);
  await page.screenshot({path:screenshots+'/latest-user.png',animations:'disabled'});
  await emit({id:'voice',state:'listening',message:'',utterance:{speaker:'user',id:'u1',text:'Busca en la web',phase:'done'}});
  await emit({id:'new',state:'thinking',request:'Busca en la web',message:'Procesando'});
  assert.match(await page.locator('.result-text').innerText(),/Busca en la web/);
  await emit({id:'new',state:'thinking',request:'Busca en la web',message:'Actividad',streamText:'Respuesta provisional'});
  await page.getByText('Respuesta provisional',{exact:true}).waitFor();
  assert.equal(await page.getByText('Busca en la web',{exact:true}).count(),0);
  await emit({id:'new',state:'completed',request:'Busca en la web',message:'Resultado con [fuente oficial](https://example.com/).'});
  await page.evaluate(()=>{window.demoOpenedUrls=[];window.zen.openPage=async url=>{window.demoOpenedUrls.push(url);return{ok:true,value:{url,title:'Fixture',verified:true}};};});
  await page.getByRole('button',{name:'fuente oficial',exact:true}).click();
  assert.deepEqual(await page.evaluate(()=>window.demoOpenedUrls),['https://example.com/']);
  await emit({id:'voice',state:'listening',message:'',utterance:{speaker:'zen',id:'audio1',sourceItemId:'u1',text:'Este es el resultado hablado.',phase:'delta'}});
  await page.getByText('Este es el resultado hablado.',{exact:true}).waitFor();
  assert.equal(await page.locator('.live-message').count(),1);
  await page.getByRole('navigation',{name:'Fuentes consultadas'}).waitFor();
  await page.screenshot({path:screenshots+'/latest-zen.png',animations:'disabled'});
  await emit({id:'voice',state:'listening',message:'',utterance:{speaker:'user',id:'u2',text:'Nueva petición',phase:'start'}});
  await emit({id:'old',state:'completed',request:'Busca en la web',message:'Mensaje obsoleto'});
  await emit({id:'voice',state:'listening',message:'',utterance:{speaker:'zen',id:'audio1',sourceItemId:'u1',text:'Mensaje obsoleto',phase:'done'}});
  assert.equal(await page.getByText('Mensaje obsoleto',{exact:true}).count(),0);
  assert.equal(await page.locator('.live-message').count(),1);
  const liveRequestId='11111111-1111-4111-8111-111111111111';
  await emit({id:'voice',state:'listening',message:'',utterance:{speaker:'user',id:'live-user-1000',text:' Abre Bloc de notas',phase:'start',timeline:{startMs:1000,endMs:2000}},liveRequest:{id:liveRequestId,captionId:'live-user-1000',text:' Abre Bloc de notas'}});
  await emit({id:'voice',state:'listening',message:'',utterance:{speaker:'zen',id:'live-zen-2100',text:' Te escucho.',phase:'start',timeline:{startMs:2100,endMs:2500}}});
  await page.getByRole('button',{name:'Revisar petición para las herramientas de ZEN'}).click();
  await page.getByRole('dialog',{name:'Revisar petición a las herramientas'}).waitFor();
  assert.match(await page.getByRole('dialog').innerText(),/Abre Bloc de notas/);
  await emit({id:'voice',state:'idle',message:'',liveRequest:null});
  assert(await page.getByRole('button',{name:'Ejecutar esta petición',exact:true}).isDisabled());
  await page.keyboard.press('Escape');assert.equal(await page.getByRole('dialog').count(),0);
  await emit({id:'voice',state:'listening',message:'',utterance:{speaker:'user',id:'u2',text:'Nueva petición',phase:'start'}});
  await page.getByRole('button',{name:'Recoger panel'}).click();await page.getByRole('button',{name:'Desplegar panel'}).click();
  assert.match(await page.locator('.result-text').innerText(),/Nueva petición/);
  assert.equal(await page.getByRole('button',{name:'Añadir contexto',exact:true}).count(),1);
  await page.getByRole('button',{name:'Añadir contexto',exact:true}).click();await page.getByRole('menu',{name:'Añadir contexto'}).waitFor();assert.equal(await page.getByRole('menuitem').count(),6);assert.equal(await page.getByRole('button',{name:'Elegir ventana',exact:true}).count(),0);assert.equal(await page.getByRole('dialog',{name:'Adjuntar contexto'}).count(),0);
  await page.screenshot({path:screenshots+'/attachment-menu.png',animations:'disabled'});
  await page.getByRole('menu',{name:'Añadir contexto'}).screenshot({path:screenshots+'/attachment-menu-detail.png',animations:'disabled'});
  await page.keyboard.press('ArrowDown');assert.match(await page.evaluate(()=>document.activeElement.textContent),/Texto seleccionado/);await page.keyboard.press('Escape');assert.equal(await page.getByRole('menu').count(),0);assert.equal(await page.locator('main.hidden').count(),0);
  await page.getByRole('button',{name:'Añadir contexto',exact:true}).click();await page.getByRole('menuitem',{name:/Carpeta del proyecto/}).click();await page.getByText('Analizar en Codex del escritorio',{exact:true}).waitFor();await page.screenshot({path:screenshots+'/folder-attached.png',animations:'disabled'});
  await page.evaluate(()=>{window.folderRuns=[];window.zen.run=async request=>{window.folderRuns.push(request);const value={id:'88888888-8888-4888-8888-888888888888',request:request.text,state:'completed',message:'Arquitectura revisada.'};window.dispatchEvent(new CustomEvent('zen-demo-task',{detail:{...value,state:'thinking',message:'Procesando'}}));window.dispatchEvent(new CustomEvent('zen-demo-task',{detail:value}));return{ok:true,value};};});await page.getByRole('textbox',{name:'Mensaje para ZEN',exact:true}).fill('Analiza la arquitectura de esta carpeta');await page.getByRole('textbox',{name:'Mensaje para ZEN',exact:true}).press('Enter');await page.getByText('Arquitectura revisada.',{exact:true}).waitFor();assert.equal(await page.evaluate(()=>window.folderRuns[0].folderId),'77777777-7777-4777-8777-777777777777');
  await page.getByRole('button',{name:'Quitar carpeta del proyecto'}).click();assert.equal(await page.getByText('Analizar en Codex del escritorio',{exact:true}).count(),0);
  await page.evaluate(()=>{window.demoStopCalls=0;const old=window.zen.stop;window.zen.stop=async()=>{window.demoStopCalls++;return old();};});
  await page.keyboard.press('Escape');await page.locator('[data-demo-hidden="true"]').waitFor();assert.equal(await page.evaluate(()=>window.demoStopCalls),0);
  await page.goto(`${base}?state=idle`);await page.getByRole('button',{name:'Desplegar panel'}).click();
  const projectId='33333333-3333-4333-8333-333333333333';
  const draft={id:projectId,name:'Mi proyecto',summary:'Un punto de partida sencillo para tu idea.',paths:['README.md'],directories:['src','docs']};
  await emit({id:'voice',state:'listening',message:'',utterance:{speaker:'user',id:'project-user',text:'Crea un proyecto sencillo',phase:'done'}});
  await emit({id:'project-task',request:'Crea un proyecto sencillo',state:'thinking',message:'Codex está preparando tu proyecto…',workContext:{owner:'codex',phase:'preparing'}});
  await page.getByRole('button',{name:'Ver trabajo de Codex'}).click();
  assert.match(await page.locator('.context-flow').innerText(),/Dando forma a tu idea/);
  await page.screenshot({path:screenshots+'/codex-handoff.png',animations:'disabled'});
  await emit({id:'project-task',request:'Crea un proyecto sencillo',state:'awaiting_input',message:'Codex preparó tu proyecto.',workContext:{owner:'codex',phase:'review',draft}});
  await page.getByRole('article',{name:'Propuesta de Codex'}).waitFor();
  await page.getByRole('button',{name:'Ver archivos antes de crear'}).click();await page.locator('.project-preview summary').click();
  assert.match(await page.locator('.project-preview pre').innerText(),/Preparado por Codex/);
  await page.evaluate(()=>{window.zen.chooseDirectory=async()=>({ok:true,value:{grantId:'44444444-4444-4444-8444-444444444444',label:'C:\\Demo'}});window.projectApproveCalls=[];window.zen.projectApprove=async value=>{window.projectApproveCalls.push(value);return{ok:false,error:'Simulación: no se crean archivos.'};};});
  await page.getByRole('button',{name:'Elegir ubicación'}).click();await page.getByRole('button',{name:'Crear aquí',exact:true}).waitFor();
  assert.match(await page.locator('.project-destination').innerText(),/Demo/);
  await page.getByRole('button',{name:'Ocultar contenido'}).click();await page.locator('.workspace-body:visible').evaluate(element=>element.scrollTop=0);
  await page.locator('main').screenshot({path:screenshots+'/codex-project-review.png',animations:'disabled'});
  await page.getByRole('button',{name:'Crear aquí',exact:true}).click();
  assert.deepEqual(await page.evaluate(()=>window.projectApproveCalls),[{id:projectId,approvalId:'22222222-2222-4222-8222-222222222222'}]);
  await emit({id:'voice',state:'listening',message:'',utterance:{speaker:'user',id:'other-context',text:'Mientras tanto, otra pregunta',phase:'start'}});
  await page.getByText('Mientras tanto, otra pregunta',{exact:true}).waitFor();assert.equal(await page.getByRole('article',{name:'Propuesta de Codex'}).count(),0);
  await page.getByRole('button',{name:'Ver proyecto',exact:true}).click();await page.getByRole('article',{name:'Propuesta de Codex'}).waitFor();
  await page.setViewportSize({width:320,height:600});assert((await page.locator('main').boundingBox()).width<=320);await page.screenshot({path:screenshots+'/codex-small-screen.png',animations:'disabled'});await page.setViewportSize({width:1400,height:740});
  await page.goto(`${base}?view=preferences`); await page.getByRole('heading', { name: 'A tu manera' }).waitFor();
  assert.equal(await page.getByLabel('Máximo mensual estimado (€)').inputValue(), '100');
  assert.equal(await page.getByLabel('Objetivo diario de ahorro (€)').inputValue(), '1');
  assert.match(await page.getByRole('status', { name: 'Consumo estimado' }).innerText(), /0.080.*estimados/);
  await page.getByLabel('Máximo mensual estimado (€)').fill('80');
  await page.getByRole('button', { name: 'Guardar preferencias', exact: true }).click();
  assert.equal(await page.evaluate(() => window.zen.settings().then(r => r.value.settings.monthlyBudgetEur)), 80);
  await page.getByLabel('Máximo mensual estimado (€)').fill('100');
  await page.getByRole('button', { name: 'Guardar preferencias', exact: true }).click();
  await page.locator('fieldset').filter({ has: page.getByText('Pago por uso', { exact: true }) }).screenshot({ path: screenshots+'/settings-economy.png', animations: 'disabled' });
  await page.getByText('Tu perfil y memoria', { exact: true }).click();
  await page.getByLabel('Resumen aportado por ti').fill('Aprender diseño');
  await page.getByRole('button', { name: 'Revisar importación' }).click();
  await page.getByRole('button', { name: 'Guardar importación' }).click();
  await page.getByRole('textbox', { name: 'Editar Objetivos' }).waitFor();
  await page.getByRole('textbox', { name: 'Editar Objetivos' }).fill('Aprender diseño y colaborar');
  await page.getByRole('button', { name: 'Guardar corrección' }).click();
  assert.equal(await page.getByRole('textbox', { name: 'Editar Objetivos' }).inputValue(), 'Aprender diseño y colaborar');
  const downloadPromise = page.waitForEvent('download'); await page.getByRole('button', { name: 'Exportar perfil' }).click();
  const download = await downloadPromise; const exported = JSON.parse(await readFile(await download.path(), 'utf8')); assert.equal(exported[0].content, 'Aprender diseño y colaborar');
  await page.getByRole('button', { name: 'Borrar perfil completo' }).click(); assert.equal(await page.getByRole('textbox', { name: 'Editar Objetivos' }).count(), 0);
  await page.emulateMedia({ reducedMotion: 'reduce' }); await page.goto(`${base}?state=idle`); assert.equal(await page.locator('main').evaluate(element => getComputedStyle(element).animationName), 'none');
  await page.setViewportSize({ width: 320, height: 600 }); await page.goto(`${base}?state=failed`); await page.getByRole('button',{name:'Desplegar panel'}).click(); const box = await page.locator('main').boundingBox(); assert(box.width <= 320); await page.screenshot({ path: screenshots+'/small-screen.png', animations: 'disabled' });
  await page.setViewportSize({width:1400,height:740});
  // Clipboard image stays in the renderer until the human sends the message.
  await page.goto(`${base}?state=idle`);await page.getByRole('button',{name:'Desplegar panel'}).click();
  await page.evaluate(async()=>{
    const canvas=document.createElement('canvas');canvas.width=640;canvas.height=220;const ctx=canvas.getContext('2d');ctx.fillStyle='#185bd1';ctx.fillRect(0,0,640,220);ctx.fillStyle='#fff';ctx.font='54px Arial';ctx.fillText('739162',60,120);
    window.fixtureImage=canvas.toDataURL('image/png');window.chatCalls=[];window.imageAttachments=[];
    window.zen.attachImage=async image=>{window.imageAttachments.push(image);return{ok:true,value:{observationId:'66666666-6666-4666-8666-666666666666'}};};
    window.zen.run=async value=>{window.chatCalls.push(value);await new Promise(resolve=>setTimeout(resolve,100));return{ok:true,value:{id:value.requestId,state:'completed',request:value.text,message:'Respuesta a tu captura.',verified:true}};};
    window.zen.previewScreen=async()=>({ok:true,value:{id:'fixture-screen',image:window.fixtureImage,capturedAt:Date.now(),scope:'display',sourceTitle:'Pantalla sintética'}});
    const blob=await(await fetch(window.fixtureImage)).blob(),clipboard=new DataTransfer();clipboard.items.add(new File([blob],'captura.png',{type:'image/png'}));document.querySelector('#chat-input').dispatchEvent(new ClipboardEvent('paste',{clipboardData:clipboard,bubbles:true,cancelable:true}));
  });
  await page.getByRole('img',{name:'Captura pegada para enviar'}).waitFor();assert.equal(await page.evaluate(()=>window.imageAttachments.length),0);
  const input=page.getByRole('textbox',{name:'Mensaje para ZEN',exact:true});await input.fill('Ayúdame con este mensaje');await input.press('Shift+Enter');assert.equal(await page.evaluate(()=>window.chatCalls.length),0);
  await page.screenshot({path:screenshots+'/paste-capture.png',animations:'disabled'});
  await input.press('Enter');await page.getByText('Respuesta a tu captura.',{exact:true}).waitFor();
  assert.equal(await page.evaluate(()=>window.chatCalls.length),1);assert.equal(await page.evaluate(()=>window.imageAttachments.length),1);assert.equal(await page.evaluate(()=>window.chatCalls[0].observationId),'66666666-6666-4666-8666-666666666666');assert.equal(await input.inputValue(),'');assert.equal(await page.getByRole('img',{name:'Captura pegada para enviar'}).count(),0);
  // A late voice caption cannot replace a typed request/result.
  await emit({id:'voice',state:'listening',message:'',utterance:{speaker:'zen',id:'stale-caption',text:'Texto de voz anterior',phase:'delta',timeline:{startMs:10000,endMs:11000}}});assert.equal(await page.getByText('Texto de voz anterior',{exact:true}).count(),0);
  await emit({id:'voice',state:'idle',message:'',screenContext:{state:'ready',snapshotId:'fixture-screen',scope:'display',sourceTitle:'Pantalla sintética',capturedAt:Date.now()}});await page.getByRole('button',{name:'Ver captura de referencia',exact:true}).click();await page.getByRole('dialog',{name:'Captura usada como contexto'}).waitFor();assert.equal(await page.getByRole('img',{name:'Captura exacta preparada para SOL'}).getAttribute('src'),await page.evaluate(()=>window.fixtureImage));await page.keyboard.press('Escape');assert.equal(await page.getByRole('dialog').count(),0);assert.equal(await page.locator('main.hidden').count(),0);
  await page.goto(`${base}?state=long-result`); await page.getByRole('button',{name:'Desplegar panel'}).click();
  assert.match(await page.locator('.result-text').innerText(),/FINAL DEL RESULTADO/);
  assert.equal(await page.locator('.result-text').evaluate(el=>getComputedStyle(el).webkitLineClamp),'none');
  await page.goto(`${base}?state=streaming&tasks=2`);await page.getByRole('button',{name:'Desplegar panel'}).click();
  assert.equal(await page.locator('.live-message').count(),1);
  assert.equal(await page.getByText('Otra petición',{exact:true}).count(),0);
  await page.getByRole('button',{name:'Recoger panel'}).click();await page.getByRole('button',{name:'Detener todas las tareas'}).click();
  // Exercise real browser audio scheduling and its silence policy without API calls.
  await page.addInitScript(() => {
    window.zenToneCount = 0; window.zenAudioGains = [];
    const oscillator = AudioContext.prototype.createOscillator;
    AudioContext.prototype.createOscillator = function (...args) { window.zenToneCount++; return oscillator.apply(this, args); };
    const gain = AudioContext.prototype.createGain;
    AudioContext.prototype.createGain = function (...args) { const node = gain.apply(this, args); window.zenAudioGains.push(node); return node; };
  });
  await page.emulateMedia({ reducedMotion: 'no-preference' });
  await page.goto(`${base}?state=idle`);
  await page.getByRole('button', { name: 'Desplegar panel' }).click();
  await page.waitForFunction(() => window.zenToneCount > 0);
  const faceBefore = await page.locator('.brand-home .companion-gaze').getAttribute('transform');
  const companionBox=await page.locator('.brand-home .zen-companion').boundingBox();await page.mouse.move(companionBox.x-100,companionBox.y+100);
  await page.waitForFunction(before => {const value=document.querySelector('.brand-home .companion-gaze')?.getAttribute('transform');return !!value&&value!==before;},faceBefore);
  assert.notEqual(await page.locator('.brand-home .companion-gaze').getAttribute('transform'), faceBefore);
  assert.equal(await page.locator('.brand-home .companion-face').getAttribute('transform'),null,'Only eyes follow the cursor; the visor stays still');
  await page.emulateMedia({reducedMotion:'reduce'});
  await page.waitForFunction(()=>!document.querySelector('.brand-home .companion-gaze').hasAttribute('transform'));
  await page.mouse.move(companionBox.x+400,companionBox.y+200);
  assert.equal(await page.locator('.brand-home .companion-gaze').getAttribute('transform'),null);
  await page.emulateMedia({reducedMotion:'no-preference'});
  await page.waitForFunction(()=>!document.querySelector('main').classList.contains('motion-off')&&!document.querySelector('.brand-home .zen-companion').classList.contains('still'));
  await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));
  await page.mouse.move(companionBox.x+200,companionBox.y+100);
  await page.waitForFunction(()=>document.querySelector('.brand-home .companion-gaze').hasAttribute('transform'));
  await page.locator('main').screenshot({path:screenshots+'/robot-welcome.png',animations:'disabled'});
  await page.getByRole('button',{name:'Recoger panel',exact:true}).click();
  for(const edge of ['top','left','right']){
    await page.evaluate(edge=>window.dispatchEvent(new CustomEvent('zen-demo-dock',{detail:edge})),edge);
    await page.waitForFunction(edge=>document.querySelector('main').classList.contains('dock-'+edge),edge);
    const box=await page.locator('.brand-home .zen-companion').boundingBox();
    await page.mouse.move(box.x+300,box.y+100);
    await page.waitForFunction(()=>document.querySelector('.brand-home .companion-gaze').getAttribute('transform')?.startsWith('translate('));
    await page.locator('main').screenshot({path:screenshots+`/robot-${edge}.png`,animations:'disabled'});
  }
  await page.evaluate(()=>window.dispatchEvent(new CustomEvent('zen-demo-dock',{detail:'top'})));
  await page.getByRole('button',{name:'Desplegar panel',exact:true}).click();
  await page.getByRole('button', { name: 'Modo reunión', exact: true }).click();
  await page.waitForFunction(() => window.zenAudioGains[0]?.gain.value === 0);
  const quietCount = await page.evaluate(() => window.zenToneCount);
  await page.getByRole('button', { name: 'Recoger panel', exact: true }).click();
  await page.getByRole('button', { name: 'Desplegar panel', exact: true }).click();
  await page.evaluate(() => window.dispatchEvent(new CustomEvent('zen-demo-task', { detail: { id: 'silent-task', state: 'completed', message: 'Resultado silencioso.' } })));
  await page.getByRole('button', { name: 'Recoger panel', exact: true }).click();
  await page.getByRole('button', { name: 'Desplegar panel', exact: true }).click();
  assert.equal(await page.evaluate(() => window.zenToneCount), quietCount, 'Meeting must silence navigation and task sounds');
  await page.getByRole('button', { name: 'En reunión', exact: true }).click();
  await page.waitForTimeout(120);
  await page.evaluate(() => window.dispatchEvent(new CustomEvent('zen-demo-task', { detail: { id: 'audible-task', state: 'completed', message: 'Resultado con aviso.' } })));
  await page.waitForFunction(previous => window.zenToneCount > previous, quietCount);
  const completedCount = await page.evaluate(() => window.zenToneCount);
  await page.waitForTimeout(120);
  await page.evaluate(() => window.dispatchEvent(new CustomEvent('zen-demo-task', { detail: { id: 'audible-task', state: 'completed', message: 'Resultado actualizado.' } })));
  assert.equal(await page.evaluate(() => window.zenToneCount), completedCount, 'Streaming updates must not replay completion');
  await page.evaluate(async () => {
    const settings = await window.zen.settings();
    const disabled = { ...settings.value, settings: { ...settings.value.settings, interfaceSounds: false, interfaceAnimations: false } };
    window.zen.settings = async () => ({ ok: true, value: disabled });
    window.dispatchEvent(new Event('focus'));
  });
  await page.locator('main.motion-off').waitFor();
  assert.equal(await page.locator('.companion-float').first().evaluate(el => getComputedStyle(el).animationName), 'none');
  await page.getByRole('button', { name: 'Recoger panel', exact: true }).click();
  await page.getByRole('button', { name: 'Desplegar panel', exact: true }).click();
  assert.equal(await page.evaluate(() => window.zenToneCount), completedCount, 'Disabled sounds must stay silent');
  await page.goto(`${base}?view=preferences`);
  const sounds = page.getByRole('checkbox', { name: /Sonidos suaves al abrir/ });
  const animations = page.getByRole('checkbox', { name: /Animaciones del compañero/ });
  assert(await sounds.isChecked()); assert(await animations.isChecked());
  await sounds.uncheck(); await animations.uncheck();
  await page.getByRole('button', { name: 'Guardar preferencias', exact: true }).click();
  const savedAppearance = await page.evaluate(async () => (await window.zen.settings()).value.settings);
  assert.equal(savedAppearance.interfaceSounds, false); assert.equal(savedAppearance.interfaceAnimations, false);
  await page.goto(`${base}?state=completed`);await page.getByRole('button',{name:'Desplegar panel'}).click();
  await page.waitForTimeout(850);
  const compactHeight=(await page.locator('main').boundingBox()).height;assert(compactHeight>=400&&compactHeight<560,`Compact height: ${compactHeight}`);
  await page.evaluate(()=>{
    window.fixtureLayoutCalls=[];const old=window.zen.layout;window.zen.layout=async value=>{window.fixtureLayoutCalls.push(value);return old(value);};
    window.fixtureHeaderChanges=0;window.fixtureTextChanges=0;window.fixtureArticle=document.querySelector('.live-message');window.fixtureBrand=document.querySelector('.brand-home');
    new MutationObserver(()=>window.fixtureHeaderChanges++).observe(document.querySelector('header'),{subtree:true,childList:true,attributes:true,characterData:true});
    new MutationObserver(()=>window.fixtureTextChanges++).observe(document.querySelector('.live-message'),{subtree:true,childList:true,characterData:true});
  });
  await emit({id:'fluid',state:'thinking',message:'Trabajando',streamText:'Texto'});await page.waitForTimeout(400);
  await page.evaluate(()=>{window.fixtureLayoutCalls=[];window.fixtureHeaderChanges=0;window.fixtureTextChanges=0;window.fixtureArticle=document.querySelector('.live-message');});
  await page.evaluate(async()=>{for(let n=1;n<=80;n++){window.dispatchEvent(new CustomEvent('zen-demo-task',{detail:{id:'fluid',state:'thinking',message:'Trabajando',streamText:'Texto literal ñ '.repeat(n)}}));await new Promise(resolve=>setTimeout(resolve,4));}});
  await page.waitForTimeout(70);
  const streamMetrics=await page.evaluate(()=>({height:document.querySelector('main').getBoundingClientRect().height,layouts:window.fixtureLayoutCalls.length,header:window.fixtureHeaderChanges,textPaints:window.fixtureTextChanges,sameArticle:window.fixtureArticle===document.querySelector('.live-message'),sameBrand:window.fixtureBrand===document.querySelector('.brand-home'),animation:getComputedStyle(document.querySelector('.companion-float')).animationName,text:document.querySelector('.result-text').textContent}));
  assert.equal(streamMetrics.height,544);assert.equal(streamMetrics.layouts,0);assert.equal(streamMetrics.header,0);assert(streamMetrics.textPaints<25);assert(streamMetrics.sameArticle&&streamMetrics.sameBrand);assert.equal(streamMetrics.animation,'none');assert.equal(streamMetrics.text,'Texto literal ñ '.repeat(80));
  await emit({id:'fluid',state:'completed',message:'Resultado final exacto.'});await page.getByRole('button',{name:'Copiar respuesta'}).waitFor();
  await page.evaluate(()=>{Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async text=>{window.fixtureCopied=text;}}});});
  await page.getByRole('button',{name:'Copiar respuesta'}).click();assert.equal(await page.evaluate(()=>window.fixtureCopied),'Resultado final exacto.');
  await emit({id:'voice',state:'failed',message:'Voz desconectada por inactividad.'});await page.getByText('Voz desconectada por inactividad.',{exact:false}).waitFor();assert.equal(await page.locator('.result-text').innerText(),'Resultado final exacto.');
  await page.waitForTimeout(350);assert.equal(await page.locator('.header-status').innerText(),'Listo');
  await page.screenshot({path:screenshots+'/stable-compact.png',animations:'disabled'});
  await emit({id:'fluid',state:'completed',message:'Respuesta extensa. '.repeat(180)+'FINAL'});await page.waitForTimeout(100);assert((await page.locator('main').boundingBox()).height>compactHeight);
  await page.locator('.latest-message').evaluate(el=>{el.scrollTop=el.scrollHeight;});await page.locator('.latest-message').evaluate(el=>{el.scrollTop=0;});await page.getByRole('button',{name:'Ir al final ↓',exact:true}).click();
  assert(await page.locator('.latest-message').evaluate(el=>el.scrollHeight-el.scrollTop-el.clientHeight<28));
  await page.screenshot({path:screenshots+'/stable-long.png',animations:'disabled'});
  await page.goto(`${base}?state=idle`);await page.getByRole('button',{name:'Desplegar panel'}).waitFor();
  await emit({id:'progress',state:'thinking',message:'Consultando archivos localmente…',activity:'reading'});await page.locator('.header-status').filter({hasText:'Leyendo'}).waitFor();
  await emit({id:'progress',state:'thinking',message:'Consultando fuentes web…',activity:'searching',streamText:'Texto literal'});await page.locator('.header-status').filter({hasText:'Consultando web'}).waitFor();
  await emit({id:'progress',state:'completed',message:'Resultado de la lectura'});
  await emit({id:'control',state:'idle',message:'',preparation:{requestId:'folder',active:true}});await page.locator('.header-status').filter({hasText:'Leyendo'}).waitFor();
  await emit({id:'control',state:'idle',message:'',preparation:{requestId:'folder',active:false}});await page.locator('.header-status').filter({hasText:'Listo'}).waitFor();
  await page.evaluate(async()=>{
    window.zenDemo=false;const settings=await window.zen.settings();settings.value.settings.voiceConsent=true;window.zen.settings=async()=>settings;window.dispatchEvent(new Event('focus'));
    navigator.mediaDevices.getUserMedia=async()=>{const context=new AudioContext();await context.resume();const oscillator=context.createOscillator(),gain=context.createGain(),output=context.createMediaStreamDestination();gain.gain.value=.07;oscillator.connect(gain).connect(output);oscillator.start();window.fixtureInputContext=context;return output.stream;};
    window.RTCPeerConnection=class{iceGatheringState='complete';connectionState='connected';createDataChannel(){window.fixtureChannel={};return window.fixtureChannel;}addTrack(){}async createOffer(){return{sdp:'v=0\r\n'};}async setLocalDescription(value){this.localDescription=value;}async setRemoteDescription(){}close(){}};
    window.zen.voiceStart=async()=>{setTimeout(()=>window.fixtureChannel.onmessage({data:JSON.stringify({type:'session.started'})}),10);return{ok:true,value:{sessionId:'synthetic-session',sdp:'v=0\r\n'}};};
  });
  await page.getByRole('button',{name:'Micrófono apagado · comenzar voz',exact:true}).click();
  await page.locator('.compact-meter').waitFor();await page.waitForFunction(()=>Number(document.querySelector('.compact-meter').style.getPropertyValue('--level'))>.05);
  assert.equal(Math.round((await page.locator('main').boundingBox()).width),320);assert.equal(Math.round((await page.locator('main').boundingBox()).height),72);
  assert(await page.locator('header').evaluate(el=>Array.from(el.querySelectorAll('button')).every(button=>button.getBoundingClientRect().right<=el.getBoundingClientRect().right)));
  await page.locator('main').screenshot({path:screenshots+'/mini-microphone.png',animations:'disabled'});
  for(const edge of ['left','right']){
    await page.evaluate(edge=>window.dispatchEvent(new CustomEvent('zen-demo-dock',{detail:edge})),edge);
    await page.waitForFunction(()=>document.querySelector('main').getBoundingClientRect().width===72);
    assert.equal(Math.round((await page.locator('main').boundingBox()).height),320);
    assert(await page.locator('header').evaluate(el=>Array.from(el.querySelectorAll('button,.compact-meter')).every(control=>{
      const bounds=control.getBoundingClientRect(),header=el.getBoundingClientRect();
      return bounds.left>=header.left&&bounds.right<=header.right&&bounds.top>=header.top&&bounds.bottom<=header.bottom;
    })),`Microphone and controls must fit the ${edge} rail`);
    await page.locator('main').screenshot({path:screenshots+`/mini-microphone-${edge}.png`,animations:'disabled'});
  }
  await page.evaluate(()=>window.dispatchEvent(new CustomEvent('zen-demo-dock',{detail:'top'})));
  await page.waitForFunction(()=>document.querySelector('main').getBoundingClientRect().width===320);
  await page.getByRole('button',{name:'Micrófono activo · silenciar',exact:true}).click();assert.equal(await page.locator('.compact-meter').count(),0);
  await page.getByRole('button',{name:'Desplegar panel',exact:true}).click();await page.getByRole('button',{name:'Desconectar',exact:true}).click();await page.evaluate(()=>window.fixtureInputContext.close());
  assert.deepEqual(errors, []);
  await page.goto(base);await page.getByRole('button',{name:'Desplegar panel'}).click();
  await page.evaluate(()=>window.dispatchEvent(new CustomEvent('zen-demo-confirmations',{detail:[{key:'file:fixture',label:'Crear archivo en C:\\Demo\\nota.txt',code:'1234',expiresAt:Date.now()+300000}]})));
  await page.getByRole('complementary',{name:'Confirmaciones por voz o chat'}).waitFor();assert.match(await page.locator('.human-confirmations').innerText(),/confirmo 1 2 3 4/);
  await page.evaluate(()=>{window.fixtureConfirmations=[];window.zen.run=async request=>{window.fixtureConfirmations.push(request);return{ok:true,value:{id:request.requestId,state:'completed',message:'Confirmación de prueba',localOnly:true}};};window.zen.refreshScreen=async()=>{throw Error('Una confirmación no debe renovar la captura');};});
  await page.getByRole('textbox',{name:'Mensaje para ZEN',exact:true}).fill('confirmo 1234');await page.getByRole('button',{name:'Enviar mensaje',exact:true}).click();
  assert.equal((await page.evaluate(()=>window.fixtureConfirmations))[0].text,'confirmo 1234');await page.screenshot({path:screenshots+'/confirmations-chat.png',animations:'disabled'});
  await page.evaluate(()=>window.dispatchEvent(new CustomEvent('zen-demo-confirmations',{detail:[]})));assert.equal(await page.locator('.human-confirmations').count(),0);
  await page.waitForTimeout(120);const beforeHandoffTones=await page.evaluate(()=>window.zenToneCount);
  await emit({id:'desktop-folder',state:'awaiting_input',request:'Analiza esta carpeta',message:'Petición preparada en Codex del escritorio. Pulsa Enviar allí.',workContext:{owner:'codex',phase:'external'}});await page.getByText('Continúa en Codex del escritorio',{exact:true}).waitFor();assert.match(await page.getByRole('region',{name:'Proyecto de Codex'}).innerText(),/Pulsa Enviar allí/);
  await page.waitForFunction(()=>document.querySelector('.status-label').textContent==='En Codex');
  assert.equal(await page.locator('main.attention,.activity-panel.waiting').count(),0);
  assert.doesNotMatch(await page.getByRole('region',{name:'Actividad de la tarea'}).innerText(),/Necesito tu respuesta|Tu turno|Voz o chat/);
  assert.match(await page.locator('.activity-step.current img').getAttribute('src'),/codex\.svg$/);
  await page.waitForTimeout(180);const handoffTones=await page.evaluate(()=>window.zenToneCount);
  assert(handoffTones>beforeHandoffTones,'Desktop handoff must play its local notification');
  await emit({id:'desktop-folder',state:'awaiting_input',request:'Analiza esta carpeta',message:'Petición preparada en Codex del escritorio. Pulsa Enviar allí.',workContext:{owner:'codex',phase:'external'}});
  await page.waitForTimeout(180);assert.equal(await page.evaluate(()=>window.zenToneCount),handoffTones,'Retained handoff must not repeat its sound');
  await page.screenshot({path:screenshots+'/codex-desktop.png',animations:'disabled'});
  await page.getByRole('button',{name:'Modo reunión',exact:true}).click();const quietHandoffTones=await page.evaluate(()=>window.zenToneCount);
  await emit({id:'desktop-folder-silent',state:'awaiting_input',message:'Continúa en Codex.',workContext:{owner:'codex',phase:'external'}});
  await page.waitForTimeout(180);assert.equal(await page.evaluate(()=>window.zenToneCount),quietHandoffTones,'Meeting must silence the handoff notification');
  await page.getByRole('button',{name:'En reunión',exact:true}).click();
  await page.waitForTimeout(180);assert.equal(await page.evaluate(()=>window.zenToneCount),quietHandoffTones,'Unmuting must not replay an old handoff');
  await page.getByRole('button',{name:'Volver a ZEN',exact:false}).click();
  assert.doesNotMatch(await page.locator('.robot-dock').innerText(),/Te necesito|Falta tu respuesta/);
  await emit({id:'needs-context',state:'awaiting_input',message:'Elige el dato que falta.'});
  assert.match(await page.getByRole('region',{name:'Actividad de la tarea'}).innerText(),/Necesito tu respuesta/);
  assert.equal(await page.locator('main.attention').count(),1);
  await page.evaluate(()=>{
    window.zen.refreshScreen=async()=>({ok:true,value:true});
    window.zen.run=request=>{if(request.text.startsWith('confirmo')){window.dispatchEvent(new CustomEvent('zen-demo-confirmations',{detail:[]}));window.fixtureComputerResolve({ok:true,value:{id:window.fixtureComputerRequest.requestId,state:'completed',message:'Resultado visual comprobado'}});return Promise.resolve({ok:true,value:{id:request.requestId,state:'completed',message:'Bloque confirmado',localOnly:true}});}window.fixtureComputerRequest=request;return new Promise(resolve=>{window.fixtureComputerResolve=resolve;});};
  });
  await page.getByRole('textbox',{name:'Mensaje para ZEN',exact:true}).fill('Controla la pantalla y rellena el formulario');await page.getByRole('button',{name:'Enviar mensaje',exact:true}).click();
  await page.waitForFunction(()=>window.fixtureComputerRequest&&document.querySelector('#chat-input').disabled===false&&document.querySelector('#chat-input').value==='');
  await page.evaluate(()=>window.dispatchEvent(new CustomEvent('zen-demo-confirmations',{detail:[{key:'computer:fixture',label:'Formulario: clic (10, 20)\nEscribir: "Prueba"',code:'5678',expiresAt:Date.now()+300000,preview:'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIHWP4z8DwHwAFgAI/ScLbtAAAAABJRU5ErkJggg=='}]})));
  await page.getByRole('button',{name:'Ver pantalla revisada',exact:true}).click();await page.getByRole('dialog',{name:'Captura usada como contexto'}).waitFor();await page.getByRole('button',{name:'Cerrar captura de referencia',exact:true}).click();
  await page.getByRole('textbox',{name:'Mensaje para ZEN',exact:true}).fill('confirmo 5678');await page.getByRole('button',{name:'Enviar mensaje',exact:true}).click();await page.getByText('Resultado visual comprobado',{exact:true}).waitFor();
  await page.screenshot({path:screenshots+'/computer-confirmation.png',animations:'disabled'});
  assert.deepEqual(errors, []);
  await page.setViewportSize({width:1000,height:800});await page.emulateMedia({reducedMotion:'no-preference'});
  await page.goto(base);await page.getByRole('button',{name:'Desplegar panel'}).click();
  for(const activity of ['processing','thinking','searching','structuring'])await emit({id:'activity-test',state:'thinking',activity,request:'Resume los puntos clave de esta página',message:'Avance de prueba'});
  await page.getByRole('region',{name:'Actividad de la tarea'}).waitFor();
  assert.equal(await page.locator('.activity-step').count(),4);
  assert.equal(await page.locator('.activity-step.current').innerText(),'Estructurando respuesta\nAhora');
  await page.waitForFunction(()=>Array.from(document.querySelectorAll('.activity-node img')).every(image=>image.complete&&image.naturalWidth===48));
  assert.match(await page.locator('.activity-step.current img').getAttribute('src'),/structure.gif$/);
  const gifFrames=await page.evaluate(async()=>{const data=await(await fetch('./activity/structure.gif')).arrayBuffer();const decoder=new ImageDecoder({data,type:'image/gif'});await decoder.tracks.ready;const count=decoder.tracks.selectedTrack.frameCount;const frames=[];for(const frameIndex of [0,6]){const {image}=await decoder.decode({frameIndex});const canvas=document.createElement('canvas');canvas.width=canvas.height=48;const ctx=canvas.getContext('2d');ctx.drawImage(image,0,0);frames.push(Array.from(ctx.getImageData(0,0,48,48).data).join(','));image.close();}decoder.close();return{count,different:frames[0]!==frames[1]};});
  assert.equal(gifFrames.count,24);assert(gifFrames.different);
  await page.waitForFunction(()=>document.querySelector('.status-label').textContent==='Estructurando');
  await page.locator('main').screenshot({path:screenshots+'/activity-expanded.png'});
  const activityHeight=(await page.locator('main').boundingBox()).height;
  for(let i=0;i<30;i++)await emit({id:'activity-test',state:'thinking',activity:'structuring',message:'Avance de prueba',streamText:'Respuesta '.repeat(i+1)});
  assert.equal(await page.locator('.activity-step').count(),4);assert.equal((await page.locator('main').boundingBox()).height,activityHeight);
  for(const activity of ['opening_web','opening_codex','writing']){
    await emit({id:'activity-test',state:'executing',activity,message:'Operación de prueba'});
    await page.getByRole('button',{name:'Recoger panel'}).click();assert.equal(await page.locator('.activity-panel').count(),0);
    await page.waitForTimeout(350);assert.equal(await page.locator('.status-label').innerText(),activity==='opening_web'?'Abriendo web':activity==='opening_codex'?'Abriendo Codex':'Escribiendo');
    assert(await page.locator('.status-label').evaluate(el=>el.scrollWidth<=el.clientWidth));
    for(const edge of ['left','right','top']){
      await page.evaluate(edge=>window.dispatchEvent(new CustomEvent('zen-demo-dock',{detail:edge})),edge);
      await page.waitForFunction(edge=>document.querySelector('main').classList.contains('dock-'+edge),edge);
      assert(await page.locator('header').evaluate(el=>Array.from(el.querySelectorAll('button')).every(button=>{const b=button.getBoundingClientRect(),h=el.getBoundingClientRect();return b.left>=h.left&&b.right<=h.right&&b.top>=h.top&&b.bottom<=h.bottom;})));
      assert(await page.locator('.status-label').evaluate(el=>el.scrollWidth<=el.clientWidth&&el.scrollHeight<=el.clientHeight));
    }
    await page.locator('main').screenshot({path:`${screenshots}/activity-capsule-${activity}.png`});
    await page.getByRole('button',{name:'Desplegar panel'}).click();
  }
  await page.emulateMedia({reducedMotion:'reduce'});await page.waitForFunction(()=>document.querySelector('.activity-step.current img').src.endsWith('.svg'));
  await page.locator('main').screenshot({path:screenshots+'/activity-static.png',animations:'disabled'});
  await emit({id:'activity-test',state:'cancelled',message:'Tarea de prueba detenida'});assert.match(await page.locator('.activity-step.current').innerText(),/Tarea detenida/);
  assert.equal(await page.locator('.activity-step.current.activity-completed').count(),0);
  await page.setViewportSize({width:390,height:600});await page.locator('main').screenshot({path:screenshots+'/activity-small.png',animations:'disabled'});
  assert(await page.getByRole('textbox',{name:'Mensaje para ZEN',exact:true}).isVisible());
  assert(await page.locator('main').evaluate(el=>el.scrollWidth<=el.clientWidth&&el.scrollHeight<=el.clientHeight+1));
  await page.setViewportSize({width:640,height:740});await page.goto(`${base}?state=idle`);await page.getByRole('button',{name:'Desplegar panel'}).click();
  await page.evaluate(()=>{window.workspaceCalls=[];window.zen.run=async request=>{window.workspaceCalls.push(request);return {ok:true,value:{id:request.requestId,request:request.text,state:'completed',message:'Resultado de prueba'}};};window.zen.tasks=async()=>({ok:true,value:[{id:'resume-test',request:'Revisa el formulario',state:'failed',message:'Interrumpida',checkpoint:'Campo verificado'}]});});
  await page.getByRole('button',{name:'Tareas y favoritos',exact:true}).click();await page.getByText('Campo verificado',{exact:true}).waitFor();
  await page.getByRole('button',{name:'Retomar / corregir',exact:true}).click();await page.waitForFunction(()=>document.querySelector('textarea').value==='Revisa el formulario');assert.equal(await page.evaluate(()=>window.workspaceCalls.length),0);
  await page.getByRole('textbox',{name:'Mensaje para ZEN'}).fill('Revisa el formulario y corrige el último campo');await page.getByRole('textbox',{name:'Mensaje para ZEN'}).press('Enter');await page.waitForFunction(()=>window.workspaceCalls.length===1);assert.equal(await page.evaluate(()=>window.workspaceCalls[0].replyTaskId),'resume-test');
  await page.getByRole('button',{name:'Tareas y favoritos',exact:true}).click();await page.getByRole('button',{name:'Favoritos',exact:true}).click();await page.getByLabel('Nombre',{exact:true}).fill('Mi favorito');await page.getByLabel('Instrucción',{exact:true}).fill('Resume este texto');await page.getByRole('button',{name:'Añadir favorito',exact:true}).click();await page.getByText('Mi favorito',{exact:true}).waitFor();
  await page.getByRole('button',{name:'Cerrar tareas y favoritos'}).click();await page.getByRole('button',{name:'Tareas y favoritos',exact:true}).click();await page.getByRole('button',{name:'Favoritos',exact:true}).click();await page.getByText('Mi favorito',{exact:true}).waitFor();await page.locator('main').screenshot({path:screenshots+'/workspace-favorites.png'});
  await page.getByRole('button',{name:'Usar',exact:true}).click();await page.waitForFunction(()=>document.querySelector('textarea').value==='Resume este texto');assert.equal(await page.getByLabel('Presupuesto por tarea').count(),0);assert.equal(await page.locator('.route-label').count(),0);assert.equal(await page.evaluate(()=>window.workspaceCalls.length),1);
  await page.getByRole('button',{name:'Añadir contexto',exact:true}).click();await page.getByRole('menuitem',{name:/Texto copiado/}).click();await page.getByText('Texto seleccionado de prueba',{exact:true}).waitFor();await page.getByRole('button',{name:'Resume',exact:true}).click();await page.getByRole('textbox',{name:'Mensaje para ZEN'}).press('Enter');await page.waitForFunction(()=>window.workspaceCalls.length===2);assert(await page.evaluate(()=>!!window.workspaceCalls[1].observationId&&window.workspaceCalls[1].budgetEur===undefined));
  await page.evaluate(()=>{const c=document.createElement('canvas');c.width=400;c.height=200;const ctx=c.getContext('2d');ctx.fillStyle='purple';ctx.fillRect(0,0,400,200);window.zen.previewScreen=async()=>({ok:true,value:{id:'region-fixture',image:c.toDataURL(),capturedAt:Date.now(),scope:'display'}});window.zen.attachImage=async image=>{window.croppedImage=image;return {ok:true,value:{observationId:'crop-observation'}};};});
  await page.getByRole('button',{name:'Añadir contexto',exact:true}).click();await page.getByRole('menuitem',{name:/Zona de pantalla/}).click();const regionBox=await page.getByRole('img',{name:'Pantalla para seleccionar una zona'}).boundingBox();await page.mouse.move(regionBox.x+regionBox.width*.1,regionBox.y+regionBox.height*.1);await page.mouse.down();await page.mouse.move(regionBox.x+regionBox.width*.6,regionBox.y+regionBox.height*.6);await page.mouse.up();await page.getByRole('button',{name:'Usar esta zona',exact:true}).click();await page.getByRole('textbox',{name:'Mensaje para ZEN'}).fill('Explica la zona');await page.getByRole('textbox',{name:'Mensaje para ZEN'}).press('Enter');await page.waitForFunction(()=>window.workspaceCalls.length===3);assert.equal(await page.evaluate(()=>window.workspaceCalls[2].observationId),'crop-observation');assert.deepEqual(await page.evaluate(async()=>{const img=new Image();img.src=window.croppedImage;await img.decode();return [img.width,img.height];}),[200,100]);
  assert.deepEqual(errors,[]);
  // Context drops stay local until a separate Send; never become instructions.
  await page.goto(base);
  await page.evaluate(()=>{window.dropRequests=[];window.zen.run=async request=>{window.dropRequests.push(request);return{ok:true,value:{id:request.requestId,state:'completed',message:'Respuesta local de prueba'}};};});
  const dropTextData=await page.evaluateHandle(()=>{const data=new DataTransfer();data.setData('text/plain','Texto de referencia, nunca una petición automática.');return data;});
  await page.locator('main').dispatchEvent('dragenter',{dataTransfer:dropTextData});assert(await page.locator('main').evaluate(el=>el.classList.contains('capsule')&&el.classList.contains('drop-ready')));
  await page.locator('main').dispatchEvent('drop',{dataTransfer:dropTextData});await page.getByRole('region',{name:'Contexto adjunto'}).waitFor();
  assert.equal(await page.getByRole('textbox',{name:'Mensaje para ZEN',exact:true}).inputValue(),'');assert.equal(await page.evaluate(()=>window.dropRequests.length),0);
  await page.getByRole('button',{name:'Enviar mensaje',exact:true}).click();await page.waitForFunction(()=>window.dropRequests.length===1);assert.equal((await page.evaluate(()=>window.dropRequests))[0].attachmentIds.length,1);
  await page.getByRole('button',{name:'Quitar adjunto Texto arrastrado',exact:true}).click();assert.equal(await page.locator('.drop-attachment').count(),0);
  const dropFilesData=await page.evaluateHandle(()=>{const data=new DataTransfer();data.items.add(new File(['documento'],'manual.pdf',{type:'application/pdf'}));data.items.add(new File(['a,b\n1,2'],'datos.csv',{type:'text/csv'}));return data;});
  await page.locator('main').dispatchEvent('drop',{dataTransfer:dropFilesData});await page.getByRole('button',{name:'Quitar adjunto manual.pdf',exact:true}).waitFor();assert.equal(await page.locator('.drop-attachment').count(),2);assert.equal(await page.evaluate(()=>window.dropRequests.length),1);
  await page.getByRole('button',{name:'Quitar adjunto manual.pdf',exact:true}).click();await page.getByRole('button',{name:'Quitar adjunto datos.csv',exact:true}).click();
  await page.getByRole('button',{name:'Recoger panel',exact:true}).click();
  await page.evaluate(()=>window.dispatchEvent(new CustomEvent('zen-demo-window-drop',{detail:{state:'hover',name:'Ventana de prueba'}})));assert(await page.locator('main').evaluate(el=>el.classList.contains('capsule')&&el.classList.contains('drop-ready')));
  await page.evaluate(()=>{const canvas=document.createElement('canvas');canvas.width=160;canvas.height=60;const ctx=canvas.getContext('2d');ctx.fillStyle='#263f4b';ctx.fillRect(0,0,160,60);ctx.fillStyle='#fff';ctx.fillText('Ventana de prueba',10,30);window.dispatchEvent(new CustomEvent('zen-demo-window-drop',{detail:{state:'ready',item:{id:crypto.randomUUID(),name:'Ventana de prueba',kind:'window',detail:'Captura local',preview:canvas.toDataURL()}}}));});
  await page.getByRole('button',{name:'Quitar adjunto Ventana de prueba',exact:true}).waitFor();await page.getByText('Ver referencia',{exact:true}).click();assert(await page.getByAltText('Referencia: Ventana de prueba',{exact:true}).isVisible());assert.equal(await page.evaluate(()=>window.dropRequests.length),1);
  await page.locator('main').screenshot({path:screenshots+'/drop-window-preview.png',animations:'disabled'});
  await page.getByRole('button',{name:'Quitar adjunto Ventana de prueba',exact:true}).click();
  await page.evaluate(()=>{window.zen.dropFiles=async()=>({ok:true,value:{folder:{id:crypto.randomUUID(),name:'Proyecto arrastrado',label:'C:\\Demo\\Proyecto'}}});});
  await page.locator('main').dispatchEvent('drop',{dataTransfer:dropFilesData});await page.getByRole('button',{name:'Quitar carpeta del proyecto',exact:true}).waitFor();assert.match(await page.locator('.composer-folder').innerText(),/Codex/);assert.equal(await page.evaluate(()=>window.dropRequests.length),1);
  await dropTextData.dispose();await dropFilesData.dispose();assert.deepEqual(errors,[]);
  // The robot reacts only to observed state; greeting never invokes a tool/model.
  await page.setViewportSize({width:1000,height:900});await page.emulateMedia({reducedMotion:'no-preference'});
  await page.goto(base);await page.getByRole('button',{name:'Desplegar panel'}).click();
  assert.equal(await page.locator('.robot-dock .robot-hand').count(),2);
  assert.equal((await page.locator('.robot-dock .zen-companion').boundingBox()).height,144);
  await page.evaluate(()=>{window.robotRunCalls=0;window.zen.run=async()=>{window.robotRunCalls++;throw Error('Greeting must stay local');};});
  await page.getByRole('button',{name:'Saludar a ZEN'}).click();await page.locator('.robot-dock .robot-waving').waitFor();
  assert.equal(await page.evaluate(()=>window.robotRunCalls),0);
  await page.locator('main').screenshot({path:screenshots+'/robot-greeting.png'});
  for(const [state,activity,pose] of [['thinking','thinking','thinking'],['thinking','reading','reading'],['thinking','writing','typing'],['executing','executing','working'],['awaiting_approval','approval','approval'],['failed','failed','concerned'],['completed','completed','success'],['cancelled','cancelled','paused']]){
    await emit({id:'robot-poses',state,activity,message:'Vista previa local de los gestos.'});
    await page.waitForFunction(pose=>document.querySelector('.robot-dock').dataset.pose===pose,pose);
    assert.equal(await page.locator('.brand-home .zen-companion').getAttribute('data-pose'),pose);
    assert.equal(await page.locator('.robot-dock .robot-waving').count(),0);
    await page.waitForTimeout(350);
    await page.locator('main').screenshot({path:screenshots+'/robot-'+pose+'.png',animations:'disabled'});
  }
  await emit({id:'robot-poses',state:'thinking',activity:'reading',paused:true,message:'Pausado'});
  await page.waitForFunction(()=>document.querySelector('.robot-dock').dataset.pose==='paused');
  await emit({id:'robot-poses',state:'thinking',activity:'writing',paused:false,message:'Escribiendo'});
  await page.emulateMedia({reducedMotion:'reduce'});
  await page.waitForFunction(()=>document.querySelector('main').classList.contains('motion-off'));
  assert(await page.locator('.zen-robot').evaluateAll(robots=>robots.every(robot=>[...robot.querySelectorAll('*')].every(el=>getComputedStyle(el).animationName==='none'))));
  assert.deepEqual(errors,[]);
  const report = { at: new Date().toISOString(), browser: 'Edge headless', passed: true, nativeResizeCycle, streamMetrics, compactHeight, checks: ['text, file and native-window drop UI: no automatic request, removable local references, preview, explicit send IDs and Codex folder route', 'larger full-body robot, two hands, observed task gestures, greeting without API, paused/failure/approval semantics and reduced-motion gestures', 'compact real Web Audio microphone meter with mock transport; mute removes meter', 'observed local reading and Live progress', 'actual activity stages, bounded timeline, no duplicate steps or resizing per delta', 'capsule shows only current status without text clipping', 'GIF assets decode, reduced motion uses static SVG', 'cancelled task never becomes completed; small viewport controls remain usable', 'computer task leaves chat available; exact preview and chat confirmation continue the same task', 'confirmation code visible; chat confirmation avoids screen capture', 'desktop Codex handoff uses neutral En Codex status, one local chime, no repeat on updates/unmute, meeting silence and genuine input prompts preserved', 'streaming: stable DOM/header/bounds, batched literal text', 'compact height and expanded long response', 'copy exact response and follow tail', 'voice warning preserves conversation', 'Codex project handoff and return to latest conversation', 'project file preview and exact destination approval', 'project review on small viewport', 'screen context status preserves latest message', 'compact visual context indicator and expiry', 'Live exact transcript review and stale request blocked', 'latest message with text composer and clipboard image priority', 'manual image stays local before send', 'exact screenshot preview and stale caption suppression', 'partial captions and public agent stream', 'old responses suppressed after interruption', 'source links retained during spoken summary', 'single clip with six context options; no window or media picker', 'favorites persist locally, editable resume carries task id, selected text and cropped image sent only on submit, chat omits cost controls and uses the configured backend budget', 'original companion follows pointer', 'header drag captures pointer and suppresses click', '320×72 top capsule, 72×320 side rail and 640px chat', 'real Web Audio tone scheduling', 'meeting immediately silences sounds', 'task updates do not repeat completion sound', 'appearance preferences save and disable sounds and animations', 'top edge in every view', 'collapse and expand without losing context', 'execution island excludes configuration', 'compact attachment popover and removable project folder', 'preferences in separate view', 'stop available while compact', 'full latest result scrolls without truncation', 'representative states', 'approval demo single use, no execution', 'Escape hides without Stop', 'latest message retained on hide', 'settings scroll panel', 'profile import editable preview, correction, export and deletion', 'reduced motion', 'small viewport', 'no page errors'], screenshots };
  await mkdir('test-results', { recursive: true }); await writeFile('test-results/ui.json', JSON.stringify(report, null, 2)); console.log(JSON.stringify(report, null, 2));
} finally { await browser.close(); await new Promise(resolve => server.close(resolve)); }
