import { chromium } from 'playwright';
import { createServer } from 'node:http';
import { readFile, mkdir, writeFile } from 'node:fs/promises';
import { resolve, extname } from 'node:path';
import assert from 'node:assert/strict';
const directory = resolve('dist/renderer');
const server = createServer(async (request, response) => {
  try { const path = resolve(directory, '.' + decodeURIComponent(new URL(request.url, 'http://localhost').pathname)); if (!path.startsWith(directory + '\\') && !path.startsWith(directory + '/')) throw new Error('Invalid path'); const content = await readFile(path); response.setHeader('Content-Type', { '.html': 'text/html; charset=utf-8', '.js': 'application/javascript', '.css': 'text/css' }[extname(path)] ?? 'application/octet-stream'); response.end(content); } catch { response.writeHead(404); response.end(); }
});
await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
const base = `http://127.0.0.1:${server.address().port}/preview.html`;
const browser = await chromium.launch({ channel: 'msedge', headless: true });
const page = await browser.newPage({ viewport: { width: 1100, height: 740 } });
const errors = []; page.on('pageerror', error => errors.push(error.message));
await mkdir('docs/ui-preview', { recursive: true });
try {
  for (const state of ['idle', 'executing', 'completed', 'failed', 'awaiting_approval', 'streaming']) {
    await page.goto(`${base}?state=${state}`); await page.locator('.zen-overlay').waitFor();
    assert.equal(Math.round((await page.locator('main').boundingBox()).height),48);
    assert.equal(await page.getByRole('button', { name: 'Configuración', exact: true }).count(),0);
    await page.getByRole('button', { name: 'Desplegar panel' }).click();
    await page.screenshot({ path: `docs/ui-preview/${state}.png`, animations: 'disabled' });
    const box = await page.locator('.zen-overlay').boundingBox(); assert(box.width <= 600); assert(box.height <= 592); assert.equal(Math.round(box.y), 0);
    assert.equal(await page.getByRole('textbox', { name: 'Petición a Zen' }).count(), 1);
    if (state === 'awaiting_approval') { await page.getByRole('button', { name: 'Permitir simulación' }).click(); assert.equal(await page.getByRole('button', { name: 'Permitir simulación' }).isDisabled(), true); assert.match(await page.locator('.approval-card').innerText(), /Ninguna acción ejecutada/); }
  }
  await page.goto(`${base}?state=idle`);
  assert.equal(Math.round((await page.locator('main').boundingBox()).height), 48);
  assert.equal((await page.locator('main').boundingBox()).width, 320);
  assert.equal(await page.getByRole('textbox', { name: 'Petición a Zen' }).count(), 0);
  await page.screenshot({ path: 'docs/ui-preview/topbar.png', animations: 'disabled' });
  await page.getByRole('button', { name: 'Desplegar panel' }).click();
  assert.equal(Math.round((await page.locator('main').boundingBox()).y), 0);
  await page.getByRole('button', { name: 'Contexto', exact: true }).click();
  await page.getByRole('heading', { name: 'Contexto de tu petición' }).waitFor();
  await page.getByRole('button', { name: 'Actividad', exact: true }).click();
  await page.getByRole('button', { name: 'Investigar', exact: false }).click();
  assert.equal(await page.getByRole('textbox', { name: 'Petición a Zen' }).inputValue(), 'Busca información sobre ');
  const input = page.getByRole('textbox', { name: 'Petición a Zen' });
  await input.fill('Primera línea'); await input.press('Shift+Enter'); await input.type('Segunda línea'); assert.match(await input.inputValue(), /Primera línea\nSegunda línea/);
  await input.press('Enter'); await page.getByRole('heading', { name: 'Listo', exact: true }).waitFor();
  await page.getByRole('button', { name: 'Historial', exact: true }).click(); assert.match(await page.locator('.messages').innerText(), /Primera línea/);
  await page.evaluate(() => { window.demoStopCalls = 0; const old = window.zen.stop; window.zen.stop = async () => { window.demoStopCalls++; return old(); }; });
  await page.keyboard.press('Escape'); await page.locator('[data-demo-hidden="true"]').waitFor(); assert.equal(await page.evaluate(() => window.demoStopCalls), 0);
  assert.match(await page.locator('.messages').innerText(), /Primera línea/);
  await page.goto(`${base}?view=preferences`); await page.getByRole('heading', { name: 'A tu manera' }).waitFor(); await page.screenshot({ path: 'docs/ui-preview/settings.png', animations: 'disabled' });
  await page.getByText('Tu perfil y memoria', { exact: true }).click();
  await page.getByLabel('Resumen aportado por ti').fill('Aprender diseño');
  await page.getByRole('button', { name: 'Revisar importación' }).click();
  await page.getByRole('button', { name: 'Guardar importación' }).click();
  await page.getByRole('textbox', { name: 'Editar Objetivos' }).waitFor();
  await page.getByRole('textbox', { name: 'Editar Objetivos' }).fill('Aprender diseño y colaborar');
  await page.getByRole('button', { name: 'Guardar corrección' }).click();
  assert.equal(await page.getByRole('textbox', { name: 'Editar Objetivos' }).inputValue(), 'Aprender diseño y colaborar');
  const downloadPromise = page.waitForEvent('download'); await page.getByRole('button', { name: 'Exportar perfil' }).click();
  const download = await downloadPromise; const exported = JSON.parse(await readFile(await download.path(), 'utf8')); assert.equal(exported[0].content, 'Aprender diseño y colaborar');
  await page.getByRole('button', { name: 'Borrar perfil completo' }).click(); assert.equal(await page.getByRole('textbox', { name: 'Editar Objetivos' }).count(), 0);
  await page.emulateMedia({ reducedMotion: 'reduce' }); await page.goto(`${base}?state=idle`); assert.equal(await page.locator('main').evaluate(element => getComputedStyle(element).animationName), 'none');
  await page.setViewportSize({ width: 320, height: 600 }); await page.goto(`${base}?state=failed`); await page.getByRole('button',{name:'Desplegar panel'}).click(); const box = await page.locator('main').boundingBox(); assert(box.width <= 320); await page.screenshot({ path: 'docs/ui-preview/small-screen.png', animations: 'disabled' });
  await page.setViewportSize({width:1100,height:740});
  await page.goto(`${base}?state=long-result`); await page.getByRole('button',{name:'Desplegar panel'}).click();
  const compactResultHeight=(await page.locator('main').boundingBox()).height;
  await page.getByRole('button',{name:'Leer resultado completo'}).click();
  assert((await page.locator('main').boundingBox()).height > compactResultHeight);
  assert.equal(await page.locator('.result-text').evaluate(el=>getComputedStyle(el).webkitLineClamp),'none');
  assert.match(await page.locator('.result-text').innerText(),/FINAL DEL RESULTADO/);
  await page.getByRole('button',{name:'Recoger resultado'}).click();
  await page.goto(`${base}?state=streaming&tasks=2`); await page.getByRole('button',{name:'Desplegar panel'}).click();
  await page.locator('.stream-label').waitFor();
  await page.getByRole('button',{name:'Otra petición',exact:true}).click();
  await page.evaluate(()=>window.dispatchEvent(new CustomEvent('zen-demo-task',{detail:{id:'simulation',state:'thinking',request:'Investiga cómo preparar la reunión',message:'Actividad en directo',streamText:'Nueva actividad pública en directo.'}})));
  assert.match(await page.locator('.result-text').innerText(),/segunda tarea/);
  await page.getByRole('button',{name:'Investiga cómo preparar la reunión',exact:true}).click();
  assert.match(await page.locator('.result-text').innerText(),/Nueva actividad pública/);
  await page.screenshot({path:'docs/ui-preview/island-streaming.png',animations:'disabled'});
  await page.getByRole('button',{name:'Recoger panel'}).click();
  assert.equal(Math.round((await page.locator('main').boundingBox()).height),48);
  await page.getByRole('button',{name:'Desplegar panel'}).click();
  assert.match(await page.locator('.result-text').innerText(),/Nueva actividad pública/);
  assert.equal(await page.getByRole('button',{name:'Configuración',exact:true}).count(),0);
  await page.evaluate(()=>window.dispatchEvent(new CustomEvent('zen-demo-task',{detail:{id:'simulation',state:'thinking',message:'Actividad en directo',streamText:'Texto en directo. '.repeat(100)}})));
  await page.waitForFunction(()=>{const el=document.querySelector('.workspace-body'); return el.scrollHeight-el.scrollTop-el.clientHeight<2;});
  await page.locator('.workspace-body').evaluate(el=>{el.scrollTop=0;el.dispatchEvent(new Event('scroll'));});
  await page.evaluate(()=>window.dispatchEvent(new CustomEvent('zen-demo-task',{detail:{id:'simulation',state:'thinking',message:'Actividad en directo',streamText:'Texto en directo. '.repeat(120)}})));
  assert.equal(await page.locator('.workspace-body').evaluate(el=>el.scrollTop),0);
  await page.getByRole('button',{name:'Recoger panel'}).click();
  await page.getByRole('button',{name:'Detener todas las tareas'}).click();
  assert.equal(await page.getByRole('button',{name:'Detener todas las tareas'}).count(),0);
  assert.deepEqual(errors, []);
  const report = { at: new Date().toISOString(), browser: 'Edge headless', passed: true, checks: ['top edge in every view', 'collapse and expand without losing context', 'execution island excludes configuration', 'context and tasks navigation', 'preferences in separate view', 'public streaming and task selection preserved', 'stream follows updates and respects manual scroll', 'stop available while compact', 'full result available on demand', 'suggestions fill input without executing', 'representative states', 'approval demo single use, no execution', 'Enter submits', 'Shift+Enter newline', 'Escape hides without Stop', 'history retained on hide', 'settings scroll panel', 'profile import editable preview, correction, export and deletion', 'reduced motion', 'small viewport', 'no page errors'], screenshots: 'docs/ui-preview' };
  await mkdir('test-results', { recursive: true }); await writeFile('test-results/ui.json', JSON.stringify(report, null, 2)); console.log(JSON.stringify(report, null, 2));
} finally { await browser.close(); await new Promise(resolve => server.close(resolve)); }
