import {DatabaseSync} from 'node:sqlite';
import {mkdirSync,existsSync,copyFileSync} from 'node:fs';
import {join} from 'node:path';
import {randomUUID} from 'node:crypto';
import {ZenError} from '../shared/errors';
import {emptyChatDraft,type ChatDraft,type ChatRow,type ChatMessage,type ChatRunState,type ChatTransfer,type ChatCheckpoint} from '../shared/conversations';
import type {Artifact,TaskEvent,TaskResult,Utterance} from '../shared/contracts';
import type {StoredDrop} from '../main/drop-context';

type Row=Record<string,any>;
export class ConversationStore {
 readonly db:DatabaseSync;
 constructor(directory:string){
  mkdirSync(directory,{recursive:true});this.db=new DatabaseSync(join(directory,'conversations.sqlite'));
  this.db.exec(`PRAGMA journal_mode=WAL;PRAGMA foreign_keys=ON;PRAGMA busy_timeout=5000;
   CREATE TABLE IF NOT EXISTS chats(id TEXT PRIMARY KEY,project TEXT,title TEXT NOT NULL,created INTEGER,updated INTEGER,pinned INTEGER DEFAULT 0,archived INTEGER DEFAULT 0,partial INTEGER DEFAULT 0,version INTEGER DEFAULT 0,reconstructed INTEGER DEFAULT 0,draft TEXT NOT NULL,checkpoint TEXT);
   CREATE TABLE IF NOT EXISTS messages(id TEXT PRIMARY KEY,chat TEXT NOT NULL REFERENCES chats(id) ON DELETE CASCADE,seq INTEGER NOT NULL,role TEXT NOT NULL,text TEXT NOT NULL,state TEXT NOT NULL,created INTEGER,run TEXT,partial INTEGER DEFAULT 0,event TEXT,UNIQUE(chat,seq));
   CREATE TABLE IF NOT EXISTS legacy_tasks(chat TEXT NOT NULL REFERENCES chats(id) ON DELETE CASCADE,task TEXT NOT NULL,PRIMARY KEY(chat,task));
   CREATE TABLE IF NOT EXISTS captions(key TEXT PRIMARY KEY,chat TEXT NOT NULL REFERENCES chats(id) ON DELETE CASCADE,message TEXT NOT NULL REFERENCES messages(id) ON DELETE CASCADE);
   CREATE TABLE IF NOT EXISTS runs(id TEXT PRIMARY KEY,chat TEXT NOT NULL REFERENCES chats(id) ON DELETE CASCADE,task TEXT,state TEXT NOT NULL,response TEXT,error TEXT,created INTEGER,updated INTEGER);
   CREATE INDEX IF NOT EXISTS run_task ON runs(task);
   CREATE TABLE IF NOT EXISTS provider(chat TEXT PRIMARY KEY REFERENCES chats(id) ON DELETE CASCADE,seq INTEGER NOT NULL,items TEXT NOT NULL,version INTEGER DEFAULT 0);
   CREATE TABLE IF NOT EXISTS responses(id TEXT PRIMARY KEY,chat TEXT NOT NULL,run TEXT,kind TEXT NOT NULL DEFAULT 'response');
   CREATE TABLE IF NOT EXISTS tools(run TEXT,call TEXT,state TEXT,result TEXT,PRIMARY KEY(run,call));
   CREATE TABLE IF NOT EXISTS attachments(id TEXT,chat TEXT NOT NULL REFERENCES chats(id) ON DELETE CASCADE,data TEXT NOT NULL,PRIMARY KEY(chat,id));
   CREATE TABLE IF NOT EXISTS chat_artifacts(id TEXT,chat TEXT NOT NULL REFERENCES chats(id) ON DELETE CASCADE,meta TEXT,data BLOB,mime TEXT,PRIMARY KEY(chat,id));
   CREATE TABLE IF NOT EXISTS transfers(id TEXT PRIMARY KEY,target TEXT NOT NULL REFERENCES chats(id) ON DELETE CASCADE,source TEXT,title TEXT,project TEXT,version INTEGER,text TEXT,created INTEGER,active INTEGER DEFAULT 1);
   CREATE TABLE IF NOT EXISTS local_state(key TEXT PRIMARY KEY,value TEXT);
   CREATE TABLE IF NOT EXISTS tombstones(id TEXT PRIMARY KEY,created INTEGER);
   CREATE TABLE IF NOT EXISTS tombstone_runs(id TEXT PRIMARY KEY,task TEXT);
   CREATE TABLE IF NOT EXISTS cleanup(response TEXT PRIMARY KEY,chat TEXT NOT NULL,error TEXT);
   CREATE INDEX IF NOT EXISTS chats_project ON chats(project,archived,pinned,updated);
   CREATE INDEX IF NOT EXISTS messages_chat ON messages(chat,seq);`);
  const prior=join(directory,'tasks.json');if(existsSync(prior)&&!existsSync(prior+'.before-conversations.bak'))copyFileSync(prior,prior+'.before-conversations.bak');
 }
 caption(chat:string,key:string,utterance:Utterance){this.transaction(()=>{this.require(chat);const prior=this.get('SELECT message FROM captions WHERE key=? AND chat=?',key,chat);const id=prior?.message??this.insert(chat,utterance.speaker==='user'?'user':'assistant',utterance.text,'incomplete',null,true);if(!prior)this.exec('INSERT INTO captions(key,chat,message) VALUES(?,?,?)',key,chat,id);this.exec('UPDATE messages SET text=?,event=? WHERE id=?',utterance.text,JSON.stringify({id:'voice',state:'listening',message:'',localOnly:true,utterance}),id);this.exec('UPDATE chats SET updated=?,version=version+1 WHERE id=?',Date.now(),chat);});}
 messageById(chat:string,id:string){this.require(chat);const row=this.get('SELECT * FROM messages WHERE chat=? AND id=?',chat,id);if(!row)throw new ZenError('Mensaje no disponible.');return this.message(row);}
 putArtifact(chat:string,item:{meta:Artifact;data:Buffer;mime:string}){this.require(chat);this.exec('INSERT OR REPLACE INTO chat_artifacts(id,chat,meta,data,mime) VALUES(?,?,?,?,?)',item.meta.id,chat,JSON.stringify(item.meta),item.data,item.mime);}
 artifact(id:string){const row=this.get('SELECT * FROM chat_artifacts WHERE id=? LIMIT 1',id);return row?{meta:JSON.parse(row.meta) as Artifact,data:Buffer.from(row.data),mime:row.mime as string,at:Date.now()}:undefined;}
 close(){this.db.close();}
 private get(sql:string,...values:any[]){return this.db.prepare(sql).get(...values) as Row|undefined;}
 private all(sql:string,...values:any[]){return this.db.prepare(sql).all(...values) as Row[];}
 private exec(sql:string,...values:any[]){return this.db.prepare(sql).run(...values);}
 transaction<T>(fn:()=>T):T{this.db.exec('BEGIN IMMEDIATE');try{const v=fn();this.db.exec('COMMIT');return v;}catch(e){this.db.exec('ROLLBACK');throw e;}}
 require(id:string){const row=this.get('SELECT * FROM chats WHERE id=?',id);if(!row)throw new ZenError('Conversación no disponible.');return row;}
 private row(r:Row):ChatRow {const latest=this.get('SELECT text,state FROM messages WHERE chat=? ORDER BY seq DESC LIMIT 1',r.id);return{id:r.id,projectId:r.project,title:r.title,createdAt:r.created,updatedAt:r.updated,pinned:!!r.pinned,archived:!!r.archived,partial:!!r.partial,version:r.version,reconstructed:!!r.reconstructed,preview:(latest?.text??'').slice(0,140),state:latest?.state};}
 chat(id:string){return this.row(this.require(id));}
 create(project:string|null,title='Nuevo chat'){const id=randomUUID(),now=Date.now();this.exec('INSERT INTO chats(id,project,title,created,updated,draft) VALUES(?,?,?,?,?,?)',id,project,title,now,now,JSON.stringify(emptyChatDraft()));return this.chat(id);}
 active(project:string|null){const key='active:'+ (project??'general'),id=this.get('SELECT value FROM local_state WHERE key=?',key)?.value;const existing=id&&this.get('SELECT * FROM chats WHERE id=? AND project IS ? AND archived=0',id,project);if(existing)return this.row(existing);const chat=this.list(project,'recent','',0)[0]??this.create(project);this.setActive(chat.id);return chat;}
 setActive(id:string){const row=this.require(id);this.exec('INSERT OR REPLACE INTO local_state(key,value) VALUES(?,?)','active:'+(row.project??'general'),id);}
 list(project:string|null,filter='recent',query='',offset=0){const escaped='%'+query.replace(/[\\%_]/g,'\\$&')+'%';return this.all(`SELECT c.* FROM chats c WHERE project IS ? AND archived=? ${filter==='pinned'?'AND pinned=1':''} AND (title LIKE ? ESCAPE '\\' OR EXISTS(SELECT 1 FROM messages m WHERE m.chat=c.id AND m.text LIKE ? ESCAPE '\\')) ORDER BY pinned DESC,updated DESC,id LIMIT 40 OFFSET ?`,project,filter==='archived'?1:0,escaped,escaped,offset).map(r=>this.row(r));}
 update(id:string,patch:{title?:string;pinned?:boolean;archived?:boolean}){this.require(id);for(const field of ['title','pinned','archived'] as const)if(patch[field]!==undefined)this.exec(`UPDATE chats SET ${field}=?,version=version+1 WHERE id=?`,field==='title'?patch[field]:Number(patch[field]),id);return this.chat(id);}
 draft(id:string):ChatDraft{return JSON.parse(this.require(id).draft);}
 saveDraft(id:string,draft:ChatDraft){this.require(id);this.exec('UPDATE chats SET draft=? WHERE id=?',JSON.stringify(draft),id);}
 private message(r:Row):ChatMessage{return{id:r.id,seq:r.seq,role:r.role,text:r.text,state:r.state,createdAt:r.created,runId:r.run??undefined,partial:!!r.partial,event:r.event?JSON.parse(r.event):undefined};}
 messages(id:string,before=Number.MAX_SAFE_INTEGER,limit=60){this.require(id);return this.all('SELECT * FROM messages WHERE chat=? AND seq<? ORDER BY seq DESC LIMIT ?',id,before,limit).reverse().map(r=>this.message(r));}
 search(id:string,query:string){this.require(id);return this.all("SELECT * FROM messages WHERE chat=? AND text LIKE ? ESCAPE '\\' ORDER BY seq LIMIT 30",id,'%'+query.replace(/[\\%_]/g,'\\$&')+'%').map(r=>this.message(r));}
 private insert(id:string,role:string,text:string,state:ChatRunState,run:string|null=null,partial=false){const seq=(this.get('SELECT MAX(seq) n FROM messages WHERE chat=?',id)?.n??0)+1,mid=randomUUID();this.exec('INSERT INTO messages(id,chat,seq,role,text,state,created,run,partial) VALUES(?,?,?,?,?,?,?,?,?)',mid,id,seq,role,text,state,Date.now(),run,Number(partial));return mid;}
 run(id:string){return this.get('SELECT * FROM runs WHERE id=?',id);}
 begin(chatId:string,requestId:string,text:string){return this.transaction(()=>{const chat=this.require(chatId),existing=this.run(requestId);if(existing){if(existing.chat!==chatId)throw new ZenError('La petición pertenece a otra conversación.');return false;}if(chat.archived)throw new ZenError('Recupera esta conversación antes de enviar.');const now=Date.now();this.exec('INSERT INTO runs(id,chat,state,created,updated) VALUES(?,?,?,?,?)',requestId,chatId,'pending',now,now);this.insert(chatId,'user',text,'completed',requestId);this.insert(chatId,'assistant','','pending',requestId);if(chat.title==='Nuevo chat')this.exec('UPDATE chats SET title=? WHERE id=?',text.replace(/\s+/g,' ').slice(0,70),chatId);this.exec('UPDATE chats SET updated=?,version=version+1 WHERE id=?',now,chatId);return true;});}
 runSeq(id:string){return this.get("SELECT seq FROM messages WHERE run=? AND role='assistant'",id)?.seq??0;}
 owner(event:TaskEvent){return this.get('SELECT * FROM runs WHERE id=? OR task=?',event.requestId??event.id,event.id);}
 accept(event:TaskEvent):TaskEvent {
  const run=this.owner(event);if(!run)return event;
  const state:ChatRunState=event.workContext?.phase==='external'?'external':event.state==='queued'?'pending':['thinking','executing','awaiting_approval'].includes(event.state)?'running':event.state==='awaiting_input'?'incomplete':event.state==='completed'?'completed':event.state==='cancelled'?(run.response?'cancel_requested':'cancelled'):'failed';
  this.transaction(()=>{this.exec('UPDATE runs SET task=?,state=?,updated=? WHERE id=?',event.id,state,Date.now(),run.id);const clean={...event,streamText:undefined,approval:undefined,usage:undefined};if(event.streamText!==undefined)this.exec("UPDATE messages SET text=text||?,state=? WHERE run=? AND role='assistant'",event.streamText,state,run.id);else if(['pending','running'].includes(state))this.exec("UPDATE messages SET state=?,event=? WHERE run=? AND role='assistant'",state,JSON.stringify(clean),run.id);else this.exec("UPDATE messages SET text=CASE WHEN ? IN ('failed','cancelled','cancel_requested','incomplete') AND text!='' THEN text||char(10)||char(10)||? ELSE ? END,state=?,event=?,partial=? WHERE run=? AND role='assistant'",state,event.message,event.message,state,JSON.stringify(clean),Number(['failed','cancelled','cancel_requested','incomplete'].includes(state)),run.id);this.exec('UPDATE chats SET updated=?,version=version+1 WHERE id=?',Date.now(),run.chat);});
  if(['completed','failed','cancelled','cancel_requested','external','incomplete'].includes(state))this.checkpoint(run.chat);
  return {...event,chatId:run.chat};
 }
 finish(requestId:string,result:TaskResult){const run=this.run(requestId);if(run)this.accept({...result,requestId,chatId:run.chat});}
 result(requestId:string):TaskResult{const run=this.run(requestId);if(!run)throw new ZenError('Petición no disponible.');const message=this.get("SELECT text FROM messages WHERE run=? AND role='assistant'",requestId)?.text??'';return{id:run.task??requestId,state:run.state==='completed'?'completed':run.state==='cancelled'?'cancelled':'awaiting_input',message:message||'Estado por comprobar. No se reenvía la petición automáticamente.',localOnly:true};}
 recover(){this.exec("UPDATE runs SET state='interrupted',error='Estado por comprobar' WHERE state IN ('pending','running','cancel_requested')");this.exec("UPDATE messages SET state='interrupted',partial=1 WHERE run IN (SELECT id FROM runs WHERE state='interrupted') AND role='assistant'");}
 checkpoint(id:string):ChatCheckpoint{const rows=this.messages(id),first=this.get("SELECT id,text FROM messages WHERE chat=? AND role='user' ORDER BY seq LIMIT 1",id),last=[...rows].reverse().find(r=>r.role==='assistant'&&r.text&&!r.event?.utterance),pending=[...rows].reverse().find(r=>r.role==='assistant'&&r.state!=='completed'&&!r.event?.utterance),prior=this.checkpointValue(id);const value:ChatCheckpoint={version:(prior?.version??0)+1,throughSeq:rows.at(-1)?.seq??0,objective:first?.text.slice(0,2000)??'',lastResult:last?.text.slice(-4000)??'',pending:pending?`Registro sin confirmar: ${pending.state}. Revisar su estado antes de continuar.`:'',sourceIds:[first?.id,last?.id].filter(Boolean),updatedAt:Date.now()};this.exec('UPDATE chats SET checkpoint=? WHERE id=?',JSON.stringify(value),id);return value;}
 checkpointValue(id:string):ChatCheckpoint|null{const data=this.require(id).checkpoint;return data?JSON.parse(data):null;}
 putAttachment(chat:string,drop:StoredDrop){this.require(chat);this.exec('INSERT OR REPLACE INTO attachments(id,chat,data) VALUES(?,?,?)',drop.item.id,chat,JSON.stringify(drop));}
 attachmentReferences(chat:string,selected:string[]):StoredDrop[]{this.require(chat);return this.all("SELECT id,json_remove(data,'$.image','$.text','$.item.preview') AS data FROM attachments WHERE chat=?",chat).map(r=>{const row=JSON.parse(r.data) as StoredDrop;if(selected.includes(r.id)){const full=this.get('SELECT data FROM attachments WHERE chat=? AND id=?',chat,r.id);row.item=JSON.parse(full!.data).item;}return row;});}
 attachments(chat:string):StoredDrop[]{this.require(chat);return this.all('SELECT data FROM attachments WHERE chat=?',chat).map(r=>JSON.parse(r.data));}
 transfers(id:string):ChatTransfer[]{this.require(id);return this.all('SELECT * FROM transfers WHERE target=? ORDER BY created',id).map(r=>({id:r.id,sourceId:r.source,sourceTitle:r.title,sourceProject:r.project,sourceVersion:r.version,text:r.text,createdAt:r.created,active:!!r.active}));}
 transfer(source:string,target:string|null,project:string|null,version:number,text:string,attachmentIds:string[]){return this.transaction(()=>{const from=this.require(source);if(from.version!==version)throw new ZenError('El origen cambió; revisa una vista previa nueva.');const to=target?this.chat(target):this.create(project,'Continuación: '+from.title.slice(0,70));if(to.projectId!==project)throw new ZenError('Proyecto de destino diferente.');const all=this.attachments(source);for(const id of attachmentIds)if(!all.some(row=>row.item.id===id))throw new ZenError('Adjunto ajeno al origen.');this.exec('INSERT INTO transfers(id,target,source,title,project,version,text,created) VALUES(?,?,?,?,?,?,?,?)',randomUUID(),to.id,source,from.title,from.project,version,text,Date.now());for(const row of all.filter(row=>attachmentIds.includes(row.item.id)))this.putAttachment(to.id,{...row,item:{...row.item,id:randomUUID()}});this.insert(to.id,'context',text,'completed');this.exec('DELETE FROM provider WHERE chat=?',to.id);this.exec('UPDATE chats SET version=version+1,reconstructed=1 WHERE id=?',to.id);return to.id;});}
 detach(id:string,transfer:string){this.require(id);this.exec('UPDATE transfers SET active=0 WHERE target=? AND id=?',id,transfer);this.exec('DELETE FROM provider WHERE chat=?',id);this.exec('UPDATE chats SET reconstructed=1,version=version+1 WHERE id=?',id);}
 context(id:string,through=Number.MAX_SAFE_INTEGER){this.require(id);const saved=this.get('SELECT * FROM provider WHERE chat=?',id);const after=saved?.seq??0;const messages=this.all("SELECT * FROM messages WHERE chat=? AND seq>? AND seq<=? AND role!='context' AND text!='' ORDER BY seq",id,after,through).map(r=>this.message(r)).filter(m=>!m.event?.localOnly);return{items:saved?JSON.parse(saved.items) as any[]:[],seq:after,version:saved?.version??0,messages};}
 saveContext(id:string,seq:number,items:unknown[],compacted=false){this.require(id);this.exec('INSERT INTO provider(chat,seq,items,version) VALUES(?,?,?,?) ON CONFLICT(chat) DO UPDATE SET seq=excluded.seq,items=excluded.items,version=provider.version+?',id,seq,JSON.stringify(items),Number(compacted),Number(compacted));}
 reconstructed(id:string){this.require(id);this.exec('UPDATE chats SET reconstructed=1 WHERE id=?',id);}
 response(id:string,chat:string,run:string,kind='response'){if(this.get('SELECT id FROM tombstones WHERE id=?',chat)){if(kind==='response')this.exec('INSERT OR IGNORE INTO cleanup(response,chat) VALUES(?,?)',id,chat);return;}this.exec('INSERT OR IGNORE INTO responses(id,chat,run,kind) VALUES(?,?,?,?)',id,chat,run,kind);if(kind==='response')this.exec('UPDATE runs SET response=? WHERE id=?',id,run);}
 startTool(run:string,call:string){if(this.get('SELECT call FROM tools WHERE run=? AND call=?',run,call))throw new ZenError('Herramienta ya registrada. No se repite un efecto incierto.');this.exec('INSERT INTO tools(run,call,state) VALUES(?,?,?)',run,call,'running');}
 finishTool(run:string,call:string,result:unknown){this.exec('UPDATE tools SET state=?,result=? WHERE run=? AND call=?','completed',JSON.stringify(result),run,call);}
 pending(id:string){this.require(id);return this.all("SELECT * FROM runs WHERE chat=? AND state IN ('interrupted','incomplete','cancel_requested','failed','cancelled')",id);}
 activeRuns(id:string){this.require(id);return this.all("SELECT * FROM runs WHERE chat=? AND state IN ('pending','running','cancel_requested')",id);}
 taskIds(id:string){return [...new Set([...this.all('SELECT task FROM legacy_tasks WHERE chat=?',id),...this.all('SELECT COALESCE(task,id) AS task FROM runs WHERE chat=?',id)].map(r=>r.task as string))];}
 deleted(event:TaskEvent){return !!(event.chatId&&this.get('SELECT id FROM tombstones WHERE id=?',event.chatId)||this.get('SELECT id FROM tombstone_runs WHERE id=? OR task=?',event.requestId??event.id,event.id));}
 delete(id:string){this.transaction(()=>{this.require(id);this.exec('INSERT OR IGNORE INTO tombstones(id,created) VALUES(?,?)',id,Date.now());this.exec("INSERT OR IGNORE INTO cleanup(response,chat) SELECT id,chat FROM responses WHERE chat=? AND kind='response'",id);this.exec('INSERT OR IGNORE INTO tombstone_runs(id,task) SELECT id,task FROM runs WHERE chat=?',id);this.exec('DELETE FROM tools WHERE run IN (SELECT id FROM runs WHERE chat=?)',id);this.exec('DELETE FROM responses WHERE chat=?',id);this.exec('DELETE FROM chats WHERE id=?',id);});}
 cleanup(){return this.all('SELECT * FROM cleanup');}
 cleaned(id:string,error?:string){if(error)this.exec('UPDATE cleanup SET error=? WHERE response=?',error,id);else this.exec('DELETE FROM cleanup WHERE response=?',id);}
 migrate(tasks:TaskEvent[]){if(this.get("SELECT value FROM local_state WHERE key='migration-tasks-v1'"))return;this.transaction(()=>{for(const task of tasks){if(['voice','storage','control'].includes(task.id))continue;const chat=this.create(task.projectContextId??null,(task.request??'Tarea recuperada').slice(0,70));this.exec('UPDATE chats SET partial=1 WHERE id=?',chat.id);this.exec('INSERT INTO legacy_tasks(chat,task) VALUES(?,?)',chat.id,task.id);if(task.request)this.insert(chat.id,'user',task.request,'completed',null,true);this.insert(chat.id,'assistant',task.message,task.workContext?.phase==='external'?'external':task.state==='completed'?'completed':'interrupted',null,true);this.checkpoint(chat.id);this.exec('UPDATE chats SET created=?,updated=? WHERE id=?',task.createdAt??task.updatedAt??Date.now(),task.updatedAt??Date.now(),chat.id);}this.exec("INSERT INTO local_state(key,value) VALUES('migration-tasks-v1','done')");});}
}
