import React,{useState} from 'react';
import type {ContextAttachment} from '../shared/drop-context';
import type {VisualReference} from '../shared/interactions';
export type SentContext={requestId:string;names:string[];at:number;state:'sending'|'sent'|'failed';image?:string};
export function ContextTray({items,remove,edit,preparing,cancel,error,clearError,image,visual,removeImage,sent}:{items:ContextAttachment[];remove:(id:string)=>void;edit:(id:string,text:string)=>Promise<void>;preparing:boolean;cancel:()=>void;error:string;clearError:()=>void;image?:string;visual?:VisualReference;removeImage:()=>void;sent?:SentContext}){
  const [editing,setEditing]=useState<string>(),[text,setText]=useState(''),[saving,setSaving]=useState(false),[editError,setEditError]=useState('');
  if(!items.length&&!image&&!preparing&&!error&&!sent)return null;
  return <section className="context-tray" aria-label="Contexto de la petición"><div className="context-heading"><strong>Contexto</strong><small>Local hasta enviar</small></div>
    {preparing&&<p role="status">Preparando en este equipo… <button onClick={cancel}>Cancelar preparación</button></p>}
    {error&&<p className="context-error" role="alert">{error}<button onClick={clearError}>Cerrar aviso</button></p>}
    {image&&<div className="context-row"><details><summary><img src={image} alt="Zona elegida para enviar"/><span>{visual?.source??'Imagen preparada'}<small>{visual?`${new Date(visual.capturedAt).toLocaleTimeString()} · ${visual.width} × ${visual.height}${visual.crop?' · recorte':''}`:'Solo esta imagen'} · preparada localmente</small></span></summary><img className="context-preview" src={image} alt="Vista previa exacta de la imagen que se enviará"/></details><button aria-label="Quitar imagen preparada" onClick={removeImage}>×</button></div>}
    {items.map(item=><div className="context-row" key={item.id}><div><strong>{item.name}</strong><small>{item.kind==='file'?'Archivo compatible':item.kind==='window'?'Captura de ventana':item.kind==='image'?'Imagen':item.kind==='link'?'Enlace':'Texto'} · preparado localmente</small><small>{item.detail}</small>{item.preview&&<details><summary>Ver referencia</summary>{item.preview.startsWith('data:image/')?<img className="context-preview" src={item.preview} alt={item.name}/>:<pre>{item.preview}</pre>}</details>}{['text','link'].includes(item.kind)&&<button onClick={()=>{setEditing(item.id);setText(item.preview??'');setEditError('');}}>Editar texto</button>}{editing===item.id&&<div className="context-edit"><textarea aria-label="Texto del contexto" maxLength={64000} value={text} onChange={e=>setText(e.target.value)}/>{editError&&<p role="alert">{editError}</p>}<button disabled={saving||!text.trim()} onClick={()=>{setSaving(true);void edit(item.id,text).then(()=>setEditing(undefined)).catch(e=>setEditError(e.message)).finally(()=>setSaving(false));}}>Guardar texto</button><button disabled={saving} onClick={()=>setEditing(undefined)}>Cancelar</button></div>}</div><button aria-label={`Quitar adjunto ${item.name}`} onClick={()=>remove(item.id)}>×</button></div>)}
    {sent&&<details className="sent-context"><summary>{sent.state==='sending'?'Petición iniciada':sent.state==='failed'?'Petición fallida':'Contexto de la petición enviada'} · {new Date(sent.at).toLocaleTimeString()}</summary><p>{sent.names.join(' · ')||'Sin adjuntos'}</p>{sent.image&&<img className="context-preview" src={sent.image} alt="Imagen incluida en la petición enviada"/>}<small>Selección fijada al enviar. Quitar elementos del borrador no retira datos ya compartidos.</small></details>}
  </section>;
}
