import React,{useEffect,useRef,useState} from 'react';
import {chatStateLabel,type ChatMessage,type ChatRow,type ChatSnapshot,type ConversationCommand,type ConversationReply} from '../shared/conversations';
import type {ProjectContexts} from '../shared/project-context';
import {MessageText} from './message-text';
import './conversations.css';

export function Conversations({snapshot,revision,loading,projects,call,open,refresh,notify,restore,scroll}:{snapshot?:ChatSnapshot;revision:number;loading:boolean;projects:ProjectContexts;call:(c:ConversationCommand)=>Promise<ConversationReply>;open:(c:ConversationCommand)=>Promise<void>;refresh:()=>Promise<void>;notify:(s:string)=>void;restore:(s:ChatSnapshot)=>void;scroll:React.RefObject<HTMLDivElement|null>}){
 const [list,setList]=useState(false),[rows,setRows]=useState<ChatRow[]>([]),[query,setQuery]=useState(''),[filter,setFilter]=useState<'recent'|'pinned'|'archived'>('recent'),[offset,setOffset]=useState(0),[more,setMore]=useState(false);
 const [search,setSearch]=useState(''),[found,setFound]=useState<ChatMessage[]|null>(null),[older,setOlder]=useState<ChatMessage[]>([]),[olderDone,setOlderDone]=useState(false),[rename,setRename]=useState<string|null>(null),[code,setCode]=useState(''),[typedCode,setTypedCode]=useState('');
 const [transfer,setTransfer]=useState<{source:ChatSnapshot;target:string|null;project:string|null;text:string;ids:string[]}|null>(null),[sources,setSources]=useState<ChatRow[]|null>(null),[sourceProject,setSourceProject]=useState<string|null>(projects.activeId);
 const [transferNew,setTransferNew]=useState(true),[destinations,setDestinations]=useState<ChatRow[]>([]);
 const chat=snapshot?.chat;
 const safe=(fn:()=>Promise<unknown>)=>void fn().catch(e=>notify(e.message));
 useEffect(()=>{let cancelled=false;const timer=setTimeout(()=>safe(async()=>{const r=await call({action:'list',projectId:projects.activeId,filter,query,offset});if(!cancelled){setRows(r.rows??[]);setMore((r.rows?.length??0)===40);setCleanup(r.pendingCleanup??0);}}),180);return()=>{cancelled=true;clearTimeout(timer);};},[projects.activeId,filter,query,offset,revision]);
 useEffect(()=>{setOlder([]);setOlderDone(false);setFound(null);setSearch('');setRename(null);setCode('');setTypedCode('');setTransfer(null);setSources(null);setList(false);},[chat?.id]);
 const [cleanup,setCleanup]=useState(0);
 const following=useRef(false),[away,setAway]=useState(false);
 useEffect(()=>{const el=scroll.current;if(!el)return;el.scrollTop=snapshot?.draft.scrollTop??0;following.current=el.scrollHeight-el.clientHeight-el.scrollTop<60;setAway(!following.current);const update=()=>{following.current=el.scrollHeight-el.clientHeight-el.scrollTop<60;setAway(!following.current);};el.addEventListener('scroll',update);return()=>el.removeEventListener('scroll',update);},[chat?.id,list]);
 useEffect(()=>{if(!list&&following.current&&scroll.current)scroll.current.scrollTop=scroll.current.scrollHeight;},[snapshot?.messages,list]);
 const choose=(id:string)=>safe(async()=>{await open({action:'open',id});setList(false);});
 const edit=async(patch:{title?:string;pinned?:boolean;archived?:boolean})=>{if(!chat)return;await call({action:'update',id:chat.id,...patch});await refresh();};
 const preview=(s:ChatSnapshot,target:string|null,project:string|null)=>{const c=s.checkpoint;setTransferNew(!target);setTransfer({source:s,target,project,text:c?`Objetivo: ${c.objective}\nÚltimo resultado: ${c.lastResult}\nPendiente: ${c.pending}`:s.messages.slice(-6).map(m=>`${m.role==='user'?'Tú':'ZEN'}: ${m.text}`).join('\n\n'),ids:[]});setSources(null);};
 useEffect(()=>{if(!transfer||!transferNew)return;safe(async()=>{const r=await call({action:'list',projectId:transfer.project,filter:'recent',query:'',offset:0});setDestinations(r.rows??[]);});},[transfer?.project,transferNew]);
 const showSources=()=>safe(async()=>{const r=await call({action:'list',projectId:sourceProject,filter:'recent',query:'',offset:0});setSources(r.rows??[]);});
 const history=found??[...older,...snapshot?.messages??[]].filter((m,i,a)=>a.findIndex(n=>n.id===m.id)===i);
 return <section className="conversations" aria-label="Chats guardados">
  <nav className="chat-navigation" aria-label="Conversaciones"><button aria-pressed={list} onClick={()=>setList(v=>!v)}>☰ Conversaciones</button><button disabled={loading} onClick={()=>safe(()=>open({action:'create',projectId:projects.activeId}))}>＋ Nuevo chat</button></nav>
  {cleanup>0&&<p className="chat-notice">Limpieza remota pendiente ({cleanup}). <button onClick={()=>safe(async()=>{const r=await call({action:'cleanup'});setCleanup(r.pendingCleanup??0);})}>Reintentar limpieza</button></p>}
  {loading&&<p role="status">Abriendo conversación…</p>}
  {list?<div className="conversation-list"><label>Buscar conversaciones<input placeholder="Título o contenido" value={query} onChange={e=>{setQuery(e.target.value);setOffset(0);}}/></label><div className="chat-filters">{(['recent','pinned','archived'] as const).map((f,i)=><button key={f} aria-pressed={filter===f} onClick={()=>{setFilter(f);setOffset(0);}}>{['Recientes','Fijadas','Archivadas'][i]}</button>)}</div>{rows.map(row=><button className="chat-row" key={row.id} aria-current={row.id===chat?.id?'page':undefined} onClick={()=>choose(row.id)}><strong>{row.pinned?'★ ':''}{row.title}</strong><span>{row.preview||'Sin mensajes'}</span><small>{row.state?chatStateLabel[row.state]:'Preparada'}{row.partial?' · Historial parcial':''} · {new Date(row.updatedAt).toLocaleDateString()}</small></button>)}{!rows.length&&<p>No hay conversaciones en esta lista.</p>}<div className="chat-filters"><button disabled={!offset} onClick={()=>setOffset(v=>Math.max(0,v-40))}>Anteriores</button><button disabled={!more} onClick={()=>setOffset(v=>v+40)}>Más conversaciones</button></div></div>:chat&&<>
   <div className="chat-heading"><h2>{chat.title}</h2><small>{chat.state?chatStateLabel[chat.state]:'Lista para conversar'}</small></div>
   {(chat.partial||chat.reconstructed)&&<p className="chat-notice">{chat.partial?'Historial anterior parcial: solo se recuperó lo que ZEN tenía guardado.':'Contexto reconstruido desde los registros locales.'}</p>}
   {chat.archived&&<p className="chat-notice">Conversación archivada. Recupera antes de enviar.</p>}
   <details className="chat-options"><summary>Opciones del chat</summary><div className="chat-filters"><button onClick={()=>setRename(chat.title)}>Renombrar</button><button onClick={()=>safe(()=>edit({pinned:!chat.pinned}))}>{chat.pinned?'Desfijar':'Fijar'}</button><button onClick={()=>safe(()=>edit({archived:!chat.archived}))}>{chat.archived?'Recuperar':'Archivar'}</button><button onClick={()=>preview(snapshot!,null,projects.activeId)}>Continuar en un chat nuevo</button><button onClick={showSources}>Usar contexto de otro chat</button><button onClick={()=>safe(async()=>{await call({action:'reconcile',id:chat.id});await refresh();})}>Comprobar resultado pendiente</button><button className="danger" onClick={()=>safe(async()=>{const r=await call({action:'delete-preview',id:chat.id});setCode(r.code??'');})}>Eliminar chat</button></div>
   {rename!==null&&<form onSubmit={e=>{e.preventDefault();safe(async()=>{await edit({title:rename});setRename(null);});}}><label>Nombre<input maxLength={100} value={rename} onChange={e=>setRename(e.target.value)}/></label><button disabled={!rename.trim()}>Guardar nombre</button></form>}
   {code&&<div className="chat-notice"><p>Eliminará historial, copias locales y respuestas remotas propias de «{chat.title}». Se detienen sus tareas. Los archivos originales y otros chats se conservan.</p><p>Di o escribe «confirmo {code}», o introduce el código aquí.</p><form onSubmit={e=>{e.preventDefault();safe(async()=>{await call({action:'delete-confirm',id:chat.id,code:typedCode});setCode('');await open({action:'active',projectId:projects.activeId});});}}><label>Código de confirmación<input inputMode="numeric" maxLength={4} value={typedCode} onChange={e=>setTypedCode(e.target.value)}/></label><button disabled={typedCode!==code}>Confirmar eliminación</button></form></div>}
   <form onSubmit={e=>{e.preventDefault();safe(async()=>{const r=await call({action:'search',id:chat.id,query:search});setFound(r.messages??[]);});}}><label>Buscar en este chat<input value={search} onChange={e=>setSearch(e.target.value)} maxLength={200}/></label><button disabled={!search.trim()}>Buscar fragmentos</button>{found&&<button type="button" onClick={()=>setFound(null)}>Volver al historial</button>}</form></details>
   {snapshot?.checkpoint&&<details className="chat-checkpoint"><summary>Dónde lo dejamos</summary><strong>Objetivo</strong><p>{snapshot.checkpoint.objective}</p><strong>Último resultado</strong><p>{snapshot.checkpoint.lastResult}</p>{snapshot.checkpoint.pending&&<p>{snapshot.checkpoint.pending}</p>}<small>Registro local · versión {snapshot.checkpoint.version} · referencias: {snapshot.checkpoint.sourceIds.map((id,i)=><button key={id} onClick={()=>safe(async()=>{const r=await call({action:'message',id:chat.id,messageId:id});setFound(r.messages??[]);})}>Ver fuente {i+1}</button>)}</small></details>}
   {!!snapshot?.attachments.length&&<details><summary>Archivos de esta conversación ({snapshot.attachments.length})</summary>{snapshot.attachments.map(a=><div className="chat-attachment" key={a.id}><span>{a.name}<small>{a.problem??(a.availability==='historical'?'Captura histórica; no acredita el estado actual.':'Disponible localmente')}</small></span><button disabled={['missing','changed'].includes(a.availability)} onClick={()=>safe(async()=>{const r=await call({action:'use-attachment',id:chat.id,attachmentId:a.id});if(r.snapshot)restore(r.snapshot);})}>Adjuntar</button></div>)}</details>}
   {snapshot?.transfers.filter(t=>t.active).map(t=><div className="chat-notice" key={t.id}>Referencia de «{t.sourceTitle}» · versión {t.sourceVersion}<button onClick={()=>safe(async()=>{await call({action:'detach',id:chat.id,transferId:t.id});await refresh();})}>Retirar de futuras peticiones</button></div>)}
   {sources&&<div className="chat-transfer"><h3>Origen del contexto</h3><label>Proyecto<select value={sourceProject??''} onChange={e=>{const id=e.target.value||null;setSourceProject(id);safe(async()=>{const r=await call({action:'list',projectId:id,filter:'recent',query:'',offset:0});setSources(r.rows??[]);});}}><option value="">General</option>{projects.projects.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label>{sources.filter(s=>s.id!==chat.id).map(s=><button className="chat-row" key={s.id} onClick={()=>safe(async()=>{const r=await call({action:'read',id:s.id});if(r.snapshot)preview(r.snapshot,chat.id,projects.activeId);})}>{s.title}</button>)}<button onClick={()=>setSources(null)}>Cerrar</button></div>}
   {transfer&&<div className="chat-transfer" role="region" aria-label="Revisar contexto compartido"><h3>Revisar contexto</h3><p>Origen: {transfer.source.chat.title} · {projects.projects.find(p=>p.id===transfer.source.chat.projectId)?.name??'General'} · versión {transfer.source.chat.version}</p><p>Destino: {transfer.target===chat.id?chat.title:transfer.target?destinations.find(d=>d.id===transfer.target)?.title:'Nuevo chat'} · {projects.projects.find(p=>p.id===transfer.project)?.name??'General'}</p>{transferNew&&<><label>Proyecto de destino<select value={transfer.project??''} onChange={e=>setTransfer({...transfer,project:e.target.value||null,target:null})}><option value="">General</option>{projects.projects.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label><label>Conversación de destino<select value={transfer.target??''} onChange={e=>setTransfer({...transfer,target:e.target.value||null})}><option value="">Crear un chat nuevo</option>{destinations.filter(d=>d.id!==transfer.source.chat.id).map(d=><option key={d.id} value={d.id}>{d.title}</option>)}</select></label></>}
   <label>Fragmento editable<textarea rows={7} maxLength={24000} value={transfer.text} onChange={e=>setTransfer({...transfer,text:e.target.value})}/></label>{transfer.source.attachments.map(a=><label key={a.id}><input type="checkbox" disabled={['missing','changed'].includes(a.availability)} checked={transfer.ids.includes(a.id)} onChange={e=>setTransfer({...transfer,ids:e.target.checked?[...transfer.ids,a.id]:transfer.ids.filter(id=>id!==a.id)})}/>{a.name}</label>)}<p>Se copia esta versión. No sincroniza cambios ni transfiere permisos. Los adjuntos quedan locales hasta que los selecciones y envíes.</p><button disabled={!transfer.text.trim()} onClick={()=>safe(async()=>{const r=await call({action:'transfer',sourceId:transfer.source.chat.id,sourceVersion:transfer.source.chat.version,targetId:transfer.target,targetProject:transfer.project,text:transfer.text,attachmentIds:transfer.ids});setTransfer(null);if(r.snapshot&&r.snapshot.chat.projectId===projects.activeId)await open({action:'open',id:r.snapshot.chat.id});else notify('Contexto guardado. Cambia al proyecto de destino para abrirlo.');await refresh();})}>Usar este contexto</button><button onClick={()=>setTransfer(null)}>Cancelar</button></div>}
   {!found&&snapshot?.hasOlder&&!olderDone&&<button onClick={()=>safe(async()=>{const first=older[0]??snapshot.messages[0];const r=await call({action:'read',id:chat.id,before:first.seq});setOlder(v=>[...r.messages??[],...v]);setOlderDone(!r.messages?.length||r.messages[0].seq===1);})}>Cargar mensajes anteriores</button>}
   {away&&!list&&<button className="chat-tail" onClick={()=>{following.current=true;if(scroll.current)scroll.current.scrollTop=scroll.current.scrollHeight;}}>Ir al final ↓</button>}<div className="chat-history" aria-label="Historial de la conversación">{history.map(m=><article className={'history-message '+m.role} key={m.id} data-message-id={m.id}><header><strong>{m.role==='user'?'Tú':m.role==='context'?'Contexto seleccionado':'ZEN'}{m.role==='user'&&m.event?.utterance?' · Voz (fragmento)':''}</strong>{m.role==='assistant'&&<small>{m.event?.utterance?'Transcripción de voz · fragmento':chatStateLabel[m.state]}{m.partial&&!m.event?.utterance?' · Parcial':''}</small>}</header>{m.text?<MessageText text={m.text} notify={notify}/>:<p role="status">{m.state==='pending'?'En cola…':m.state==='running'?'Preparando respuesta…':'Sin contenido recuperable.'}</p>}{found&&<button onClick={()=>safe(async()=>{const r=await call({action:'use-message',id:chat.id,messageId:m.id});if(r.snapshot)restore(r.snapshot);notify('Fragmento añadido al contexto local. Se enviará con tu próxima petición.');})}>Usar este fragmento</button>}{m.text&&m.role==='assistant'&&!['running','pending'].includes(m.state)&&<div className="chat-filters"><button onClick={()=>safe(()=>navigator.clipboard.writeText(m.text))}>Copiar</button><button onClick={()=>safe(async()=>{const r=await window.zen.saveResult({chatId:chat.id,messageId:m.id});notify(r.ok?r.value.saved?'Texto guardado.':'Guardado cancelado.':r.error);})}>Guardar texto</button>{m.event?.artifacts?.map(a=><button key={a.id} onClick={()=>safe(async()=>{const r=await window.zen.saveResult({artifactId:a.id});notify(r.ok?r.value.saved?'Resultado guardado.':'Guardado cancelado.':r.error);})}>Guardar {a.title}</button>)}</div>}</article>)}{found&&!history.length&&<p>Sin coincidencias en esta conversación.</p>}{!history.length&&!found&&<p className="chat-empty">Un espacio para continuar tus ideas. Escribe abajo o añade contexto.</p>}</div>
  </>}
 </section>;
}
