import React,{useEffect,useRef,useState} from 'react';
import {Icon} from './components';
import {Companion} from './Companion';
import {petGeometry,type PetGeometry} from '../shared/pet';
import type {RobotPresentation} from '../shared/companion';
export function FloatingPet({quick,guide,attach,presentation,size,animated,bubbles,silent,critical,microphone,completion,home,open,region,voice,tasks,hide,dismissCompletion}:{quick:()=>void;guide:()=>void;attach:()=>void;presentation:RobotPresentation;size:number;animated:boolean;bubbles:boolean;silent:boolean;critical:boolean;microphone:boolean;completion:{id:string;text:string}|null;home:()=>void;open:()=>void;region:()=>void;voice:()=>void;tasks:()=>void;hide:()=>void;dismissCompletion:()=>void}){
  const [geometry,setGeometry]=useState<PetGeometry>(()=>petGeometry({x:0,y:0,width:300,height:390},{xRatio:.5,yRatio:.7},size)),[hover,setHover]=useState(false),[menu,setMenu]=useState(false),[more,setMore]=useState(false),[dismissed,setDismissed]=useState(false);
  const timer=useRef<ReturnType<typeof setTimeout>>(undefined),lastHover=useRef(0),gesture=useRef<{x:number;y:number;moved:boolean}>(undefined),suppress=useRef(false),button=useRef<HTMLButtonElement>(null);
  const bubble=microphone||bubbles&&!dismissed&&(critical||!silent&&(hover||!!completion));
  const kind=menu?(more?'menu':'fan'):bubble?'bubble':'none';
  useEffect(()=>{let disposed=false;void window.zen.petSurface(kind).then(r=>{if(!disposed&&r.ok)setGeometry(r.value);});return()=>{disposed=true;};},[kind,size]);
  useEffect(()=>{const off=window.zen.onPetGeometry(setGeometry);return()=>{off();clearTimeout(timer.current);void window.zen.petSurface('none');void window.zen.drag('end');};},[]);
  useEffect(()=>{setDismissed(false);},[presentation.label,completion?.id]);
  useEffect(()=>{if(menu)requestAnimationFrame(()=>document.querySelector<HTMLButtonElement>('.pet-fan button,.pet-menu button')?.focus());},[menu]);
  useEffect(()=>{if(!menu)return;void window.zen.focusOverlay();const close=()=>{setMenu(false);setMore(false);};const outside=(e:PointerEvent)=>{if(!(e.target as Element).closest('.pet-fan,.pet-menu,.pet-actions,.pet-more,.pet-avatar'))close();};window.addEventListener('blur',close);document.addEventListener('pointerdown',outside,true);return()=>{window.removeEventListener('blur',close);document.removeEventListener('pointerdown',outside,true);};},[menu]);
  const leave=()=>{clearTimeout(timer.current);setHover(false);};
  const enter=()=>{if(menu||Date.now()-lastHover.current<2000)return;clearTimeout(timer.current);timer.current=setTimeout(()=>{lastHover.current=Date.now();setHover(true);setDismissed(false);},700);};
  const dismiss=()=>{setDismissed(true);setHover(false);dismissCompletion();};
  const menuAction=(action:()=>void)=>{setMenu(false);setMore(false);leave();action();};
  const finish=(event:React.PointerEvent<HTMLButtonElement>)=>{if(!gesture.current)return;suppress.current=gesture.current.moved;gesture.current=undefined;if(event.currentTarget.hasPointerCapture(event.pointerId))event.currentTarget.releasePointerCapture(event.pointerId);void window.zen.drag('end');};
  return <div className="floating-pet" aria-label="Mascota flotante ZEN" onKeyDown={event=>{if(menu&&['ArrowDown','ArrowUp','Home','End'].includes(event.key)){event.preventDefault();const items=Array.from(event.currentTarget.querySelectorAll<HTMLButtonElement>('.pet-fan button,.pet-menu button'));const at=items.indexOf(document.activeElement as HTMLButtonElement);items[event.key==='Home'?0:event.key==='End'?items.length-1:(at+(event.key==='ArrowDown'?1:-1)+items.length)%items.length]?.focus();}if(event.key==='Escape'&&(menu||bubble)){event.preventDefault();event.stopPropagation();setMenu(false);dismiss();lastHover.current=Date.now();clearTimeout(timer.current);button.current?.focus();}if(event.key==='ContextMenu'||event.shiftKey&&event.key==='F10'){event.preventDefault();setMore(false);setMenu(true);leave();}}}>
    <button ref={button} className="pet-avatar" style={{left:geometry.avatar.x,top:geometry.avatar.y,width:size,height:size}} aria-label={`Inicio de ZEN · ${presentation.label}`} aria-haspopup="menu" onFocus={enter} onBlur={leave} onPointerEnter={enter} onPointerLeave={leave} onContextMenu={e=>{e.preventDefault();leave();setMenu(true);}} onPointerDown={event=>{if(event.button!==0)return;suppress.current=false;leave();gesture.current={x:event.screenX,y:event.screenY,moved:false};event.currentTarget.setPointerCapture(event.pointerId);void window.zen.drag('start');}} onPointerMove={event=>{const g=gesture.current;if(g&&Math.hypot(event.screenX-g.x,event.screenY-g.y)>=7)g.moved=true;}} onPointerUp={finish} onPointerCancel={finish} onLostPointerCapture={finish} onClick={event=>{if(suppress.current){event.preventDefault();suppress.current=false;return;}home();}}>
      <Companion pose={presentation.pose} animated={animated}/>
    </button>
    {menu&&!more?<div className={'pet-fan '+(geometry.actions?'arc':'fallback')} role="menu" aria-label="Acciones de ZEN" style={geometry.actions?undefined:{left:geometry.surface.x,top:geometry.surface.y,width:geometry.surface.width,height:geometry.surface.height}}>{[{text:'Hablar',icon:'mic' as const,action:voice},{text:'Capturar',icon:'screen' as const,action:region},{text:'Adjuntar',icon:'attach' as const,action:attach},{text:'Chat',icon:'chat' as const,action:open}].map((item,index)=><button key={item.text} role="menuitem" style={geometry.actions?{left:geometry.actions[index].x,top:geometry.actions[index].y,width:geometry.actions[index].width,height:geometry.actions[index].height}:undefined} onClick={()=>menuAction(item.action)}><Icon name={item.icon}/><span>{item.text}</span></button>)}</div>:menu?<div className="pet-menu" role="menu" aria-label="Acciones de ZEN" style={{width:geometry.surface.width,height:geometry.surface.height,left:geometry.surface.x,top:geometry.surface.y}}>{[{text:'Abrir conversación',action:open},{text:'Pregunta rápida',action:quick},{text:'Guíame',action:guide},{text:'Adjuntar archivos',action:attach},{text:'Señalar en pantalla',action:region},{text:'Control de voz',action:voice},{text:'Últimas tareas',action:tasks},{text:'Ajustes',action:()=>{void window.zen.openPreferences();}},{text:'Ocultar mascota',action:hide}].map(item=><button role="menuitem" key={item.text} onClick={()=>menuAction(item.action)}>{item.text}</button>)}<button role="menuitem" onClick={()=>{setMenu(false);button.current?.focus();}}>Cerrar menú</button></div>:bubble&&<aside className="pet-bubble" style={{left:geometry.surface.x,top:geometry.surface.y,width:geometry.surface.width,height:geometry.surface.height}} aria-label="Estado de ZEN"><button className="pet-bubble-content" onClick={open}><strong>{critical?presentation.label:microphone?'Escuchando':completion?'Tarea completada':presentation.label}</strong><span>{critical?presentation.hint:microphone?'Usa Control de voz para silenciar.':completion?.text??'¿En qué te ayudo?'}</span>{microphone&&<small>Micrófono activo</small>}</button><button className="pet-bubble-close" aria-label="Cerrar burbuja" onClick={dismiss}>×</button></aside>}
    <button className="pet-actions" aria-label={menu?'Cerrar acciones':'Acciones de la mascota'} title={menu?'Cerrar acciones':'Acciones'} aria-expanded={menu} onClick={()=>{setMore(false);setMenu(!menu);leave();}} style={{left:geometry.avatar.x+size/2-16,top:geometry.avatar.y+size-30}}>•••</button>
    {menu&&<button className="pet-more" title="Más opciones" aria-label="Más opciones de la mascota" style={{left:geometry.avatar.x+size/2-16,top:geometry.avatar.y+3}} onClick={()=>setMore(!more)}>+</button>}
    {microphone&&!menu&&<button className="pet-more" aria-label="Silenciar micrófono" title="Silenciar micrófono" style={{left:geometry.avatar.x+size/2-16,top:geometry.avatar.y+3}} onClick={voice}><Icon name="mute"/></button>}
    <span className="pet-accessible-status" role="status">{presentation.label}</span>
  </div>;
}
