import React,{useEffect,useRef,useState} from 'react';
import type {ProjectContexts} from '../shared/project-context';
import {Icon} from './components';
export function ProjectPicker({value,locked,select,manage}:{value:ProjectContexts;locked:boolean;select:(id:string|null)=>Promise<boolean>;manage:()=>void}){
  const [open,setOpen]=useState(false),[query,setQuery]=useState('');
  const root=useRef<HTMLDivElement>(null),trigger=useRef<HTMLButtonElement>(null);
  const close=()=>{setOpen(false);trigger.current?.focus();};
  useEffect(()=>{if(!open)return;const outside=(e:PointerEvent)=>{if(!root.current?.contains(e.target as Node))close();};const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){e.preventDefault();e.stopPropagation();close();}};document.addEventListener('pointerdown',outside,true);document.addEventListener('keydown',key,true);root.current?.querySelector<HTMLElement>('.project-picker-panel input,.project-card-choice')?.focus();return()=>{document.removeEventListener('pointerdown',outside,true);document.removeEventListener('keydown',key,true);};},[open]);
  const current=value.projects.find(p=>p.id===value.activeId);
  const projects=[{id:null,name:'General',detail:'Perfil general'},...value.projects.map(p=>({...p,detail:p.documents.filter(d=>d.enabled).length+' referencias elegidas'}))].filter(p=>p.name.toLocaleLowerCase().includes(query.toLocaleLowerCase()));
  return <div className="project-picker" ref={root}><button ref={trigger} className="project-chip" aria-label={'Proyecto: '+(current?.name??'General')} title={'Cambiar proyecto · '+(current?.name??'General')} aria-expanded={open} aria-haspopup="dialog" onClick={()=>{setOpen(!open);setQuery('');}}><Icon name="folder"/><span>{current?.name??'General'}</span><small>Cambiar</small></button>{open&&<section className="project-picker-panel" role="dialog" aria-label="Seleccionar proyecto"><div className="panel-heading"><strong>Tu proyecto</strong><button aria-label="Cerrar selector de proyecto" onClick={close}>×</button></div>{value.projects.length>5&&<input aria-label="Buscar proyecto" placeholder="Buscar proyecto" value={query} onChange={e=>setQuery(e.target.value)}/>}<div className="project-choices" onKeyDown={e=>{if(!['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;const items=Array.from(e.currentTarget.querySelectorAll<HTMLButtonElement>('button:not(:disabled)'));if(!items.length)return;e.preventDefault();const at=items.indexOf(document.activeElement as HTMLButtonElement);items[e.key==='Home'?0:e.key==='End'?items.length-1:(at+(['ArrowUp','ArrowLeft'].includes(e.key)?-1:1)+items.length)%items.length]?.focus();}}>{projects.map(p=><button className="project-card-choice" key={p.id??'general'} aria-pressed={value.activeId===p.id} disabled={locked} onClick={async()=>{if(p.id===value.activeId||await select(p.id))close();}}><Icon name="folder"/><span><strong>{p.name}</strong><small>{p.detail}</small></span>{value.activeId===p.id&&<Icon name="check"/>}</button>)}{!projects.length&&<p>No hay proyectos con ese nombre.</p>}</div>{locked&&<p role="status">Espera a que termine la tarea o la preparación para cambiar.</p>}<button className="manage-projects" onClick={()=>{close();manage();}}>Gestionar proyectos</button></section>}</div>;
}
