import React,{useRef,useState} from 'react';
import type {VisualReference} from '../shared/interactions';
type Point={x:number;y:number};
type Mark={type:'circle'|'arrow'|'stroke';points:Point[]};
function draw(context:CanvasRenderingContext2D,mark:Mark,w:number,h:number){
  const points=mark.points.map(p=>({x:p.x*w,y:p.y*h})),[a,b]=points;if(!b)return;
  context.strokeStyle='#ffcf70';context.lineWidth=Math.max(3,Math.min(w,h)/130);context.lineCap='round';context.beginPath();
  if(mark.type==='circle')context.ellipse((a.x+b.x)/2,(a.y+b.y)/2,Math.abs(a.x-b.x)/2,Math.abs(a.y-b.y)/2,0,0,Math.PI*2);
  else{context.moveTo(a.x,a.y);points.slice(1).forEach(p=>context.lineTo(p.x,p.y));if(mark.type==='arrow'){const angle=Math.atan2(b.y-a.y,b.x-a.x),length=Math.max(12,Math.min(w,h)/25);context.moveTo(b.x-Math.cos(angle-.5)*length,b.y-Math.sin(angle-.5)*length);context.lineTo(b.x,b.y);context.lineTo(b.x-Math.cos(angle+.5)*length,b.y-Math.sin(angle+.5)*length);}}
  context.stroke();
}
export function RegionPicker({image,done,cancel,source='Pantalla de ZEN',capturedAt=Date.now()}:{image:string;source?:string;capturedAt?:number;done:(value:string,reference:VisualReference,question:string)=>void;cancel:()=>void}){
  const img=useRef<HTMLImageElement>(null),start=useRef<Point|undefined>(undefined),[area,setArea]=useState<{x:number;y:number;w:number;h:number}>();
  const [cropped,setCropped]=useState<string>(),[reference,setReference]=useState<VisualReference>(),[tool,setTool]=useState<Mark['type']>('arrow'),[marks,setMarks]=useState<Mark[]>([]),[current,setCurrent]=useState<Mark>(),[question,setQuestion]=useState(''),[error,setError]=useState('');
  const at=useRef(capturedAt),base=useRef<HTMLCanvasElement|undefined>(undefined);
  const point=(e:React.PointerEvent)=>{const b=img.current!.getBoundingClientRect();return{x:Math.max(0,Math.min(1,(e.clientX-b.left)/b.width)),y:Math.max(0,Math.min(1,(e.clientY-b.top)/b.height))};};
  const crop=()=>{if(!area||!img.current)return;try{const image=img.current,canvas=document.createElement('canvas'),x=Math.round(area.x*image.naturalWidth),y=Math.round(area.y*image.naturalHeight),width=Math.min(image.naturalWidth-x,Math.round(area.w*image.naturalWidth)),height=Math.min(image.naturalHeight-y,Math.round(area.h*image.naturalHeight));if(width<8||height<8)return;const scale=Math.min(1,1920/Math.max(width,height));canvas.width=Math.round(width*scale);canvas.height=Math.round(height*scale);canvas.getContext('2d')!.drawImage(image,x,y,width,height,0,0,canvas.width,canvas.height);base.current=canvas;setCropped(canvas.toDataURL('image/jpeg',.85));setReference({id:crypto.randomUUID(),width:canvas.width,height:canvas.height,capturedAt:at.current,source,crop:{x,y,width,height}});}catch{setError('No se pudo recortar. Cancela y vuelve a capturar.');}};
  const rendered=()=>{if(!base.current)return '';const canvas=document.createElement('canvas');canvas.width=base.current.width;canvas.height=base.current.height;const context=canvas.getContext('2d')!;context.drawImage(base.current,0,0);marks.forEach(mark=>draw(context,mark,canvas.width,canvas.height));return canvas.toDataURL('image/jpeg',.85);};
  const [preview,setPreview]=useState<string>();
  return <section className="region-picker" aria-label="Seleccionar zona de pantalla"><div className="context-heading"><strong>{cropped?'Señala dentro del recorte':'Recorta lo que quieres compartir'}</strong><button onClick={cancel} aria-label="Cancelar selección de zona">×</button></div><p>{cropped?'Solo se compartirá este recorte con sus marcas. Una marca no cambia el recorte.':'Arrastra un rectángulo sobre esta captura congelada. Esc cancela sin enviar.'}</p>
    {cropped&&<div className="context-actions">{(['arrow','circle','stroke'] as const).map(type=><button key={type} aria-pressed={type===tool} onClick={()=>{setTool(type);setPreview(undefined);}}>{type==='arrow'?'Flecha':type==='circle'?'Círculo':'Trazo'}</button>)}<button disabled={!marks.length} onClick={()=>{setMarks(rows=>rows.slice(0,-1));setPreview(undefined);}}>Deshacer marca</button><button onClick={()=>{setCropped(undefined);setReference(undefined);setMarks([]);setPreview(undefined);}}>Cambiar recorte</button></div>}
    <div className="region-image" onPointerDown={e=>{if(e.button!==0||preview)return;e.currentTarget.setPointerCapture(e.pointerId);start.current=point(e);if(cropped)setCurrent({type:tool,points:[start.current,start.current]});else setArea(undefined);}} onPointerMove={e=>{if(!start.current)return;const p=point(e),s=start.current;if(cropped)setCurrent(previous=>previous?{...previous,points:tool==='stroke'?[...previous.points.slice(-98),p]:[s,p]}:previous);else setArea({x:Math.min(s.x,p.x),y:Math.min(s.y,p.y),w:Math.abs(p.x-s.x),h:Math.abs(p.y-s.y)});}} onPointerUp={()=>{start.current=undefined;if(current){setMarks(rows=>[...rows,current].slice(-20));setCurrent(undefined);}}} onPointerCancel={()=>{start.current=undefined;setCurrent(undefined);}}><img ref={img} src={preview??cropped??image} alt={preview?'Vista previa exacta del recorte anotado':'Pantalla para seleccionar una zona'} draggable={false}/>{!cropped&&area&&<span className="region-box" style={{left:`${area.x*100}%`,top:`${area.y*100}%`,width:`${area.w*100}%`,height:`${area.h*100}%`}}/>}{cropped&&!preview&&<svg className="annotation-layer" viewBox={`0 0 ${reference!.width} ${reference!.height}`} aria-hidden="true">{[...marks,...(current?[current]:[])].map((mark,i)=>{const w=reference!.width,h=reference!.height,[a,b]=mark.points,angle=Math.atan2((b.y-a.y)*h,(b.x-a.x)*w),length=Math.max(12,Math.min(w,h)/25);return <g key={i} fill="none" stroke="#ffcf70" strokeWidth={Math.max(3,Math.min(w,h)/130)} strokeLinecap="round">{mark.type==='circle'?<ellipse cx={(a.x+b.x)*w/2} cy={(a.y+b.y)*h/2} rx={Math.abs(a.x-b.x)*w/2} ry={Math.abs(a.y-b.y)*h/2}/>:<polyline points={mark.points.map(p=>`${p.x*w},${p.y*h}`).join(' ')}/ >}{mark.type==='arrow'&&<polyline points={`${b.x*w-Math.cos(angle-.5)*length},${b.y*h-Math.sin(angle-.5)*length} ${b.x*w},${b.y*h} ${b.x*w-Math.cos(angle+.5)*length},${b.y*h-Math.sin(angle+.5)*length}`}/>}</g>;})}</svg>}</div>
    {error&&<p role="alert">{error}</p>}{!cropped?<button disabled={!area||area.w<.01||area.h<.01} onClick={crop}>Usar esta zona</button>:<><label className="region-question">¿Qué quieres saber sobre esta zona?<textarea maxLength={8000} value={question} onChange={e=>setQuestion(e.target.value)}/></label><div className="context-actions"><button onClick={()=>setPreview(value=>value?undefined:rendered())}>{preview?'Editar marcas':'Ver imagen exacta'}</button><button onClick={()=>{const output=rendered();if(output.length>3000000)return setError('El recorte es demasiado grande. Elige una zona menor.');done(output,reference!,question);}}>Adjuntar recorte</button></div></>}
  </section>;
}
