import React,{useEffect,useRef,useState} from 'react';
import type {TaskEvent} from '../shared/contracts';
import {taskStatus,type Favorite} from '../shared/workspace';
import {isExternalCodexTask} from '../shared/project';
import type {ProjectContexts} from '../shared/project-context';
export function WorkspacePanel({use,notify,tasks,draft,resume,projects,review,stop}:{use:(text:string,taskId?:string)=>void;notify:(text:string)=>void;tasks:TaskEvent[];draft:string;resume:React.ReactNode;projects:ProjectContexts;review:()=>void;stop:()=>void}){
  const [tab,setTab]=useState<'tasks'|'favorites'>('tasks'),[favorites,setFavorites]=useState<Favorite[]>([]),[editing,setEditing]=useState<string>(),[label,setLabel]=useState(''),[prompt,setPrompt]=useState(''),[selected,setSelected]=useState<string>(),[filter,setFilter]=useState(''),[suggestions,setSuggestions]=useState(false);
  const [titles,setTitles]=useState<Record<string,string>>(()=>{try{const v=JSON.parse(localStorage.getItem('zen-task-titles')??'{}');return Object.fromEntries(Object.entries(v).filter(([k,v])=>k.length<100&&typeof v==='string'&&v.length<=120).slice(-100)) as Record<string,string>;}catch{return {};}});
  const list=useRef<HTMLDivElement>(null),openButton=useRef<HTMLButtonElement|null>(null);
  useEffect(()=>{void window.zen.favorites().then(r=>r.ok?setFavorites(r.value):notify(r.error));},[]);
  useEffect(()=>{setSelected(undefined);setFilter('');if(list.current)list.current.scrollTop=0;},[projects.activeId]);
  const save=async(rows:Favorite[])=>{const r=await window.zen.saveFavorites(rows);if(!r.ok)return notify(r.error);setFavorites(r.value);setEditing(undefined);setLabel('');setPrompt('');};
  const title=(row:TaskEvent)=>titles[row.id]??row.request??row.approval?.title??'Tarea';
  const rows=tasks.filter(t=>(t.request||t.approval)&&(t.projectContextId??null)===projects.activeId).slice(-100).reverse().filter(row=>title(row).toLocaleLowerCase().includes(filter.toLocaleLowerCase()));
  const row=tasks.find(t=>t.id===selected&&(t.projectContextId??null)===projects.activeId),active=row&&['queued','thinking','executing','awaiting_approval'].includes(row.state);
  const back=()=>{setSelected(undefined);requestAnimationFrame(()=>openButton.current?.focus({preventScroll:true}));};
  return <section className="workspace-panel" aria-label="Tareas y favoritos">
    <div className="panel-heading"><h2>{row?'Detalle de la tarea':'Tareas'}</h2>{row?<button onClick={back}>Volver a tareas</button>:<button aria-pressed={tab==='favorites'} onClick={()=>setTab(tab==='tasks'?'favorites':'tasks')}>{tab==='tasks'?'Favoritos':'Tareas recientes'}</button>}</div>
    <div className="workspace-list content-scroll" ref={list} hidden={!!row}>
      {tab==='tasks'?<>{resume}<label className="task-filter">Buscar tarea<input value={filter} onChange={e=>setFilter(e.target.value)} placeholder="Título de la petición"/></label>
      {draft.trim()&&<article className="task-row"><div><strong>{draft}</strong><small>Preparada · sin enviar</small></div><button onClick={()=>use(draft)}>Continuar</button></article>}
      {!rows.length&&<p>No hay tareas que mostrar en este proyecto.</p>}
      {rows.map(item=><article className="task-row" key={item.id} data-task-id={item.id}><div><strong title={title(item)}>{title(item)}</strong><small role="status">{taskStatus(item)}</small></div><button aria-label={'Abrir tarea: '+title(item)} onClick={e=>{openButton.current=e.currentTarget;setSelected(item.id);}}>Abrir</button></article>)}</>:<>
      <div className="favorite-list">{favorites.map(fav=><article className="favorite-row" key={fav.id}><strong>{fav.label}</strong><div className="context-actions"><button onClick={()=>use(fav.prompt)}>Usar</button><button onClick={()=>{setEditing(fav.id);setLabel(fav.label);setPrompt(fav.prompt);}}>Editar</button><button onClick={()=>void save(favorites.filter(f=>f.id!==fav.id))}>Quitar</button></div></article>)}</div>
      <button aria-expanded={suggestions} onClick={()=>setSuggestions(!suggestions)}>Rutinas sugeridas</button>{suggestions&&<div className="context-actions">{[{label:'Explica este error',prompt:'Explica este error y los pasos para resolverlo.'},{label:'Revisa JS de Dynamics',prompt:'Revisa este JavaScript de Dynamics: errores, impacto y correcciones propuestas para mi revisión.'},{label:'Respuesta en inglés',prompt:'Redacta una respuesta en inglés al mensaje adjunto. Usa un tono cordial y breve; la revisaré antes de enviarla.'}].map(fav=><button key={fav.label} onClick={()=>{setEditing(undefined);setLabel(fav.label);setPrompt(fav.prompt);}}>{fav.label}</button>)}</div>}
      <form onSubmit={event=>{event.preventDefault();if(label.trim()&&prompt.trim())void save([...favorites.filter(f=>f.id!==editing),{id:editing??crypto.randomUUID(),label:label.trim(),prompt:prompt.trim()}]);}}><label>Nombre<input value={label} maxLength={50} onChange={e=>setLabel(e.target.value)} required/></label><label>Instrucción<textarea value={prompt} maxLength={2000} onChange={e=>setPrompt(e.target.value)} required/></label><button type="submit" disabled={!editing&&favorites.length>=20}>{editing?'Guardar favorito':'Añadir favorito'}</button></form></>}
    </div>
    {row&&<div className="task-detail content-scroll"><label>Título de la tarea<input aria-label="Título de la tarea" maxLength={120} value={title(row).slice(0,120)} onChange={e=>{const next={...titles,[row.id]:e.target.value};setTitles(next);try{localStorage.setItem('zen-task-titles',JSON.stringify(Object.fromEntries(Object.entries(next).slice(-100))));}catch{notify('No se pudo guardar el título local.');}}}/></label><p role="status">{taskStatus(row)}</p><p className="task-request">{row.request}</p>{isExternalCodexTask(row)&&<p>Preparada en Codex. Falta pulsar Enviar allí; ZEN no recibe su ejecución ni su resultado.</p>}<p className="task-result">{row.checkpoint??row.message}</p><div className="context-actions"><button onClick={()=>use('',row.id)}>Retomar conversación</button>{taskStatus(row)==='Necesita permiso'&&<button onClick={review}>Revisar acción</button>}{active&&<button className="danger" onClick={stop}>Detener</button>}{row.undoAvailable&&<button onClick={()=>void window.zen.undoCreation(row.id).then(r=>{if(!r.ok)notify(r.error);else review();})}>Deshacer creación…</button>}{row.state==='completed'&&<button onClick={()=>void window.zen.saveResult({taskId:row.id}).then(r=>notify(r.ok?r.value.saved?'Resultado guardado.':'Guardado cancelado.':r.error))}>Guardar resultado</button>}</div></div>}
  </section>;
}
