import React,{useEffect,useState} from 'react';
import type {TaskEvent} from '../shared/contracts';
import type {Favorite} from '../shared/workspace';
import {isExternalCodexTask} from '../shared/project';
export function WorkspacePanel({close,use,notify}:{close:()=>void;use:(text:string,taskId?:string)=>void;notify:(text:string)=>void}){
  const [tab,setTab]=useState<'tasks'|'favorites'>('tasks'),[tasks,setTasks]=useState<TaskEvent[]>([]),[favorites,setFavorites]=useState<Favorite[]>([]),[editing,setEditing]=useState<string>(),[label,setLabel]=useState(''),[prompt,setPrompt]=useState('');
  useEffect(()=>{void window.zen.tasks().then(r=>r.ok?setTasks(r.value.filter(t=>t.request).reverse()):notify(r.error));void window.zen.favorites().then(r=>r.ok?setFavorites(r.value):notify(r.error));},[]);
  const save=async(rows:Favorite[])=>{const r=await window.zen.saveFavorites(rows);if(!r.ok)return notify(r.error);setFavorites(r.value);setEditing(undefined);setLabel('');setPrompt('');};
  return <section className="workspace-panel" aria-label="Tareas y favoritos"><div className="context-heading"><strong>Tu espacio de trabajo</strong><button onClick={close} aria-label="Cerrar tareas y favoritos">×</button></div><nav aria-label="Vista de trabajo"><button aria-pressed={tab==='tasks'} onClick={()=>setTab('tasks')}>Tareas recientes</button><button aria-pressed={tab==='favorites'} onClick={()=>setTab('favorites')}>Favoritos</button></nav>
    <div className="workspace-list">{tab==='tasks'?tasks.length?tasks.slice(0,20).map(row=><article key={row.id}><strong>{row.request?.slice(0,130)}</strong><small>{isExternalCodexTask(row)?'En Codex del escritorio':row.paused?'En pausa':row.state==='completed'?'Completada':row.state==='failed'?'Interrumpida':row.state==='cancelled'?'Detenida':row.state==='awaiting_input'?'Espera tu intervención':'En curso'}</small><p>{row.checkpoint??row.message.slice(-250)}</p><button onClick={()=>use(row.request??'',row.id)}>Retomar / corregir</button><button onClick={()=>void window.zen.saveResult({taskId:row.id}).then(r=>notify(r.ok?r.value.saved?'Resultado guardado.':'Guardado cancelado.':r.error))}>Guardar resultado</button></article>):<p>Aquí podrás recuperar tus tareas. Retomar prepara una petición editable y obtiene contexto nuevo al enviarla.</p>:<><div className="favorite-list">{favorites.map(row=><article key={row.id}><strong>{row.label}</strong><p>{row.prompt}</p><button onClick={()=>use(row.prompt)}>Usar</button><button onClick={()=>{setEditing(row.id);setLabel(row.label);setPrompt(row.prompt);}}>Editar</button><button onClick={()=>void save(favorites.filter(f=>f.id!==row.id))}>Quitar</button></article>)}</div><form onSubmit={event=>{event.preventDefault();if(label.trim()&&prompt.trim())void save([...favorites.filter(f=>f.id!==editing),{id:editing??crypto.randomUUID(),label:label.trim(),prompt:prompt.trim()}]);}}><label>Nombre<input value={label} maxLength={50} onChange={e=>setLabel(e.target.value)} required/></label><label>Instrucción<textarea value={prompt} maxLength={2000} onChange={e=>setPrompt(e.target.value)} required/></label><button type="submit">{editing?'Guardar favorito':'Añadir favorito'}</button></form></>}</div>
    <small>Guardado local · elegir una tarea o favorito no inicia llamadas.</small></section>;
}
